import type { Context } from '@deepseek-ai/cordis'
import { defineTool } from '@deepseek-ai/dsh-tools'

// ==================== PRNG & HELPERS ====================

function mulberry32(seed: number): () => number {
  return () => {
    let t = (seed += 0x6d2b79f5)
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function hashString(str: string): number {
  let hash = 0
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i)
    hash = ((hash << 5) - hash + char) | 0
  }
  return Math.abs(hash)
}

function initRng(input: object): () => number {
  const seed = hashString(JSON.stringify(input))
  return mulberry32(seed)
}

function rngRange(rng: () => number, min: number, max: number): number {
  return Math.floor(rng() * (max - min + 1)) + min
}

function clamp(val: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, val))
}

function pickItems(rng: () => number, items: string[], count: number): string[] {
  const shuffled = [...items].sort(() => rng() - 0.5)
  return shuffled.slice(0, count)
}

const DISCLAIMER = '---\n*Disclaimer: This analysis is generated by AI and is for informational and creative planning purposes only. It does not constitute legal advice, IP counsel, or financial guidance. Always consult qualified IP attorneys, valuation professionals, and licensing experts before making legal or commercial decisions.*'

const VERSION = '1.0.0'

// ==================== TOOL 1: IP REGISTRATION ADVISOR ====================

interface IPRRegistrationInput {
  work_type: string
  jurisdiction: string[]
  budget_usd: number
  commercial_potential: 'low' | 'medium' | 'high' | 'blockbuster'
  prior_art_search_needed: boolean
}

interface IPRegistrationAction {
  type: string
  estimated_cost_usd: number
  timeline_months: number
  priority: 'critical' | 'high' | 'medium' | 'low'
  notes: string
}

interface IPRegistrationResult {
  registration_strategy: string
  actions: IPRegistrationAction[]
  total_estimated_cost: number
  risk_level: string
  timeline_months: number
  summary: string
}

function adviseIPRegistration(input: IPRRegistrationInput): IPRegistrationResult {
  const rng = initRng(input)
  const jurisdictions = input.jurisdiction.length > 0 ? input.jurisdiction : ['US']
  const commercial = input.commercial_potential || 'medium'
  const budget = input.budget_usd || 5000
  const workType = input.work_type || 'digital_art'

  const actions: IPRegistrationAction[] = []

  // Copyright registration
  const copyrightBaseCost = jurisdictions.length * rngRange(rng, 35, 65)
  actions.push({
    type: 'Copyright Registration',
    estimated_cost_usd: copyrightBaseCost,
    timeline_months: rngRange(rng, 3, 8),
    priority: 'critical',
    notes: 'Automatic upon creation, but registration required for statutory damages in US. File in each target jurisdiction.',
  })

  // Trademark (if commercial potential is medium+)
  if (commercial !== 'low') {
    const tmCost = jurisdictions.length * rngRange(rng, 1000, 2500)
    actions.push({
      type: 'Trademark Registration (Name/Logo)',
      estimated_cost_usd: tmCost,
      timeline_months: rngRange(rng, 8, 18),
      priority: commercial === 'high' || commercial === 'blockbuster' ? 'critical' : 'high',
      notes: `Protects brand identity across ${jurisdictions.length} jurisdiction(s). Essential for merchandising and franchise value. Madrid Protocol can reduce multi-country costs by 40-60%.`,
    })
  }

  // Patent (only for certain work types)
  if (workType === 'game_mechanics' || workType === 'software' || workType === 'interactive_system') {
    const patentCost = rngRange(rng, 8000, 15000)
    if (budget > patentCost * 0.5) {
      actions.push({
        type: 'Utility/Design Patent',
        estimated_cost_usd: patentCost,
        timeline_months: rngRange(rng, 18, 36),
        priority: 'medium',
        notes: 'Consider provisional patent first ($2,000-3,500) to secure priority date. Full patent is expensive — evaluate ROI based on product lifecycle.',
      })
    }
  }

  // Prior art search
  if (input.prior_art_search_needed) {
    actions.push({
      type: 'Prior Art Search',
      estimated_cost_usd: rngRange(rng, 1500, 5000),
      timeline_months: rngRange(rng, 1, 3),
      priority: 'high',
      notes: 'Essential before full IP investment. Identifies potential infringement risks and strengthens application quality.',
    })
  }

  // International strategy
  if (jurisdictions.length > 1) {
    actions.push({
      type: 'International IP Filing Strategy',
      estimated_cost_usd: rngRange(rng, 2000, 8000),
      timeline_months: rngRange(rng, 6, 24),
      priority: 'high',
      notes: 'PCT Patent, Madrid Protocol Trademark, Berne Convention Copyright (automatic in 180+ countries). Budget for translation and local counsel fees.',
    })
  }

  // Monitoring / enforcement setup
  actions.push({
    type: 'IP Monitoring Setup',
    estimated_cost_usd: rngRange(rng, 500, 3000),
    timeline_months: rngRange(rng, 1, 2),
    priority: 'medium',
    notes: 'Set up watch services for trademark, copyright infringement monitoring, and domain name monitoring.',
  })

  // Sort by priority
  const priorityOrder = { critical: 0, high: 1, medium: 2, low: 3 }
  actions.sort((a, b) => priorityOrder[a.priority] - priorityOrder[b.priority])

  const totalCost = actions.reduce((s, a) => s + a.estimated_cost_usd, 0)
  const maxTimeline = Math.max(...actions.map(a => a.timeline_months))

  let riskLevel = 'low'
  if (actions.some(a => a.priority === 'critical' && a.estimated_cost_usd > budget * 0.4)) riskLevel = 'medium'
  if (totalCost > budget * 1.5) riskLevel = 'high'

  let strategy = 'Phased Registration'
  if (budget > totalCost * 1.2) strategy = 'Full-Stack IP Protection'
  else if (budget < totalCost * 0.5) strategy = 'Essential-Only Protection'

  return {
    registration_strategy: strategy,
    actions,
    total_estimated_cost: totalCost,
    risk_level: riskLevel,
    timeline_months: maxTimeline,
    summary: `Strategy: ${strategy} | Total estimated cost: $${totalCost.toLocaleString()} across ${actions.length} actions | Budget: $${budget.toLocaleString()} | Risk: ${riskLevel} | ${jurisdictions.length} jurisdiction(s)`,
  }
}

function formatIPRegistrationReport(input: IPRRegistrationInput, result: IPRegistrationResult): string {
  const lines: string[] = []

  lines.push('## IP Registration Strategy')
  lines.push('')
  lines.push(`**${input.work_type || 'Creative Work'}** | Jurisdictions: ${input.jurisdiction.join(', ') || 'US'} | Budget: $${(input.budget_usd || 0).toLocaleString()}`)
  lines.push('')
  lines.push(result.summary)
  lines.push('')

  lines.push('### Recommended Actions')
  lines.push('| # | Action | Cost (USD) | Timeline | Priority | Notes |')
  lines.push('|---|--------|------------|----------|----------|-------|')
  let idx = 1
  for (const a of result.actions) {
    const priTag = a.priority.toUpperCase()
    lines.push(`| ${idx} | ${a.type} | $${a.estimated_cost_usd.toLocaleString()} | ${a.timeline_months}mo | ${priTag} | ${a.notes} |`)
    idx++
  }
  lines.push('')

  lines.push(`### Budget Analysis`)
  lines.push(`- **Estimated Total**: $${result.total_estimated_cost.toLocaleString()}`)
  lines.push(`- **Available Budget**: $${(input.budget_usd || 0).toLocaleString()}`)
  const coverage = input.budget_usd > 0 ? Math.min(100, Math.round((input.budget_usd / result.total_estimated_cost) * 100)) : 0
  lines.push(`- **Budget Coverage**: ${coverage}%`)
  lines.push(`- **Risk Level**: ${result.risk_level.toUpperCase()}`)
  lines.push('')

  lines.push('### Commercial Potential Context')
  lines.push(`- **Level**: ${input.commercial_potential || 'medium'}`)
  lines.push(`- **Recommendation**: ${result.registration_strategy}`)
  lines.push('')

  lines.push(DISCLAIMER)
  return lines.join('\n')
}

// ==================== TOOL 2: DERIVATIVE WORKS STRATEGIST ====================

interface DerivativeWorksInput {
  original_ip: { name: string; genre: string; audience: string }
  target_formats: string[]
  market_demand: { format: string; demand_score: number }[]
  budget_usd: number
  timeline_months: number
}

interface DerivativePlan {
  format: string
  priority: 'must_do' | 'high' | 'medium' | 'low'
  estimated_revenue_usd: number
  estimated_cost_usd: number
  timeline_months: number
  notes: string
}

interface DerivativeWorksResult {
  total_revenue_potential: number
  total_investment: number
  plans: DerivativePlan[]
  roadmap: string[]
  summary: string
}

function planDerivativeWorks(input: DerivativeWorksInput): DerivativeWorksResult {
  const rng = initRng(input)
  const formats = input.target_formats.length > 0 ? input.target_formats : ['merchandise', 'digital_content']
  const budget = input.budget_usd || 10000
  const timeline = input.timeline_months || 12
  const ipName = input.original_ip?.name || 'IP'

  const allFormatPools: Record<string, { costRange: [number, number]; revenueMult: number; speed: string }> = {
    merchandise: { costRange: [2000, 15000], revenueMult: 1.5, speed: 'fast' },
    graphic_novel: { costRange: [5000, 40000], revenueMult: 2.0, speed: 'medium' },
    animated_series: { costRange: [20000, 500000], revenueMult: 5.0, speed: 'slow' },
    video_game: { costRange: [10000, 200000], revenueMult: 3.5, speed: 'slow' },
    live_action: { costRange: [50000, 5000000], revenueMult: 8.0, speed: 'very_slow' },
    mobile_app: { costRange: [3000, 50000], revenueMult: 2.5, speed: 'medium' },
    digital_collectible: { costRange: [1000, 20000], revenueMult: 1.8, speed: 'fast' },
    fiction_novel: { costRange: [2000, 25000], revenueMult: 1.5, speed: 'medium' },
    soundtrack_album: { costRange: [3000, 30000], revenueMult: 1.3, speed: 'medium' },
    vr_experience: { costRange: [15000, 300000], revenueMult: 2.0, speed: 'slow' },
  }

  const plans: DerivativePlan[] = []
  for (const format of formats) {
    const pool = allFormatPools[format] || { costRange: [2000, 15000], revenueMult: 1.5, speed: 'medium' }
    const demand = input.market_demand?.find(m => m.format === format)?.demand_score || rngRange(rng, 40, 85)
    const cost = rngRange(rng, pool.costRange[0], pool.costRange[1])
    const revenue = Math.round(cost * pool.revenueMult * (demand / 70) * (0.8 + rng() * 0.4))

    let priority: DerivativePlan['priority'] = 'medium'
    if (demand >= 80 && pool.speed === 'fast') priority = 'must_do'
    else if (demand >= 65) priority = 'high'
    else if (demand < 45) priority = 'low'

    const speedMonths = pool.speed === 'fast' ? rngRange(rng, 1, 3) : pool.speed === 'medium' ? rngRange(rng, 3, 8) : pool.speed === 'slow' ? rngRange(rng, 6, 18) : rngRange(rng, 12, 36)

    plans.push({
      format,
      priority,
      estimated_revenue_usd: revenue,
      estimated_cost_usd: cost,
      timeline_months: clamp(speedMonths, 1, timeline),
      notes: `Demand score: ${demand}/100 | Speed: ${pool.speed} | Expected revenue multiplier: ${pool.revenueMult}x`,
    })
  }

  // Sort by priority
  const priorityOrder = { must_do: 0, high: 1, medium: 2, low: 3 }
  plans.sort((a, b) => priorityOrder[a.priority] - priorityOrder[b.priority])

  const totalRevenue = plans.reduce((s, p) => s + p.estimated_revenue_usd, 0)
  const totalInvestment = plans.reduce((s, p) => s + p.estimated_cost_usd, 0)

  const roadmap: string[] = []
  const mustDo = plans.filter(p => p.priority === 'must_do')
  const high = plans.filter(p => p.priority === 'high')

  if (mustDo.length > 0) roadmap.push(`Phase 1 (0-3 months): Launch ${mustDo.map(p => p.format).join(', ')} — high-demand fast formats`)
  if (high.length > 0) roadmap.push(`Phase 2 (3-${Math.min(12, timeline)} months): Develop ${high.map(p => p.format).join(', ')} — expand audience reach`)
  roadmap.push(`Phase 3 (${Math.min(12, timeline)}+ months): Evaluate remaining formats based on Phase 1-2 performance data`)
  roadmap.push('Cross-promote all formats: each derivative drives traffic to the original and other products')

  return {
    total_revenue_potential: totalRevenue,
    total_investment: totalInvestment,
    plans,
    roadmap,
    summary: `${ipName} | ${plans.length} derivative format(s) planned | Revenue potential: $${totalRevenue.toLocaleString()} | Investment: $${totalInvestment.toLocaleString()} | ROI ratio: ${totalInvestment > 0 ? (totalRevenue / totalInvestment).toFixed(1) : 0}x`,
  }
}

function formatDerivativeWorksReport(input: DerivativeWorksInput, result: DerivativeWorksResult): string {
  const lines: string[] = []
  const ipName = input.original_ip?.name || 'IP'

  lines.push('## Derivative Works Strategy')
  lines.push('')
  lines.push(`**${ipName}** | Genre: ${input.original_ip?.genre || 'N/A'} | Target Audiences: ${input.original_ip?.audience || 'N/A'}`)
  lines.push('')
  lines.push(result.summary)
  lines.push('')

  lines.push('### Format Plans')
  lines.push('| # | Format | Priority | Cost | Revenue (Est.) | Timeline | Notes |')
  lines.push('|---|--------|----------|------|----------------|----------|-------|')
  let idx = 1
  for (const p of result.plans) {
    lines.push(`| ${idx} | ${p.format} | ${p.priority.toUpperCase()} | $${p.estimated_cost_usd.toLocaleString()} | $${p.estimated_revenue_usd.toLocaleString()} | ${p.timeline_months}mo | ${p.notes} |`)
    idx++
  }
  lines.push('')

  lines.push('### Development Roadmap')
  for (const step of result.roadmap) {
    lines.push(`- ${step}`)
  }
  lines.push('')

  lines.push('### ROI Analysis')
  lines.push(`- **Total Investment**: $${result.total_investment.toLocaleString()}`)
  lines.push(`- **Total Revenue Potential**: $${result.total_revenue_potential.toLocaleString()}`)
  lines.push(`- **Net Potential**: $${(result.total_revenue_potential - result.total_investment).toLocaleString()}`)
  lines.push('')

  lines.push(DISCLAIMER)
  return lines.join('\n')
}

// ==================== TOOL 3: CROSS-MEDIA ADAPTATION PLANNER ====================

interface CrossMediaInput {
  source_ip: { title: string; medium: string }
  target_media: string[]
  audience_analysis: { primary_age: string; platforms: string[] }
  production_budget_usd: number
  risk_tolerance: 'low' | 'medium' | 'high'
}

interface AdaptationStep {
  from_medium: string
  to_medium: string
  difficulty: 'straightforward' | 'moderate' | 'complex' | 'very_complex'
  estimated_cost_usd: number
  estimated_timeline_months: number
  key_challenges: string[]
  opportunities: string[]
}

interface CrossMediaResult {
  adaptation_path: AdaptationStep[]
  total_cost: number
  total_timeline: number
  risk_assessment: string
  summary: string
}

function planCrossMediaAdaptation(input: CrossMediaInput): CrossMediaResult {
  const rng = initRng(input)
  const targets = input.target_media.length > 0 ? input.target_media : ['animation', 'game']
  const budget = input.production_budget_usd || 50000
  const source = input.source_ip?.medium || 'novel'
  const risk = input.risk_tolerance || 'medium'
  const ipTitle = input.source_ip?.title || 'IP'

  const adaptationMatrix: Record<string, { difficulty: AdaptationStep['difficulty']; costMult: [number, number]; timeRange: [number, number] }> = {
    'novel_to_animation': { difficulty: 'complex', costMult: [10000, 100000], timeRange: [6, 24] },
    'novel_to_game': { difficulty: 'complex', costMult: [5000, 80000], timeRange: [4, 18] },
    'novel_to_film': { difficulty: 'very_complex', costMult: [50000, 5000000], timeRange: [12, 36] },
    'novel_to_comic': { difficulty: 'moderate', costMult: [2000, 30000], timeRange: [3, 12] },
    'game_to_animation': { difficulty: 'complex', costMult: [20000, 300000], timeRange: [6, 18] },
    'game_to_film': { difficulty: 'very_complex', costMult: [50000, 5000000], timeRange: [12, 36] },
    'game_to_novel': { difficulty: 'straightforward', costMult: [1000, 15000], timeRange: [3, 8] },
    'game_to_comic': { difficulty: 'moderate', costMult: [2000, 25000], timeRange: [3, 10] },
    'animation_to_game': { difficulty: 'complex', costMult: [5000, 100000], timeRange: [4, 18] },
    'animation_to_novel': { difficulty: 'straightforward', costMult: [1000, 12000], timeRange: [3, 8] },
    'animation_to_film': { difficulty: 'very_complex', costMult: [50000, 5000000], timeRange: [12, 36] },
    'comic_to_animation': { difficulty: 'moderate', costMult: [10000, 200000], timeRange: [6, 18] },
    'comic_to_game': { difficulty: 'complex', costMult: [5000, 80000], timeRange: [4, 16] },
    'comic_to_film': { difficulty: 'very_complex', costMult: [50000, 5000000], timeRange: [12, 36] },
    'animation_to_comic': { difficulty: 'moderate', costMult: [2000, 20000], timeRange: [3, 10] },
    'game_to_merchandise': { difficulty: 'straightforward', costMult: [1000, 20000], timeRange: [2, 6] },
    'novel_to_merchandise': { difficulty: 'straightforward', costMult: [500, 15000], timeRange: [2, 5] },
    'animation_to_merchandise': { difficulty: 'straightforward', costMult: [1000, 25000], timeRange: [2, 6] },
  }

  const adaptationPath: AdaptationStep[] = []

  for (const target of targets) {
    const key = `${source}_to_${target}`
    const matrix = adaptationMatrix[key] || {
      difficulty: 'moderate' as AdaptationStep['difficulty'],
      costMult: [2000, 30000] as [number, number],
      timeRange: [3, 12] as [number, number],
    }

    const costCostMult: [number, number] = matrix.costMult
    const cost = rngRange(rng, costCostMult[0], costCostMult[1])
    const time = rngRange(rng, matrix.timeRange[0], matrix.timeRange[1])

    const challenges: string[] = []
    const opportunities: string[] = []

    if (matrix.difficulty === 'very_complex') {
      challenges.push('Requires significant creative reinterpretation')
      challenges.push('High production values expected by audience')
      opportunities.push('Blockbuster potential if executed well')
      opportunities.push('Opens premium licensing opportunities')
    } else if (matrix.difficulty === 'complex') {
      challenges.push('Medium-specific narrative techniques required')
      challenges.push('Fan expectations create quality bar pressure')
      opportunities.push('Strong audience crossover potential')
      opportunities.push('Can leverage existing fanbase for launch')
    } else if (matrix.difficulty === 'moderate') {
      challenges.push('Some creative adaptation needed')
      opportunities.push('Lower barrier to entry, faster time-to-market')
      opportunities.push('Can test market response before larger investments')
    } else {
      challenges.push('Relatively direct adaptation path')
      opportunities.push('Quickest path to revenue')
      opportunities.push('Low investment, minimal risk experiment')
    }

    if (target === 'game') {
      opportunities.push('Games offer ongoing revenue via DLC, in-app purchases')
      challenges.push('Game design requires separate skill set from original medium')
    }
    if (target === 'animation') {
      opportunities.push('Animation has strong streaming platform demand')
      challenges.push('Production quality expectations are high for animation')
    }
    if (target === 'merchandise') {
      opportunities.push('Merchandise: low margin but high fan engagement')
    }

    adaptationPath.push({
      from_medium: source,
      to_medium: target,
      difficulty: matrix.difficulty,
      estimated_cost_usd: cost,
      estimated_timeline_months: time,
      key_challenges: challenges,
      opportunities,
    })
  }

  const totalCost = adaptationPath.reduce((s, a) => s + a.estimated_cost_usd, 0)
  const totalTimeline = Math.max(...adaptationPath.map(a => a.estimated_timeline_months))

  let riskAssessment = 'Manageable'
  if (totalCost > budget * 2) riskAssessment = 'High risk — significant budget overrun likely'
  else if (totalCost > budget) riskAssessment = 'Elevated risk — budget stretched'
  else if (adaptationPath.some(a => a.difficulty === 'very_complex')) riskAssessment = 'Moderate risk — complex adaptations require careful planning'

  return {
    adaptation_path: adaptationPath,
    total_cost: totalCost,
    total_timeline: totalTimeline,
    risk_assessment: riskAssessment,
    summary: `${ipTitle} (${source}) | ${adaptationPath.length} target media | Total cost: $${totalCost.toLocaleString()} | Timeline: ${totalTimeline} months | Risk: ${riskAssessment}`,
  }
}

function formatCrossMediaReport(input: CrossMediaInput, result: CrossMediaResult): string {
  const lines: string[] = []
  const ipTitle = input.source_ip?.title || 'IP'

  lines.push('## Cross-Media Adaptation Plan')
  lines.push('')
  lines.push(`**${ipTitle}** | Source: ${input.source_ip?.medium || 'N/A'} | Budget: $${(input.production_budget_usd || 0).toLocaleString()} | Risk Tolerance: ${input.risk_tolerance || 'medium'}`)
  lines.push('')
  lines.push(result.summary)
  lines.push('')

  lines.push('### Adaptation Path')
  for (const step of result.adaptation_path) {
    lines.push(`#### ${step.from_medium} → ${step.to_medium}`)
    lines.push(`- **Difficulty**: ${step.difficulty}`)
    lines.push(`- **Estimated Cost**: $${step.estimated_cost_usd.toLocaleString()}`)
    lines.push(`- **Timeline**: ${step.estimated_timeline_months} months`)
    lines.push(`- **Key Challenges**: ${step.key_challenges.join('; ')}`)
    lines.push(`- **Opportunities**: ${step.opportunities.join('; ')}`)
    lines.push('')
  }

  lines.push('### Budget & Timeline Summary')
  lines.push(`- **Total Estimated Cost**: $${result.total_cost.toLocaleString()}`)
  lines.push(`- **Available Budget**: $${(input.production_budget_usd || 0).toLocaleString()}`)
  lines.push(`- **Max Timeline**: ${result.total_timeline} months`)
  lines.push(`- **Risk Assessment**: ${result.risk_assessment}`)
  lines.push('')

  lines.push('### Audience Insight')
  lines.push(`- **Primary Age Group**: ${input.audience_analysis?.primary_age || 'N/A'}`)
  lines.push(`- **Platforms**: ${(input.audience_analysis?.platforms || []).join(', ')}`)
  lines.push('')

  lines.push(DISCLAIMER)
  return lines.join('\n')
}

// ==================== TOOL 4: IP VALUATION CREATIVE ====================

interface IPValuationInput {
  ip_name: string
  audience_size: number
  engagement_rate: number
  revenue_streams: { source: string; monthly_usd: number }[]
  comparable_deals: { deal_name: string; value_usd: number }[]
  growth_trajectory: 'declining' | 'stable' | 'growing' | 'viral'
}

interface IPValuationResult {
  estimated_value_usd: number
  value_range_low: number
  value_range_high: number
  valuation_method: string
  revenue_multiplier: number
  comparable_analysis: string[]
  growth_adjustment: string
  summary: string
}

function valueCreativeIP(input: IPValuationInput): IPValuationResult {
  const rng = initRng(input)
  const audience = input.audience_size || 10000
  const engagement = input.engagement_rate || 3.0
  const streams = input.revenue_streams || []
  const trajectory = input.growth_trajectory || 'stable'
  const ipName = input.ip_name || 'IP'

  // Base revenue calculation
  const monthlyRevenue = streams.reduce((s, r) => s + r.monthly_usd, 0)
  const annualRevenue = monthlyRevenue * 12

  // Revenue multiplier based on growth trajectory
  let multiplier = 2.0
  if (trajectory === 'viral') multiplier = rngRange(rng, 4, 8)
  else if (trajectory === 'growing') multiplier = rngRange(rng, 3, 5)
  else if (trajectory === 'stable') multiplier = rngRange(rng, 2, 3)
  else if (trajectory === 'declining') multiplier = rngRange(rng, 1, 2)
  multiplier = parseFloat(multiplier.toFixed(1))

  // Engagement quality adjustment
  const engagementMultiplier = engagement > 8 ? 1.5 : engagement > 5 ? 1.2 : engagement > 3 ? 1.0 : 0.8

  // Audience-driven value component
  const audienceValue = audience * engagement * 0.5

  // Estimated value
  const baseValue = annualRevenue > 0 ? annualRevenue * multiplier : audienceValue
  const adjustedValue = Math.round(baseValue * engagementMultiplier)

  const lowRange = Math.round(adjustedValue * 0.6)
  const highRange = Math.round(adjustedValue * 1.8)

  // Comparable analysis
  const comparables = input.comparable_deals || []
  const compAnalysis: string[] = []
  if (comparables.length > 0) {
    const avgCompValue = comparables.reduce((s, d) => s + d.value_usd, 0) / comparables.length
    const compRatio = adjustedValue / avgCompValue
    compAnalysis.push(`Average comparable deal value: $${Math.round(avgCompValue).toLocaleString()}`)
    compAnalysis.push(`Your IP vs comps: ${compRatio > 1.2 ? 'premium' : compRatio < 0.8 ? 'discount' : 'aligned'} (${compRatio.toFixed(2)}x)`)
    for (const c of comparables.slice(0, 3)) {
      compAnalysis.push(`- ${c.deal_name}: $${c.value_usd.toLocaleString()}`)
    }
  } else {
    compAnalysis.push('No comparable deals provided — valuation based on revenue metrics and audience analysis')
  }

  let method = 'Revenue Multiple'
  if (annualRevenue === 0) method = 'Audience & Engagement-Based (no revenue data)'
  else if (comparables.length >= 3) method = 'Blended (Revenue + Comparable Deals)'

  const growthAdj = trajectory === 'viral' ? 'Significant premium for viral trajectory — high growth potential justifies elevated multiple' :
    trajectory === 'growing' ? 'Positive growth trajectory supports above-market multiple' :
    trajectory === 'stable' ? 'Stable trajectory — standard market multiples apply' :
    'Declining trajectory requires value protection focus — consider strategic pivots'

  return {
    estimated_value_usd: adjustedValue,
    value_range_low: lowRange,
    value_range_high: highRange,
    valuation_method: method,
    revenue_multiplier: multiplier,
    comparable_analysis: compAnalysis,
    growth_adjustment: growthAdj,
    summary: `${ipName} | Estimated value: $${adjustedValue.toLocaleString()} (range: $${lowRange.toLocaleString()} - $${highRange.toLocaleString()}) | Multiplier: ${multiplier}x | Growth: ${trajectory}`,
  }
}

function formatIPValuationReport(input: IPValuationInput, result: IPValuationResult): string {
  const lines: string[] = []

  lines.push('## Creative IP Valuation Report')
  lines.push('')
  lines.push(`**${input.ip_name || 'IP'}** | Audience: ${(input.audience_size || 0).toLocaleString()} | Engagement: ${input.engagement_rate || 0}% | Growth: ${input.growth_trajectory || 'stable'}`)
  lines.push('')
  lines.push(result.summary)
  lines.push('')

  lines.push('### Valuation')
  lines.push(`| Metric | Value |`)
  lines.push(`|--------|-------|`)
  lines.push(`| **Estimated Value** | $${result.estimated_value_usd.toLocaleString()} |`)
  lines.push(`| **Range (Low)** | $${result.value_range_low.toLocaleString()} |`)
  lines.push(`| **Range (High)** | $${result.value_range_high.toLocaleString()} |`)
  lines.push(`| **Method** | ${result.valuation_method} |`)
  lines.push(`| **Revenue Multiplier** | ${result.revenue_multiplier}x |`)
  lines.push('')

  lines.push('### Growth Trajectory Adjustment')
  lines.push(result.growth_adjustment)
  lines.push('')

  lines.push('### Comparable Deal Analysis')
  for (const item of result.comparable_analysis) {
    lines.push(`- ${item}`)
  }
  lines.push('')

  lines.push('### Revenue Streams')
  if (input.revenue_streams && input.revenue_streams.length > 0) {
    lines.push('| Source | Monthly | Annual |')
    lines.push('|--------|---------|--------|')
    for (const r of input.revenue_streams) {
      lines.push(`| ${r.source} | $${r.monthly_usd.toLocaleString()} | $${(r.monthly_usd * 12).toLocaleString()} |`)
    }
  } else {
    lines.push('No revenue streams specified — valuation based on audience metrics.')
  }
  lines.push('')

  lines.push(DISCLAIMER)
  return lines.join('\n')
}

// ==================== TOOL 5: ANTI-PIRACY MONITOR DESIGNER ====================

interface AntiPiracyInput {
  content_type: string
  distribution_channels: string[]
  monitoring_budget_usd: number
  takedown_speed_requirement: 'standard' | 'fast' | 'immediate'
  jurisdiction: string[]
}

interface MonitoringLayer {
  layer: string
  technique: string
  coverage_pct: number
  cost_usd: number
  response_time: string
  effectiveness: 'high' | 'medium' | 'low'
}

interface AntiPiracyResult {
  monitoring_layers: MonitoringLayer[]
  total_coverage: number
  total_cost: number
  takedown_avg_hours: number
  prevention_tips: string[]
  summary: string
}

function designAntiPiracyMonitoring(input: AntiPiracyInput): AntiPiracyResult {
  const rng = initRng(input)
  const channels = input.distribution_channels.length > 0 ? input.distribution_channels : ['web', 'social_media', 'torrent']
  const budget = input.monitoring_budget_usd || 2000
  const speed = input.takedown_speed_requirement || 'standard'
  const contentType = input.content_type || 'digital_art'
  const jurisdictions = input.jurisdiction.length > 0 ? input.jurisdiction : ['US']

  const layers: MonitoringLayer[] = []

  // Web monitoring
  if (channels.includes('web') || channels.includes('website')) {
    layers.push({
      layer: 'Web Crawling & Detection',
      technique: 'Automated scraping + perceptual fingerprinting to detect unauthorized copies',
      coverage_pct: rngRange(rng, 60, 80),
      cost_usd: rngRange(rng, 500, 3000),
      response_time: speed === 'immediate' ? '2-6 hours' : speed === 'fast' ? '12-24 hours' : '24-72 hours',
      effectiveness: 'high',
    })
  }

  // Social media monitoring
  if (channels.includes('social_media') || channels.includes('platforms')) {
    layers.push({
      layer: 'Social Media Monitoring',
      technique: 'Platform API monitoring + image recognition for unauthorized reposts and edits',
      coverage_pct: rngRange(rng, 50, 75),
      cost_usd: rngRange(rng, 300, 2000),
      response_time: speed === 'immediate' ? '4-12 hours' : '24-48 hours',
      effectiveness: 'medium',
    })
  }

  // Torrent / P2P monitoring
  if (channels.includes('torrent') || channels.includes('p2p') || channels.includes('file_sharing')) {
    layers.push({
      layer: 'P2P/Torrent Monitoring',
      technique: 'Tracker monitoring + DHT scanning + swarm analysis for leaked content',
      coverage_pct: rngRange(rng, 40, 65),
      cost_usd: rngRange(rng, 500, 2500),
      response_time: speed === 'immediate' ? '6-12 hours' : '24-72 hours',
      effectiveness: 'medium',
    })
  }

  // Marketplace monitoring (prints, merch)
  if (channels.includes('marketplace') || channels.includes('prints') || channels.includes('merchandise')) {
    layers.push({
      layer: 'Marketplace Monitoring',
      technique: 'Automated product image matching on Etsy, Redbubble, Taobao, Amazon Merch',
      coverage_pct: rngRange(rng, 55, 70),
      cost_usd: rngRange(rng, 400, 2000),
      response_time: '24-72 hours',
      effectiveness: 'medium',
    })
  }

  // Watermarking / fingerprinting (preventive)
  layers.push({
    layer: 'Digital Watermarking',
    technique: 'Invisible forensic watermarking embedded in original files for leak source tracing',
    coverage_pct: rngRange(rng, 80, 95),
    cost_usd: rngRange(rng, 200, 1500),
    response_time: 'N/A (preventive)',
    effectiveness: 'high',
  })

  // Fallback if no channels matched
  if (layers.length === 0) {
    layers.push({
      layer: 'Basic Web Monitoring',
      technique: 'Automated reverse image search and keyword monitoring',
      coverage_pct: rngRange(rng, 40, 60),
      cost_usd: rngRange(rng, 200, 1000),
      response_time: '48-72 hours',
      effectiveness: 'medium',
    })
  }

  const totalCoverage = Math.min(95, Math.round(layers.reduce((s, l) => s + l.coverage_pct, 0) / layers.length + rngRange(rng, 5, 15)))
  const totalCost = layers.reduce((s, l) => s + l.cost_usd, 0)

  const avgHours = speed === 'immediate' ? rngRange(rng, 4, 12) : speed === 'fast' ? rngRange(rng, 12, 36) : rngRange(rng, 24, 72)

  const preventionTips: string[] = [
    'Register copyright in all target jurisdictions before content launch — enables statutory damages',
    'Use visible watermarks on preview/low-res versions; invisible forensic watermarks on full-res',
    'Implement DMCA-compliant takedown process with pre-prepared templates for each platform',
    'Monitor newly registered domain names containing your IP names — early indicator of piracy ecosystems',
    'Release content strategically: staggered regional releases reduce mass piracy incentives',
    'Build fan community — loyal fans actively report piracy and support official channels',
    'Consider blockchain/NFT provenance for high-value digital artworks',
    'Partner with anti-piracy service providers (Mintz, MarkMonitor, Red Points) for enterprise-grade monitoring',
  ]

  return {
    monitoring_layers: layers,
    total_coverage: totalCoverage,
    total_cost: totalCost,
    takedown_avg_hours: avgHours,
    prevention_tips: preventionTips,
    summary: `${contentType} | ${layers.length} monitoring layers | ${totalCoverage}% coverage | $${totalCost.toLocaleString()} cost | Avg takedown: ${avgHours}h | ${jurisdictions.length} jurisdiction(s)`,
  }
}

function formatAntiPiracyReport(input: AntiPiracyInput, result: AntiPiracyResult): string {
  const lines: string[] = []

  lines.push('## Anti-Piracy Monitoring Design')
  lines.push('')
  lines.push(`**${input.content_type || 'Content'}** | Channels: ${(input.distribution_channels || []).join(', ') || 'N/A'} | Speed: ${input.takedown_speed_requirement || 'standard'} | Budget: $${(input.monitoring_budget_usd || 0).toLocaleString()}`)
  lines.push('')
  lines.push(result.summary)
  lines.push('')

  lines.push('### Monitoring Layers')
  lines.push('| # | Layer | Coverage | Cost | Response | Effectiveness |')
  lines.push('|---|-------|----------|------|----------|---------------|')
  let idx = 1
  for (const layer of result.monitoring_layers) {
    lines.push(`| ${idx} | ${layer.layer} | ${layer.coverage_pct}% | $${layer.cost_usd.toLocaleString()} | ${layer.response_time} | ${layer.effectiveness.toUpperCase()} |`)
    idx++
  }
  lines.push('')

  lines.push('### Layer Details')
  for (const layer of result.monitoring_layers) {
    lines.push(`#### ${layer.layer}`)
    lines.push(`- **Technique**: ${layer.technique}`)
    lines.push(`- **Effectiveness**: ${layer.effectiveness}`)
    lines.push('')
  }

  lines.push('### Key Metrics')
  lines.push(`- **Total Coverage**: ${result.total_coverage}%`)
  lines.push(`- **Total Budget Required**: $${result.total_cost.toLocaleString()}`)
  lines.push(`- **Available Budget**: $${(input.monitoring_budget_usd || 0).toLocaleString()}`)
  lines.push(`- **Average Takedown Time**: ${result.takedown_avg_hours} hours`)
  lines.push('')

  lines.push('### Prevention Tips')
  for (const tip of result.prevention_tips) {
    lines.push(`- ${tip}`)
  }
  lines.push('')

  lines.push(DISCLAIMER)
  return lines.join('\n')
}

// ==================== TOOL 6: LICENSING DEAL STRUCTURER ====================

interface LicensingInput {
  ip_assets: { asset_name: string; asset_type: string }[]
  licensee_profile: { company: string; size: string; territory: string }
  deal_type: 'exclusive' | 'non_exclusive' | 'sole'
  minimum_guarantee_usd: number
  royalty_rate_range: { min_pct: number; max_pct: number }
}

interface LicensingDealResult {
  deal_terms: {
    territory: string
    duration_years: number
    exclusivity: string
    minimum_guarantee: number
    royalty_rate: string
    advance_usd: number
  }
  milestones: { milestone: string; payment_usd: number; deadline: string }[]
  risk_factors: string[]
  recommendations: string[]
  summary: string
}

function structureLicensingDeal(input: LicensingInput): LicensingDealResult {
  const rng = initRng(input)
  const mg = input.minimum_guarantee_usd || 10000
  const dealType = input.deal_type || 'non_exclusive'
  const territory = input.licensee_profile?.territory || 'Global'
  const company = input.licensee_profile?.company || 'Licensee'
  const assets = input.ip_assets || []

  // Advance calculation
  const advanceMultiplier = dealType === 'exclusive' ? rngRange(rng, 10, 25) / 10 : rngRange(rng, 3, 8) / 10
  const advance = Math.round(mg * advanceMultiplier)

  // Duration
  const duration = dealType === 'exclusive' ? rngRange(rng, 3, 7) : rngRange(rng, 1, 3)

  // Royalty range
  const rateMin = input.royalty_rate_range?.min_pct || 5
  const rateMax = input.royalty_rate_range?.max_pct || 15
  const baseRate = rngRange(rng, rateMin, rateMax)

  // Milestones
  const milestones: LicensingDealResult['milestones'] = [
    {
      milestone: 'Signing / Advance Payment',
      payment_usd: advance,
      deadline: 'At contract execution',
    },
    {
      milestone: 'First Commercial Release',
      payment_usd: Math.round(mg * 0.25),
      deadline: `Within ${rngRange(rng, 6, 18)} months of signing`,
    },
    {
      milestone: 'Minimum Guarantee Achievement',
      payment_usd: mg,
      deadline: `${duration} years from signing`,
    },
    {
      milestone: 'Sales Target Bonus (if applicable)',
      payment_usd: Math.round(mg * 0.3),
      deadline: `Year ${Math.ceil(duration / 2)} of contract`,
    },
  ]

  const risks: string[] = []
  if (dealType === 'exclusive' && duration > 3) risks.push('Long exclusive deal may limit future licensing opportunities')
  if (mg < 5000) risks.push('Low minimum guarantee may not incentivize licensee commitment')
  if (assets.length > 5) risks.push('Licensing many assets in one deal increases compliance monitoring complexity')
  risks.push('Currency fluctuation risk if deal spans multi-year term across territories')
  risks.push('Licensee may not fully exploit the IP — include performance clauses with reversal rights')

  const recommendations: string[] = []
  recommendations.push(`Structure royalty at ${baseRate}% of net revenue (standard for ${assets[0]?.asset_type || 'creative content'})`)
  if (dealType === 'exclusive') {
    recommendations.push('Exclusive deal: require minimum annual performance or territory reverts to licensor')
    recommendations.push('Include quarterly reporting and audit rights to verify royalty calculations')
  }
  recommendations.push('Define "Net Revenue" explicitly in contract — exclude only documented platform fees and returns')
  recommendations.push('Include clause for sublicensing approval to prevent unauthorized third-party licensing')
  recommendations.push('Add IP protection clause: licensee must maintain quality standards and brand guidelines')
  recommendations.push('Consider escalation clause: royalty rate increases after revenue milestones')
  if (duration > 3) recommendations.push('Long-term deal: include termination option at year 2-3 with buy-back clause')

  return {
    deal_terms: {
      territory,
      duration_years: duration,
      exclusivity: dealType,
      minimum_guarantee: mg,
      royalty_rate: `${rateMin}%-${rateMax}% (recommended: ${baseRate}%)`,
      advance_usd: advance,
    },
    milestones,
    risk_factors: risks,
    recommendations,
    summary: `${company} | ${dealType} license | ${territory} | ${duration}yr term | MG: $${mg.toLocaleString()} | Advance: $${advance.toLocaleString()} | Royalty: ${rateMin}%-${rateMax}%`,
  }
}

function formatLicensingDealReport(input: LicensingInput, result: LicensingDealResult): string {
  const lines: string[] = []
  const company = input.licensee_profile?.company || 'Licensee'

  lines.push('## Licensing Deal Structure')
  lines.push('')
  lines.push(`**${company}** | Deal Type: ${input.deal_type || 'non_exclusive'} | Territory: ${input.licensee_profile?.territory || 'Global'}`)
  lines.push('')
  lines.push(result.summary)
  lines.push('')

  lines.push('### Deal Terms')
  lines.push(`| Term | Value |`)
  lines.push(`|------|-------|`)
  lines.push(`| **Territory** | ${result.deal_terms.territory} |`)
  lines.push(`| **Duration** | ${result.deal_terms.duration_years} years |`)
  lines.push(`| **Exclusivity** | ${result.deal_terms.exclusivity} |`)
  lines.push(`| **Minimum Guarantee** | $${result.deal_terms.minimum_guarantee.toLocaleString()} |`)
  lines.push(`| **Royalty Rate** | ${result.deal_terms.royalty_rate} |`)
  lines.push(`| **Advance** | $${result.deal_terms.advance_usd.toLocaleString()} |`)
  lines.push('')

  lines.push('### Payment Milestones')
  lines.push('| # | Milestone | Payment | Deadline |')
  lines.push('|---|-----------|---------|----------|')
  let idx = 1
  for (const m of result.milestones) {
    lines.push(`| ${idx} | ${m.milestone} | $${m.payment_usd.toLocaleString()} | ${m.deadline} |`)
    idx++
  }
  lines.push('')

  lines.push('### Risk Factors')
  for (const risk of result.risk_factors) {
    lines.push(`- ${risk}`)
  }
  lines.push('')

  lines.push('### Recommendations')
  for (const rec of result.recommendations) {
    lines.push(`- ${rec}`)
  }
  lines.push('')

  lines.push('### Licensed Assets')
  if (input.ip_assets && input.ip_assets.length > 0) {
    for (const asset of input.ip_assets) {
      lines.push(`- **${asset.asset_name}** (${asset.asset_type})`)
    }
  } else {
    lines.push('No specific assets listed — define asset scope before finalizing deal.')
  }
  lines.push('')

  lines.push(DISCLAIMER)
  return lines.join('\n')
}

// ==================== TOOL 7: CREATOR BRAND BUILDER ====================

interface CreatorBrandInput {
  creator_profile: { name: string; expertise: string; years_experience: number }
  content_niche: string
  target_audience: { age_range: string; interests: string[] }
  platform_mix: string[]
  monetization_goals: string[]
}

interface BrandStrategyResult {
  brand_positioning: string
  content_pillars: { pillar: string; frequency: string; format: string }[]
  platform_strategy: { platform: string; role: string; posting_frequency: string }[]
  monetization_roadmap: { phase: string; actions: string[]; timeline: string }[]
  community_tips: string[]
  summary: string
}

function buildCreatorBrand(input: CreatorBrandInput): BrandStrategyResult {
  const rng = initRng(input)
  const creatorName = input.creator_profile?.name || 'Creator'
  const niche = input.content_niche || 'creative'
  const platforms = input.platform_mix.length > 0 ? input.platform_mix : ['youtube', 'instagram', 'twitter']
  const goals = input.monetization_goals.length > 0 ? input.monetization_goals : ['sponsorships', 'merchandise']

  // Brand positioning
  const positioningOptions = [
    `${creatorName} — The ${niche} Authority: Deep expertise meets accessible storytelling`,
    `${creatorName} — The ${niche} Innovator: Pushing boundaries in ${niche} creation`,
    `${creatorName} — The ${niche} Educator: Making ${niche} accessible to everyone`,
    `${creatorName} — The ${niche} Storyteller: Narrative-driven ${niche} content`,
  ]
  const positioning = positioningOptions[rngRange(rng, 0, positioningOptions.length - 1)]

  // Content pillars
  const pillarPool = [
    { pillar: 'Behind the Scenes', frequency: '2x/week', format: 'Short-form video / Stories' },
    { pillar: 'Tutorials & How-To', frequency: '1x/week', format: 'Long-form video / Blog' },
    { pillar: 'Industry Commentary', frequency: '2x/week', format: 'Twitter threads / Short video' },
    { pillar: 'Project Showcases', frequency: '1x/week', format: 'High-production video / Carousel' },
    { pillar: 'Community Engagement', frequency: '3x/week', format: 'Q&A / Pols / Live streams' },
    { pillar: 'Collaborations', frequency: '1x/month', format: 'Joint content with other creators' },
    { pillar: 'Personal Journey', frequency: '1x/week', format: 'Vlog / Diary format' },
  ]
  const contentPillars = pickItems(rng, pillarPool.map(p => JSON.stringify(p)), rngRange(rng, 3, 5)).map(s => JSON.parse(s))

  // Platform strategy
  const platformRoles: Record<string, { role: string; freq: string }> = {
    youtube: { role: 'Primary content hub — long-form, evergreen', freq: '2-3 videos/week' },
    instagram: { role: 'Visual showcase + community', freq: '1 post/day + stories' },
    twitter: { role: 'Thought leadership + networking', freq: '3-5 tweets/day' },
    tiktok: { role: 'Discovery + viral reach', freq: '1-2 videos/day' },
    bilibili: { role: 'Chinese market + long-form content', freq: '2-3 videos/week' },
    patreon: { role: 'Premium community + exclusive content', freq: '4-8 posts/month' },
    discord: { role: 'Community hub + direct fan interaction', freq: 'Daily engagement' },
    newsletter: { role: 'Direct relationship + deep dives', freq: '1-2 emails/week' },
    twitch: { role: 'Live creation + real-time community', freq: '3-5 streams/week' },
  }

  const platformStrategy = platforms.map(p => {
    const info = platformRoles[p] || { role: 'Content distribution', freq: '3-5 posts/week' }
    return { platform: p, role: info.role, posting_frequency: info.freq }
  })

  // Monetization roadmap
  const monetizationRoadmap: BrandStrategyResult['monetization_roadmap'] = []

  if (goals.includes('sponsorships')) {
    monetizationRoadmap.push({
      phase: 'Phase 1: Sponsorship Readiness',
      actions: [
        'Build media kit with audience demographics and engagement metrics',
        'Reach out to 10-20 brands aligned with your niche',
        'Create sponsored content portfolio (even unpaid initially)',
        'Set rates: $500-2,000 per sponsored post (based on audience size)',
      ],
      timeline: 'Months 1-3',
    })
  }

  if (goals.includes('merchandise')) {
    monetizationRoadmap.push({
      phase: 'Phase 2: Merchandise Launch',
      actions: [
        'Design 3-5 signature products (apparel, prints, accessories)',
        'Use print-on-demand (Printful, Printify) to minimize inventory risk',
        'Launch limited drops to create urgency',
        'Integrate with Shopify or Gumroad for direct sales',
      ],
      timeline: 'Months 3-6',
    })
  }

  if (goals.includes('digital_products')) {
    monetizationRoadmap.push({
      phase: 'Phase 3: Digital Products',
      actions: [
        'Create templates, presets, or tools related to your niche',
        'Develop a mini-course or tutorial series',
        'Sell via Gumroad, LemonSqueezy, or your own site',
        'Price: $10-50 for templates, $50-200 for courses',
      ],
      timeline: 'Months 4-8',
    })
  }

  if (goals.includes('community')) {
    monetizationRoadmap.push({
      phase: 'Phase 4: Community & Membership',
      actions: [
        'Launch Patreon or Discord membership tier',
        'Offer exclusive content, early access, and direct interaction',
        'Price: $5-20/month for membership',
        'Target: 100 members = $500-2,000/month recurring',
      ],
      timeline: 'Months 6-12',
    })
  }

  if (monetizationRoadmap.length === 0) {
    monetizationRoadmap.push({
      phase: 'Phase 1: Foundation',
      actions: ['Define your unique value proposition', 'Build consistent content output', 'Grow audience to 1,000+ engaged followers'],
      timeline: 'Months 1-3',
    })
  }

  const communityTips: string[] = [
    'Reply to every comment in first 30 minutes after posting — algorithm boost + community building',
    'Create a recurring series (weekly show, monthly challenge) to build habit and anticipation',
    'Cross-pollinate audiences: mention your other platforms in every piece of content',
    'Collaborate with creators at your level — mutual growth beats solo grinding',
    'Share your process, not just results — authenticity builds deeper connection',
    'Use analytics to double down on what works; kill what does not after 5+ attempts',
    'Build email list from day 1 — platform algorithms change, email is forever',
    'Host monthly community events (livestream Q&A, challenges, AMAs)',
  ]

  return {
    brand_positioning: positioning,
    content_pillars: contentPillars,
    platform_strategy: platformStrategy,
    monetization_roadmap: monetizationRoadmap,
    community_tips: communityTips,
    summary: `${creatorName} | Niche: ${niche} | ${platforms.length} platforms | ${contentPillars.length} content pillars | ${monetizationRoadmap.length} monetization phases`,
  }
}

function formatCreatorBrandReport(input: CreatorBrandInput, result: BrandStrategyResult): string {
  const lines: string[] = []
  const creatorName = input.creator_profile?.name || 'Creator'

  lines.push('## Creator Brand Strategy')
  lines.push('')
  lines.push(`**${creatorName}** | Niche: ${input.content_niche || 'N/A'} | Expertise: ${input.creator_profile?.expertise || 'N/A'} | ${input.creator_profile?.years_experience || 0}+ years`)
  lines.push('')
  lines.push(result.summary)
  lines.push('')

  lines.push('### Brand Positioning')
  lines.push(result.brand_positioning)
  lines.push('')

  lines.push('### Content Pillars')
  lines.push('| # | Pillar | Frequency | Format |')
  lines.push('|---|--------|-----------|--------|')
  let idx = 1
  for (const p of result.content_pillars) {
    lines.push(`| ${idx} | ${p.pillar} | ${p.frequency} | ${p.format} |`)
    idx++
  }
  lines.push('')

  lines.push('### Platform Strategy')
  lines.push('| Platform | Role | Posting Frequency |')
  lines.push('|----------|------|-------------------|')
  for (const ps of result.platform_strategy) {
    lines.push(`| ${ps.platform} | ${ps.role} | ${ps.posting_frequency} |`)
  }
  lines.push('')

  lines.push('### Monetization Roadmap')
  for (const phase of result.monetization_roadmap) {
    lines.push(`#### ${phase.phase} (${phase.timeline})`)
    for (const action of phase.actions) {
      lines.push(`- ${action}`)
    }
    lines.push('')
  }

  lines.push('### Community Building Tips')
  for (const tip of result.community_tips) {
    lines.push(`- ${tip}`)
  }
  lines.push('')

  lines.push('### Target Audience')
  lines.push(`- **Age Range**: ${input.target_audience?.age_range || 'N/A'}`)
  lines.push(`- **Interests**: ${(input.target_audience?.interests || []).join(', ')}`)
  lines.push('')

  lines.push(DISCLAIMER)
  return lines.join('\n')
}

// ==================== TOOL 8: IP PORTFOLIO DIVERSIFIER ====================

interface PortfolioDiversifierInput {
  current_portfolio: { ip_name: string; format: string; genre: string; revenue_usd: number }[]
  risk_tolerance: 'low' | 'medium' | 'high'
  investment_budget_usd: number
  market_trends: string[]
  time_horizon_years: number
}

interface DiversificationRecommendation {
  action: 'expand' | 'diversify' | 'consolidate' | 'exit'
  area: string
  rationale: string
  investment_usd: number
  expected_roi_pct: number
  timeline_months: number
  priority: 'critical' | 'high' | 'medium' | 'low'
}

interface PortfolioDiversifierResult {
  current_diversity_score: number
  target_diversity_score: number
  recommendations: DiversificationRecommendation[]
  risk_analysis: string
  summary: string
}

function diversifyIPPortfolio(input: PortfolioDiversifierInput): PortfolioDiversifierResult {
  const rng = initRng(input)
  const portfolio = input.current_portfolio || []
  const budget = input.investment_budget_usd || 50000
  const risk = input.risk_tolerance || 'medium'
  const horizon = input.time_horizon_years || 3
  const trends = input.market_trends || []

  // Calculate current diversity
  const formats = new Set(portfolio.map(p => p.format))
  const genres = new Set(portfolio.map(p => p.genre))
  const totalRevenue = portfolio.reduce((s, p) => s + p.revenue_usd, 0)

  const formatDiversity = Math.min(100, formats.size * 20)
  const genreDiversity = Math.min(100, genres.size * 25)
  const revenueConcentration = portfolio.length > 0 ? Math.max(0, 100 - (Math.max(...portfolio.map(p => p.revenue_usd)) / (totalRevenue || 1)) * 100) : 50
  const currentDiversity = Math.round((formatDiversity + genreDiversity + revenueConcentration) / 3)

  const targetDiversity = risk === 'high' ? rngRange(rng, 75, 90) : risk === 'medium' ? rngRange(rng, 60, 80) : rngRange(rng, 45, 65)

  // Generate recommendations
  const recommendations: DiversificationRecommendation[] = []

  // Format expansion
  if (formats.size < 3) {
    const missingFormats = ['animation', 'game', 'merchandise', 'literature', 'music'].filter(f => !formats.has(f))
    if (missingFormats.length > 0) {
      const targetFormat = missingFormats[rngRange(rng, 0, missingFormats.length - 1)]
      recommendations.push({
        action: 'diversify',
        area: `Expand into ${targetFormat}`,
        rationale: `Current portfolio only covers ${formats.size} format(s). ${targetFormat} represents a high-growth opportunity.`,
        investment_usd: Math.round(budget * (0.2 + rng() * 0.15)),
        expected_roi_pct: rngRange(rng, 15, 45),
        timeline_months: rngRange(rng, 6, 18),
        priority: 'high',
      })
    }
  }

  // Genre diversification
  if (genres.size < 3) {
    const missingGenres = ['sci-fi', 'fantasy', 'slice_of_life', 'horror', 'comedy', 'educational'].filter(g => !genres.has(g))
    if (missingGenres.length > 0) {
      const targetGenre = missingGenres[rngRange(rng, 0, missingGenres.length - 1)]
      recommendations.push({
        action: 'diversify',
        area: `Develop ${targetGenre} content`,
        rationale: `Genre diversification reduces audience concentration risk. ${targetGenre} is trending in current market.`,
        investment_usd: Math.round(budget * (0.15 + rng() * 0.1)),
        expected_roi_pct: rngRange(rng, 10, 35),
        timeline_months: rngRange(rng, 4, 12),
        priority: 'medium',
      })
    }
  }

  // Market expansion
  recommendations.push({
    action: 'expand',
    area: 'International market expansion',
    rationale: 'Geographic diversification reduces single-market dependency and opens new revenue streams.',
    investment_usd: Math.round(budget * (0.1 + rng() * 0.1)),
    expected_roi_pct: rngRange(rng, 12, 30),
    timeline_months: rngRange(rng, 6, 24),
    priority: risk === 'high' ? 'high' : 'medium',
  })

  // Trend-based recommendation
  if (trends.length > 0) {
    const topTrend = trends[0]
    recommendations.push({
      action: 'expand',
      area: `Capitalize on trend: ${topTrend}`,
      rationale: `Market trend "${topTrend}" aligns with portfolio capabilities. Early mover advantage available.`,
      investment_usd: Math.round(budget * (0.15 + rng() * 0.1)),
      expected_roi_pct: rngRange(rng, 20, 50),
      timeline_months: rngRange(rng, 3, 9),
      priority: 'high',
    })
  }

  // Consolidation (if portfolio is too fragmented)
  if (portfolio.length > 5 && risk === 'low') {
    recommendations.push({
      action: 'consolidate',
      area: 'Focus on top-performing IPs',
      rationale: 'Portfolio has many assets but resources are spread thin. Consolidate around 2-3 highest-potential IPs.',
      investment_usd: Math.round(budget * 0.1),
      expected_roi_pct: rngRange(rng, 15, 25),
      timeline_months: rngRange(rng, 3, 6),
      priority: 'medium',
    })
  }

  // Sort by priority
  const priorityOrder = { critical: 0, high: 1, medium: 2, low: 3 }
  recommendations.sort((a, b) => priorityOrder[a.priority] - priorityOrder[b.priority])

  // Risk analysis
  let riskAnalysis = ''
  if (risk === 'high') {
    riskAnalysis = 'High risk tolerance enables aggressive diversification. Accept short-term volatility for long-term portfolio growth.'
  } else if (risk === 'medium') {
    riskAnalysis = 'Balanced approach: diversify gradually while maintaining revenue from existing IPs. Monitor market signals quarterly.'
  } else {
    riskAnalysis = 'Conservative strategy: prioritize stability and incremental growth. Avoid speculative bets; focus on proven formats and genres.'
  }

  return {
    current_diversity_score: currentDiversity,
    target_diversity_score: targetDiversity,
    recommendations,
    risk_analysis: riskAnalysis,
    summary: `${portfolio.length} IP(s) in portfolio | Current diversity: ${currentDiversity}/100 | Target: ${targetDiversity}/100 | ${recommendations.length} recommendations | Budget: $${budget.toLocaleString()} | Horizon: ${horizon}yr`,
  }
}

function formatPortfolioDiversifierReport(input: PortfolioDiversifierInput, result: PortfolioDiversifierResult): string {
  const lines: string[] = []

  lines.push('## IP Portfolio Diversification Strategy')
  lines.push('')
  lines.push(`**Portfolio**: ${(input.current_portfolio || []).length} IP(s) | Risk Tolerance: ${input.risk_tolerance || 'medium'} | Budget: $${(input.investment_budget_usd || 0).toLocaleString()} | Horizon: ${input.time_horizon_years || 3} years`)
  lines.push('')
  lines.push(result.summary)
  lines.push('')

  lines.push('### Diversity Assessment')
  lines.push(`| Metric | Score |`)
  lines.push(`|--------|-------|`)
  lines.push(`| **Current Diversity** | ${result.current_diversity_score}/100 |`)
  lines.push(`| **Target Diversity** | ${result.target_diversity_score}/100 |`)
  lines.push(`| **Gap** | ${result.target_diversity_score - result.current_diversity_score} points |`)
  lines.push('')

  lines.push('### Current Portfolio')
  if (input.current_portfolio && input.current_portfolio.length > 0) {
    lines.push('| # | IP Name | Format | Genre | Revenue |')
    lines.push('|---|---------|--------|-------|---------|')
    let idx = 1
    for (const ip of input.current_portfolio) {
      lines.push(`| ${idx} | ${ip.ip_name} | ${ip.format} | ${ip.genre} | $${ip.revenue_usd.toLocaleString()} |`)
      idx++
    }
  } else {
    lines.push('No current portfolio items specified.')
  }
  lines.push('')

  lines.push('### Recommendations')
  lines.push('| # | Action | Area | Investment | Expected ROI | Timeline | Priority |')
  lines.push('|---|--------|------|------------|--------------|----------|----------|')
  let idx = 1
  for (const r of result.recommendations) {
    lines.push(`| ${idx} | ${r.action.toUpperCase()} | ${r.area} | $${r.investment_usd.toLocaleString()} | ${r.expected_roi_pct}% | ${r.timeline_months}mo | ${r.priority.toUpperCase()} |`)
    idx++
  }
  lines.push('')

  lines.push('### Recommendation Details')
  for (const r of result.recommendations) {
    lines.push(`#### ${r.area}`)
    lines.push(`- **Action**: ${r.action}`)
    lines.push(`- **Rationale**: ${r.rationale}`)
    lines.push(`- **Expected ROI**: ${r.expected_roi_pct}%`)
    lines.push('')
  }

  lines.push('### Risk Analysis')
  lines.push(result.risk_analysis)
  lines.push('')

  if (input.market_trends && input.market_trends.length > 0) {
    lines.push('### Market Trends Considered')
    for (const trend of input.market_trends) {
      lines.push(`- ${trend}`)
    }
    lines.push('')
  }

  lines.push(DISCLAIMER)
  return lines.join('\n')
}

// ==================== PLUGIN REGISTRATION ====================

export function apply(ctx: Context) {
  const tools = ctx.tools

  // Tool 1: IP Registration Advisor
  tools.register(defineTool({
    name: 'ip_registration_advisor',
    description: 'Advises on IP registration strategy (copyright, trademark, patent) for creative works. Evaluates work type, jurisdictions, budget, commercial potential, and prior art search needs. Returns prioritized action plan with cost estimates, timelines, and risk assessment.',
    parameters: {
      input_data: { type: 'string', description: 'JSON-encoded input with fields: work_type, jurisdiction[], budget_usd, commercial_potential (low|medium|high|blockbuster), prior_art_search_needed', required: true }
    },
    output: { schema: { type: 'string' }, render: 'text' },
    async execute(args: { input_data: string }) {
      const input: IPRRegistrationInput = JSON.parse(args.input_data)
      const result = adviseIPRegistration(input)
      return formatIPRegistrationReport(input, result)
    }
  }))

  // Tool 2: Derivative Works Strategist
  tools.register(defineTool({
    name: 'derivative_works_strategist',
    description: 'Plans derivative works strategy (merch, adaptations, spin-offs) for an IP. Analyzes target formats, market demand, budget, and timeline. Returns prioritized format plans with revenue projections, cost estimates, and a phased development roadmap.',
    parameters: {
      input_data: { type: 'string', description: 'JSON-encoded input with fields: original_ip{name, genre, audience}, target_formats[], market_demand[{format, demand_score}], budget_usd, timeline_months', required: true }
    },
    output: { schema: { type: 'string' }, render: 'text' },
    async execute(args: { input_data: string }) {
      const input: DerivativeWorksInput = JSON.parse(args.input_data)
      const result = planDerivativeWorks(input)
      return formatDerivativeWorksReport(input, result)
    }
  }))

  // Tool 3: Cross-Media Adaptation Planner
  tools.register(defineTool({
    name: 'cross_media_adaptation_planner',
    description: 'Plans cross-media adaptation (novel to animation to game to film). Maps source IP to target media with difficulty assessment, cost estimates, timelines, key challenges, and opportunities. Includes risk assessment based on budget and risk tolerance.',
    parameters: {
      input_data: { type: 'string', description: 'JSON-encoded input with fields: source_ip{title, medium}, target_media[], audience_analysis{primary_age, platforms[]}, production_budget_usd, risk_tolerance (low|medium|high)', required: true }
    },
    output: { schema: { type: 'string' }, render: 'text' },
    async execute(args: { input_data: string }) {
      const input: CrossMediaInput = JSON.parse(args.input_data)
      const result = planCrossMediaAdaptation(input)
      return formatCrossMediaReport(input, result)
    }
  }))

  // Tool 4: IP Valuation Creative
  tools.register(defineTool({
    name: 'ip_valuation_creative',
    description: 'Values a creative IP based on audience size, engagement rate, revenue streams, comparable deals, and growth trajectory. Returns estimated value with range, valuation method, revenue multiplier, comparable analysis, and growth adjustment notes.',
    parameters: {
      input_data: { type: 'string', description: 'JSON-encoded input with fields: ip_name, audience_size, engagement_rate, revenue_streams[{source, monthly_usd}], comparable_deals[{deal_name, value_usd}], growth_trajectory (declining|stable|growing|viral)', required: true }
    },
    output: { schema: { type: 'string' }, render: 'text' },
    async execute(args: { input_data: string }) {
      const input: IPValuationInput = JSON.parse(args.input_data)
      const result = valueCreativeIP(input)
      return formatIPValuationReport(input, result)
    }
  }))

  // Tool 5: Anti-Piracy Monitor Designer
  tools.register(defineTool({
    name: 'anti_piracy_monitor_designer',
    description: 'Designs anti-piracy monitoring strategy for digital creative works. Creates monitoring layers (web, social, P2P, marketplace, watermarking) with coverage, cost, response time, and effectiveness metrics. Includes prevention tips and takedown speed optimization.',
    parameters: {
      input_data: { type: 'string', description: 'JSON-encoded input with fields: content_type, distribution_channels[], monitoring_budget_usd, takedown_speed_requirement (standard|fast|immediate), jurisdiction[]', required: true }
    },
    output: { schema: { type: 'string' }, render: 'text' },
    async execute(args: { input_data: string }) {
      const input: AntiPiracyInput = JSON.parse(args.input_data)
      const result = designAntiPiracyMonitoring(input)
      return formatAntiPiracyReport(input, result)
    }
  }))

  // Tool 6: Licensing Deal Structurer
  tools.register(defineTool({
    name: 'licensing_deal_structurer',
    description: 'Structures licensing deals for creative IP (territory, duration, exclusivity, royalties). Generates deal terms, payment milestones, risk factors, and recommendations. Covers exclusive, non-exclusive, and sole licensing models with advance calculations.',
    parameters: {
      input_data: { type: 'string', description: 'JSON-encoded input with fields: ip_assets[{asset_name, asset_type}], licensee_profile{company, size, territory}, deal_type (exclusive|non_exclusive|sole), minimum_guarantee_usd, royalty_rate_range{min_pct, max_pct}', required: true }
    },
    output: { schema: { type: 'string' }, render: 'text' },
    async execute(args: { input_data: string }) {
      const input: LicensingInput = JSON.parse(args.input_data)
      const result = structureLicensingDeal(input)
      return formatLicensingDealReport(input, result)
    }
  }))

  // Tool 7: Creator Brand Builder
  tools.register(defineTool({
    name: 'creator_brand_builder',
    description: 'Builds a creator brand strategy (platform, content, monetization, community). Generates brand positioning, content pillars, platform-specific strategies, phased monetization roadmap, and community building tips. Optimized for individual creators building sustainable brands.',
    parameters: {
      input_data: { type: 'string', description: 'JSON-encoded input with fields: creator_profile{name, expertise, years_experience}, content_niche, target_audience{age_range, interests[]}, platform_mix[], monetization_goals[]', required: true }
    },
    output: { schema: { type: 'string' }, render: 'text' },
    async execute(args: { input_data: string }) {
      const input: CreatorBrandInput = JSON.parse(args.input_data)
      const result = buildCreatorBrand(input)
      return formatCreatorBrandReport(input, result)
    }
  }))

  // Tool 8: IP Portfolio Diversifier
  tools.register(defineTool({
    name: 'ip_portfolio_diversifier',
    description: 'Advises on diversifying a creative IP portfolio across formats, genres, and markets. Calculates current diversity score, generates prioritized recommendations (expand, diversify, consolidate, exit), and provides risk analysis based on risk tolerance and time horizon.',
    parameters: {
      input_data: { type: 'string', description: 'JSON-encoded input with fields: current_portfolio[{ip_name, format, genre, revenue_usd}], risk_tolerance (low|medium|high), investment_budget_usd, market_trends[], time_horizon_years', required: true }
    },
    output: { schema: { type: 'string' }, render: 'text' },
    async execute(args: { input_data: string }) {
      const input: PortfolioDiversifierInput = JSON.parse(args.input_data)
      const result = diversifyIPPortfolio(input)
      return formatPortfolioDiversifierReport(input, result)
    }
  }))

  console.log(`[dsh-tool-creativeip] Loaded v${VERSION} - Creative IP Operations and Protection with 8 tools`)
  console.log('  Tools: ip_registration_advisor, derivative_works_strategist, cross_media_adaptation_planner, ip_valuation_creative, anti_piracy_monitor_designer, licensing_deal_structurer, creator_brand_builder, ip_portfolio_diversifier')
}
