/**
 * DSH Cybersecurity & Threat Intelligence Plugin v0.1.0
 *
 * Enterprise cybersecurity toolkit targeting the $300B+ cybersecurity market
 * with AI-powered security tools growing at 20% CAGR. Provides deterministic
 * threat intelligence, vulnerability management, incident response, security
 * orchestration, attack surface mapping, malware analysis, posture scoring,
 * * and zero trust architecture advisory.
 *
 * Tools (8):
 * 1. threat_intelligence_aggregator  - Aggregate and correlate threat intelligence from multiple sources
 * 2. vulnerability_management_engine  - Scan, prioritize, and manage vulnerability remediation
 * 3. incident_response_orchestrator   - Orchestrate end-to-end incident response workflows
 * 4. security_orchestration_automator - Automate SOAR playbooks and security workflows
 * 5. attack_surface_mapper            - Map and analyze organizational attack surface
 * 6. malware_behavior_analyst        - Analyze malware behavior patterns and indicators
 * 7. security_posture_scorer          - Score and benchmark organizational security posture
 * 8. zero_trust_architecture_advisor  - Advise on zero trust architecture implementation
 *
 * @module dsh-tool-cyberthreat
 * @version 0.1.0
 * @license MIT
 */

import type { Context } from '@deepseek-ai/cordis'
import { defineTool } from '@deepseek-ai/dsh-tools'

export const name = 'dsh-tool-cyberthreat'
export const inject = ['tools']

/* ─────────────────────────────────────────────
   Disclaimer
   ───────────────────────────────────────────── */
const DISCLAIMER =
  'This analysis is generated by AI model inference and deterministic algorithms. It is for reference only and does not replace professional cybersecurity assessment, penetration testing, or certified security auditing.'

/* ─────────────────────────────────────────────
   SeededRandom (mulberry32 PRNG)
   Seed derived from JSON.stringify(input)
   ───────────────────────────────────────────── */
function createSeededRandom(seed: number) {
  let s = seed | 0
  return () => {
    s = (s + 0x6d2b79f5) | 0
    let t = Math.imul(s ^ (s >>> 15), 1 | s)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function hashString(str: string): number {
  let hash = 0
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i)
    hash = ((hash << 5) - hash) + char
    hash = hash & hash
  }
  return Math.abs(hash) || 1
}

function createRngFromInput(input: unknown) {
  const seed = hashString(JSON.stringify(input))
  return createSeededRandom(seed)
}

/** Deterministic pick from array */
function pick<T>(rng: () => number, arr: T[]): T {
  return arr[Math.floor(rng() * arr.length)]
}

/** Deterministic pick N unique items from array */
function pickN<T>(rng: () => number, arr: T[], n: number): T[] {
  const copy = [...arr]
  const result: T[] = []
  for (let i = 0; i < Math.min(n, copy.length); i++) {
    const idx = Math.floor(rng() * copy.length)
    result.push(copy.splice(idx, 1)[0])
  }
  return result
}

/** Deterministic integer in range [min, max] */
function randInt(rng: () => number, min: number, max: number): number {
  return Math.floor(rng() * (max - min + 1)) + min
}

/* ─────────────────────────────────────────────
   1. Threat Intelligence Aggregator
   ───────────────────────────────────────────── */
export interface ThreatIntelInput {
  organization: string
  industry: string
  sources: string[]
  threat_types: string[]
  time_window_days: number
  severity_threshold: 'critical' | 'high' | 'medium' | 'low' | 'all'
}

export interface ThreatIndicator {
  ioc: string
  type: string
  severity: string
  confidence: number
  source: string
  first_seen: string
  last_seen: string
  related_campaigns: string[]
  mitre_technique: string
}

export interface ThreatActor {
  name: string
  motivation: string
  sophistication: string
  origin: string
  targeted_sectors: string[]
  known_tools: string[]
  active: boolean
}

export interface ThreatIntelResult {
  organization: string
  industry: string
  aggregation_id: string
  time_window_days: number
  total_indicators: number
  indicators: ThreatIndicator[]
  threat_actors: ThreatActor[]
  campaign_correlations: string[]
  trend_analysis: string[]
  recommended_actions: string[]
  risk_level: 'Critical' | 'High' | 'Medium' | 'Low'
}

function aggregateThreatIntel(input: ThreatIntelInput): ThreatIntelResult {
  const rng = createRngFromInput(input)
  const aggregationId = `TI-${randInt(rng, 10000, 99999)}`

  const iocTypes = ['IP Address', 'Domain', 'File Hash (SHA256)', 'URL', 'Email Address', 'CVE', 'Mutex', 'Registry Key', 'Certificate Hash', 'YARA Rule']
  const severities = ['Critical', 'High', 'Medium', 'Low']
  const sources = input.sources.length > 0 ? input.sources : ['AlienVault OTX', 'VirusTotal', 'MISP', 'Shodan', 'Abuse.ch', 'CISA KEV', 'Recorded Future', 'ThreatConnect']
  const campaigns = ['APT28-Fancy Bear', 'APT29-Cozy Bear', 'Lazarus Group', 'Equation Group', 'Carbanak', 'CozyDuke', 'Sandworm', 'Turla', 'Kimsuky', 'MuddyWater']
  const mitreTechniques = ['T1566-Phishing', 'T1059-Command Scripting', 'T1078-Valid Accounts', 'T1105-Ingress Tool Transfer', 'T1048-Exfiltration', 'T1486-Data Encrypted', 'T1562-Impair Defenses', 'T1021-Remote Services', 'T1003-Credential Dumping', 'T1053-Scheduled Task']

  const indicatorCount = randInt(rng, 8, 25)
  const indicators: ThreatIndicator[] = []
  for (let i = 0; i < indicatorCount; i++) {
    const iocType = pick(rng, iocTypes)
    let ioc = ''
    switch (iocType) {
      case 'IP Address': ioc = `${randInt(rng, 1, 255)}.${randInt(rng, 0, 255)}.${randInt(rng, 0, 255)}.${randInt(rng, 1, 255)}`; break
      case 'Domain': ioc = `mal${randInt(rng, 100, 999)}-${pick(rng, ['c2', 'drop', 'update', 'cdn'])}.${pick(rng, ['xyz', 'top', 'club', 'online', 'site'])}`; break
      case 'File Hash (SHA256)': ioc = Array.from({ length: 64 }, () => '0123456789abcdef'[randInt(rng, 0, 15)]).join(''); break
      case 'URL': ioc = `https://mal-${randInt(rng, 100, 999)}.${pick(rng, ['xyz', 'top', 'club'])}/${pick(rng, ['update', 'download', 'api', 'gate'])}.php`; break
      case 'Email Address': ioc = `actor${randInt(rng, 1, 99)}@${pick(rng, ['protonmail.com', 'tutanota.com', 'gmail.com'])}`; break
      case 'CVE': ioc = `CVE-2025-${randInt(rng, 10000, 99999)}`; break
      default: ioc = `indicator-${randInt(rng, 100000, 999999)}`; break
    }

    const sevIdx = randInt(rng, 0, 3)
    const severityThresholdIdx = input.severity_threshold === 'all' ? 3 : severities.indexOf(input.severity_threshold.charAt(0).toUpperCase() + input.severity_threshold.slice(1))
    const severity = severityThresholdIdx < sevIdx ? severities[sevIdx] : severities[Math.min(sevIdx, severityThresholdIdx)]

    indicators.push({
      ioc,
      type: iocType,
      severity,
      confidence: Math.round((0.5 + rng() * 0.5) * 100) / 100,
      source: pick(rng, sources),
      first_seen: `2025-${String(randInt(rng, 1, 7)).padStart(2, '0')}-${String(randInt(rng, 1, 28)).padStart(2, '0')}`,
      last_seen: `2025-${String(randInt(rng, 8, 12)).padStart(2, '0')}-${String(randInt(rng, 1, 28)).padStart(2, '0')}`,
      related_campaigns: pickN(rng, campaigns, randInt(rng, 1, 3)),
      mitre_technique: pick(rng, mitreTechniques),
    })
  }

  const actorCount = randInt(rng, 3, 7)
  const motivations = ['Cybercrime', 'Espionage', 'Hacktivism', 'Destructive', 'Financial Theft', 'State-Sponsored']
  const sophisticationLevels = ['Low', 'Moderate', 'High', 'Advanced Persistent', 'Elite']
  const origins = ['CN', 'RU', 'KP', 'IR', 'Unknown', 'Eastern Europe', 'Southeast Asia']
  const sectors = ['Finance', 'Healthcare', 'Government', 'Energy', 'Technology', 'Defense', 'Telecom', 'Manufacturing', 'Education', 'Critical Infrastructure']
  const tools = ['Cobalt Strike', 'Metasploit', 'Mimikatz', 'PowerShell Empire', 'Cobalt Beacon', 'Custom RAT', 'Living-off-Land', 'Fileless Malware', 'Supply Chain Compromise', 'Zero-Day Exploit']

  const threatActors: ThreatActor[] = []
  for (let i = 0; i < actorCount; i++) {
    threatActors.push({
      name: pick(rng, campaigns) + `-${randInt(rng, 1, 99)}`,
      motivation: pick(rng, motivations),
      sophistication: pick(rng, sophisticationLevels),
      origin: pick(rng, origins),
      targeted_sectors: pickN(rng, sectors, randInt(rng, 2, 4)),
      known_tools: pickN(rng, tools, randInt(rng, 2, 5)),
      active: rng() > 0.3,
    })
  }

  const campaignCorrelations: string[] = []
  const selectedCampaigns = pickN(rng, campaigns, randInt(rng, 3, 5))
  for (const camp of selectedCampaigns) {
    campaignCorrelations.push(`${camp}: ${randInt(rng, 3, 15)} correlated indicators detected in ${input.industry} sector`)
  }

  const trendAnalysis: string[] = []
  trendAnalysis.push(`Phishing campaigns targeting ${input.industry} increased ${randInt(rng, 15, 65)}% in the last ${input.time_window_days} days`)
  trendAnalysis.push(`Ransomware variants targeting ${input.industry}: ${randInt(rng, 5, 20)} new families identified`)
  trendAnalysis.push(`Zero-day exploits observed: ${randInt(rng, 1, 8)} in the analysis window`)
  trendAnalysis.push(`Credential stuffing attacks from ${pick(rng, origins)}-based infrastructure: ${randInt(rng, 100, 2000)} attempts/day`)
  trendAnalysis.push(`Supply chain compromise attempts: ${randInt(rng, 0, 5)} detected via dependency monitoring`)

  const recommendedActions: string[] = []
  recommendedActions.push(`Block ${indicators.filter(i => i.type === 'IP Address').length} identified malicious IPs at perimeter firewall`)
  recommendedActions.push(`Deploy IOCs to SIEM for real-time detection (${indicators.length} indicators)`)
  recommendedActions.push(`Update email filtering rules for ${indicators.filter(i => i.type === 'Email Address').length} malicious sender patterns`)
  recommendedActions.push(`Patch systems against ${indicators.filter(i => i.type === 'CVE').length} identified CVEs`)
  recommendedActions.push(`Conduct threat hunt for TTPs associated with ${threatActors.filter(a => a.active).length} active threat actors`)
  recommendedActions.push(`Brief executive leadership on ${input.industry}-specific threat landscape`)

  const criticalCount = indicators.filter(i => i.severity === 'Critical').length
  const highCount = indicators.filter(i => i.severity === 'High').length
  let riskLevel: ThreatIntelResult['risk_level'] = 'Low'
  if (criticalCount >= 3) riskLevel = 'Critical'
  else if (criticalCount >= 1 || highCount >= 5) riskLevel = 'High'
  else if (highCount >= 2) riskLevel = 'Medium'

  return {
    organization: input.organization,
    industry: input.industry,
    aggregation_id: aggregationId,
    time_window_days: input.time_window_days,
    total_indicators: indicators.length,
    indicators,
    threat_actors: threatActors,
    campaign_correlations: campaignCorrelations,
    trend_analysis: trendAnalysis,
    recommended_actions: recommendedActions,
    risk_level: riskLevel,
  }
}

function formatThreatIntelReport(r: ThreatIntelResult): string {
  const lines: string[] = []
  lines.push('## Threat Intelligence Aggregation Report')
  lines.push('')
  lines.push(`**Organization:** ${r.organization} | **Industry:** ${r.industry} | **Aggregation ID:** ${r.aggregation_id}`)
  lines.push(`**Time Window:** ${r.time_window_days} days | **Total Indicators:** ${r.total_indicators} | **Risk Level:** ${r.risk_level}`)
  lines.push('')
  lines.push('### Key Indicators of Compromise')
  lines.push('| IOC | Type | Severity | Confidence | Source | MITRE |')
  lines.push('|-----|------|----------|------------|--------|-------|')
  for (const i of r.indicators.slice(0, 15)) {
    lines.push(`| ${i.ioc.substring(0, 40)} | ${i.type} | ${i.severity} | ${(i.confidence * 100).toFixed(0)}% | ${i.source} | ${i.mitre_technique} |`)
  }
  if (r.indicators.length > 15) lines.push(`| ... and ${r.indicators.length - 15} more indicators | | | | | |`)
  lines.push('')
  lines.push('### Threat Actors')
  for (const a of r.threat_actors) {
    lines.push(`- **${a.name}** [${a.sophistication}] | Origin: ${a.origin} | Motivation: ${a.motivation} | Active: ${a.active ? 'Yes' : 'No'}`)
    lines.push(`  - Targets: ${a.targeted_sectors.join(', ')}`)
    lines.push(`  - Tools: ${a.known_tools.join(', ')}`)
  }
  lines.push('')
  lines.push('### Campaign Correlations')
  for (const c of r.campaign_correlations) lines.push(`- ${c}`)
  lines.push('')
  lines.push('### Trend Analysis')
  for (const t of r.trend_analysis) lines.push(`- ${t}`)
  lines.push('')
  lines.push('### Recommended Actions')
  for (const a of r.recommended_actions) lines.push(`- [ ] ${a}`)
  lines.push('')
  lines.push(`> **Disclaimer:** ${DISCLAIMER}`)
  return lines.join('\n')
}

/* ─────────────────────────────────────────────
   2. Vulnerability Management Engine
   ───────────────────────────────────────────── */
export interface VulnMgmtInput {
  asset_scope: string[]
  environment: 'production' | 'staging' | 'development' | 'cloud' | 'hybrid'
  scan_depth: 'surface' | 'standard' | 'deep' | 'compliance'
  max_results: number
  include_exploitability: boolean
}

export interface Vulnerability {
  cve_id: string
  cvss_score: number
  severity: 'Critical' | 'High' | 'Medium' | 'Low'
  asset: string
  description: string
  exploit_available: boolean
  patch_available: boolean
  remediation_effort: 'Low' | 'Medium' | 'High'
  days_open: number
  epss_score: number
}

export interface VulnMgmtResult {
  scan_id: string
  environment: string
  scan_depth: string
  total_vulnerabilities: number
  by_severity: Record<string, number>
  vulnerabilities: Vulnerability[]
  remediation_plan: string[]
  compliance_gaps: string[]
  risk_acceptance_items: string[]
  mttr_estimate: string
}

function runVulnManagement(input: VulnMgmtInput): VulnMgmtResult {
  const rng = createRngFromInput(input)
  const scanId = `VULN-${randInt(rng, 10000, 99999)}`

  const vulnTemplates = [
    { desc: 'Remote Code Execution via deserialization', cvss: 9.8, sev: 'Critical' as const },
    { desc: 'SQL Injection in authentication endpoint', cvss: 9.1, sev: 'Critical' as const },
    { desc: 'Server-Side Request Forgery (SSRF)', cvss: 8.6, sev: 'High' as const },
    { desc: 'Cross-Site Scripting (Stored)', cvss: 7.5, sev: 'High' as const },
    { desc: 'Privilege Escalation via misconfigured IAM', cvss: 8.2, sev: 'High' as const },
    { desc: 'Insecure Direct Object Reference (IDOR)', cvss: 7.8, sev: 'High' as const },
    { desc: 'XML External Entity (XXE) Injection', cvss: 8.4, sev: 'High' as const },
    { desc: 'Path Traversal in file upload', cvss: 7.2, sev: 'High' as const },
    { desc: 'Weak TLS configuration (TLS 1.0 enabled)', cvss: 5.9, sev: 'Medium' as const },
    { desc: 'Missing security headers (CSP/HSTS)', cvss: 4.3, sev: 'Medium' as const },
    { desc: 'Information disclosure via error messages', cvss: 5.3, sev: 'Medium' as const },
    { desc: 'Outdated library with known CVE', cvss: 6.5, sev: 'Medium' as const },
    { desc: 'Default credentials on admin panel', cvss: 9.5, sev: 'Critical' as const },
    { desc: 'Unauthenticated API endpoint exposure', cvss: 7.1, sev: 'High' as const },
    { desc: 'Container escape via privileged mode', cvss: 8.9, sev: 'Critical' as const },
    { desc: 'Kubernetes RBAC misconfiguration', cvss: 7.4, sev: 'High' as const },
    { desc: 'Cloud storage bucket public access', cvss: 6.8, sev: 'Medium' as const },
    { desc: 'Insecure secrets in environment variables', cvss: 7.9, sev: 'High' as const },
    { desc: 'Missing MFA on privileged accounts', cvss: 8.1, sev: 'High' as const },
    { desc: 'Log injection vulnerability', cvss: 4.8, sev: 'Medium' as const },
  ]

  const assets = input.asset_scope.length > 0 ? input.asset_scope : ['web-app-01', 'api-gateway', 'db-primary', 'k8s-cluster', 'cdn-edge', 'auth-service']
  const maxResults = input.max_results || randInt(rng, 10, 20)
  const vulnCount = Math.min(maxResults, randInt(rng, 8, vulnTemplates.length))

  const vulnerabilities: Vulnerability[] = []
  const selectedTemplates = pickN(rng, vulnTemplates, vulnCount)
  for (const tpl of selectedTemplates) {
    const cvssVariance = (rng() * 1.4) - 0.7
    const cvss = Math.max(0, Math.min(10, tpl.cvss + cvssVariance))
    const severity = cvss >= 9.0 ? 'Critical' : cvss >= 7.0 ? 'High' : cvss >= 4.0 ? 'Medium' : 'Low'
    const exploitAvailable = input.include_exploitability && (cvss >= 7.0 ? rng() > 0.3 : rng() > 0.7)

    vulnerabilities.push({
      cve_id: `CVE-2025-${randInt(rng, 10000, 99999)}`,
      cvss_score: Math.round(cvss * 10) / 10,
      severity,
      asset: pick(rng, assets),
      description: tpl.desc,
      exploit_available: exploitAvailable,
      patch_available: rng() > 0.25,
      remediation_effort: cvss >= 9.0 ? 'High' : cvss >= 7.0 ? (rng() > 0.5 ? 'Medium' : 'High') : 'Low',
      days_open: randInt(rng, 1, 180),
      epss_score: Math.round((rng() * (cvss / 10)) * 100) / 100,
    })
  }

  const bySeverity: Record<string, number> = { Critical: 0, High: 0, Medium: 0, Low: 0 }
  for (const v of vulnerabilities) bySeverity[v.severity]++

  const remediationPlan: string[] = []
  const criticalVulns = vulnerabilities.filter(v => v.severity === 'Critical')
  const highVulns = vulnerabilities.filter(v => v.severity === 'High')
  const exploitable = vulnerabilities.filter(v => v.exploit_available)

  if (criticalVulns.length > 0) {
    remediationPlan.push(`IMMEDIATE (24hr): Patch ${criticalVulns.length} Critical vulnerabilities: ${criticalVulns.slice(0, 3).map(v => v.cve_id).join(', ')}`)
  }
  if (exploitable.length > 0) {
    remediationPlan.push(`URGENT (48hr): Address ${exploitable.length} exploitable vulnerabilities with public PoC/exploit code`)
  }
  if (highVulns.length > 0) {
    remediationPlan.push(`HIGH (7 days): Remediate ${highVulns.length} High-severity vulnerabilities`)
  }
  remediationPlan.push(`STANDARD (30 days): Address ${vulnerabilities.filter(v => v.severity === 'Medium').length} Medium-severity findings`)
  remediationPlan.push(`PLANNED (90 days): Resolve ${vulnerabilities.filter(v => v.severity === 'Low').length} Low-severity findings via regular patching cycle`)
  remediationPlan.push(`Process: Implement continuous vulnerability scanning with weekly reporting cadence`)

  const complianceGaps: string[] = []
  if (criticalVulns.length > 0) complianceGaps.push('SOC2 CC7.1: Critical vulnerabilities exceed 24-hour remediation SLA')
  if (vulnerabilities.filter(v => v.days_open > 30).length > 3) complianceGaps.push('PCI DSS Req 6.2: Multiple vulnerabilities past 30-day remediation window')
  if (vulnerabilities.filter(v => !v.patch_available).length > 0) complianceGaps.push('ISO27001 A.12.6.1: Unpatched vulnerabilities require risk acceptance documentation')
  if (input.environment === 'cloud' && vulnerabilities.some(v => v.description.includes('bucket') || v.description.includes('RBAC'))) {
    complianceGaps.push('CSA CCM: Cloud security configuration gaps identified')
  }

  const riskAcceptanceItems: string[] = []
  const unpatched = vulnerabilities.filter(v => !v.patch_available)
  for (const v of unpatched.slice(0, 3)) {
    riskAcceptanceItems.push(`${v.cve_id} on ${v.asset}: No patch available - compensating controls required`)
  }

  const avgDaysOpen = vulnerabilities.reduce((s, v) => s + v.days_open, 0) / vulnerabilities.length
  const mttrEstimate = avgDaysOpen > 60 ? '60+ days (process improvement needed)' : avgDaysOpen > 30 ? '30-60 days' : '14-30 days'

  return {
    scan_id: scanId,
    environment: input.environment,
    scan_depth: input.scan_depth,
    total_vulnerabilities: vulnerabilities.length,
    by_severity: bySeverity,
    vulnerabilities,
    remediation_plan: remediationPlan,
    compliance_gaps: complianceGaps,
    risk_acceptance_items: riskAcceptanceItems,
    mttr_estimate: mttrEstimate,
  }
}

function formatVulnMgmtReport(r: VulnMgmtResult): string {
  const lines: string[] = []
  lines.push('## Vulnerability Management Report')
  lines.push('')
  lines.push(`**Scan ID:** ${r.scan_id} | **Environment:** ${r.environment} | **Scan Depth:** ${r.scan_depth}`)
  lines.push(`**Total Vulnerabilities:** ${r.total_vulnerabilities} | **MTTR Estimate:** ${r.mttr_estimate}`)
  lines.push('')
  lines.push('### Severity Breakdown')
  lines.push(`- Critical: ${r.by_severity.Critical} | High: ${r.by_severity.High} | Medium: ${r.by_severity.Medium} | Low: ${r.by_severity.Low}`)
  lines.push('')
  lines.push('### Top Vulnerabilities')
  lines.push('| CVE | CVSS | Severity | Asset | Exploit | Patch | EPSS |')
  lines.push('|-----|------|----------|-------|---------|-------|------|')
  for (const v of r.vulnerabilities.slice(0, 12)) {
    lines.push(`| ${v.cve_id} | ${v.cvss_score} | ${v.severity} | ${v.asset} | ${v.exploit_available ? 'Yes' : 'No'} | ${v.patch_available ? 'Yes' : 'No'} | ${v.epss_score} |`)
  }
  lines.push('')
  lines.push('### Remediation Plan')
  for (const p of r.remediation_plan) lines.push(`- ${p}`)
  lines.push('')
  if (r.compliance_gaps.length > 0) {
    lines.push('### Compliance Gaps')
    for (const g of r.compliance_gaps) lines.push(`- ${g}`)
    lines.push('')
  }
  if (r.risk_acceptance_items.length > 0) {
    lines.push('### Risk Acceptance Required')
    for (const item of r.risk_acceptance_items) lines.push(`- ${item}`)
    lines.push('')
  }
  lines.push(`> **Disclaimer:** ${DISCLAIMER}`)
  return lines.join('\n')
}

/* ─────────────────────────────────────────────
   3. Incident Response Orchestrator
   ───────────────────────────────────────────── */
export interface IRInput {
  incident_type: 'ransomware' | 'data_breach' | 'ddos' | 'insider_threat' | 'apt' | 'supply_chain' | 'phishing_campaign' | 'zero_day'
  severity: 'P1' | 'P2' | 'P3' | 'P4'
  affected_systems: number
  data_volume_gb: number
  regulatory_scope: string[]
  containment_status: 'none' | 'partial' | 'full'
}

export interface IRPhase {
  name: string
  order: number
  status: 'pending' | 'active' | 'completed'
  actions: string[]
  owner: string
  sla_minutes: number
  dependencies: string[]
}

export interface IRResult {
  incident_id: string
  incident_type: string
  severity: string
  phases: IRPhase[]
  containment_actions: string[]
  eradication_steps: string[]
  recovery_procedures: string[]
  communication_timeline: string[]
  regulatory_notifications: string[]
  estimated_total_recovery_hours: number
  lessons_learned_template: string[]
}

function orchestrateIncidentResponse(input: IRInput): IRResult {
  const rng = createRngFromInput(input)
  const incidentId = `IR-${randInt(rng, 10000, 99999)}`

  const severitySLA: Record<string, number> = { P1: 15, P2: 30, P3: 60, P4: 120 }
  const baseSLA = severitySLA[input.severity]

  const phases: IRPhase[] = [
    {
      name: 'Detection & Triage',
      order: 1,
      status: 'active',
      actions: [
        'Validate incident indicators and confirm scope',
        'Activate incident response team and assign roles',
        'Establish secure communication channel (out-of-band)',
        'Begin evidence preservation and chain of custody',
        'Classify incident severity and escalation path',
      ],
      owner: 'SOC Lead',
      sla_minutes: baseSLA,
      dependencies: [],
    },
    {
      name: 'Containment',
      order: 2,
      status: input.containment_status === 'full' ? 'completed' : input.containment_status === 'partial' ? 'active' : 'pending',
      actions: [
        `Isolate ${input.affected_systems} affected systems from network`,
        'Block identified attack vectors at perimeter',
        'Disable compromised accounts and revoke sessions',
        'Deploy network segmentation for affected segments',
        'Enable enhanced logging on all adjacent systems',
      ],
      owner: 'Security Engineering',
      sla_minutes: baseSLA * 2,
      dependencies: ['Detection & Triage'],
    },
    {
      name: 'Eradication',
      order: 3,
      status: 'pending',
      actions: [
        'Remove malware and attacker artifacts from all systems',
        'Patch exploited vulnerabilities',
        'Reset all credentials in affected scope',
        'Scan for persistence mechanisms and backdoors',
        'Verify integrity of all affected systems',
      ],
      owner: 'Incident Response Team',
      sla_minutes: baseSLA * 6,
      dependencies: ['Containment'],
    },
    {
      name: 'Recovery',
      order: 4,
      status: 'pending',
      actions: [
        'Restore systems from verified clean backups',
        'Gradually reintroduce systems to production',
        'Monitor restored systems for re-compromise indicators',
        'Validate business functionality of recovered systems',
        'Implement additional monitoring on recovered assets',
      ],
      owner: 'IT Operations',
      sla_minutes: baseSLA * 12,
      dependencies: ['Eradication'],
    },
    {
      name: 'Post-Incident & Lessons Learned',
      order: 5,
      status: 'pending',
      actions: [
        'Conduct formal root cause analysis (RCA)',
        'Document timeline of all incident activities',
        'Update playbooks with new TTPs and IOCs',
        'Brief executive leadership and board (if required)',
        'Implement preventive controls identified during RCA',
      ],
      owner: 'CISO Office',
      sla_minutes: baseSLA * 168,
      dependencies: ['Recovery'],
    },
  ]

  const containmentActions: string[] = []
  containmentActions.push(`[ ] Network isolation: ${input.affected_systems} systems quarantined`)
  containmentActions.push(`[ ] Attack vector blocked at firewall/proxy`)
  containmentActions.push(`[ ] Compromised credentials revoked and force-reset initiated`)
  containmentActions.push(`[ ] Forensic images captured for ${Math.ceil(input.affected_systems * 0.3)} priority systems`)
  containmentActions.push(`[ ] Threat hunting initiated across environment for related IOCs`)

  const eradicationSteps: string[] = []
  eradicationSteps.push('Full malware scan across all affected and adjacent systems')
  eradicationSteps.push('Registry and filesystem analysis for persistence mechanisms')
  eradicationSteps.push('Memory forensics on critical systems for fileless malware')
  eradicationSteps.push('Credential rotation for all service accounts in scope')
  eradicationSteps.push('Patch deployment for all exploited vulnerabilities')
  eradicationSteps.push('Verify no C2 communication from any internal system')

  const recoveryProcedures: string[] = []
  recoveryProcedures.push('Restore from last known-good backup (verify backup integrity first)')
  recoveryProcedures.push('Staged recovery: Critical business functions first, then supporting systems')
  recoveryProcedures.push('Enhanced monitoring period: 72 hours post-recovery for re-compromise')
  recoveryProcedures.push('User acceptance testing before declaring systems fully recovered')
  recoveryProcedures.push('Update disaster recovery documentation with new recovery procedures')

  const communicationTimeline: string[] = []
  communicationTimeline.push(`T+0min: Internal IR team activation and secure comms established`)
  communicationTimeline.push(`T+${baseSLA}min: Initial assessment to CISO and executive team`)
  communicationTimeline.push(`T+${baseSLA * 2}min: Stakeholder notification with impact assessment`)
  communicationTimeline.push(`T+${baseSLA * 4}min: Status update to all employees (if customer-facing)`)
  communicationTimeline.push(`T+24hr: Detailed incident report to leadership`)
  communicationTimeline.push(`T+72hr: External communications (customers, partners) if required`)
  communicationTimeline.push(`T+7days: Final incident report and lessons learned`)

  const regulatoryNotifications: string[] = []
  for (const reg of input.regulatory_scope) {
    if (reg.toLowerCase().includes('gdpr')) {
      regulatoryNotifications.push('GDPR: Supervisory authority notification within 72 hours (Art. 33)')
      regulatoryNotifications.push('GDPR: Data subject notification if high risk (Art. 34)')
    }
    if (reg.toLowerCase().includes('hipaa')) {
      regulatoryNotifications.push('HIPAA: HHS notification within 60 days if >500 records (Breach Notification Rule)')
    }
    if (reg.toLowerCase().includes('pci')) {
      regulatoryNotifications.push('PCI DSS: Acquirer and card brand notification within 24 hours of confirmation')
    }
    if (reg.toLowerCase().includes('soc2')) {
      regulatoryNotifications.push('SOC 2: Customer notification per contractual SLA requirements')
    }
    if (reg.toLowerCase().includes('sec')) {
      regulatoryNotifications.push('SEC: Material incident disclosure within 4 business days (Form 8-K)')
    }
  }
  if (regulatoryNotifications.length === 0) {
    regulatoryNotifications.push('No specific regulatory notification requirements identified')
    regulatoryNotifications.push('Review contractual obligations for customer notification SLAs')
  }

  const baseRecoveryHours: Record<string, number> = { P1: 48, P2: 24, P3: 12, P4: 8 }
  const estimatedHours = baseRecoveryHours[input.severity] + Math.ceil(input.affected_systems * 0.5) + Math.ceil(input.data_volume_gb * 0.1)

  const lessonsLearnedTemplate: string[] = []
  lessonsLearnedTemplate.push('1. Incident Summary: [What happened, when, detected by whom]')
  lessonsLearnedTemplate.push('2. Root Cause: [Technical and procedural root cause]')
  lessonsLearnedTemplate.push('3. Timeline: [Detailed minute-by-minute timeline]')
  lessonsLearnedTemplate.push('4. What Went Well: [Effective response actions]')
  lessonsLearnedTemplate.push('5. What Needs Improvement: [Gaps in detection/response]')
  lessonsLearnedTemplate.push('6. Action Items: [Preventive measures with owners and deadlines]')
  lessonsLearnedTemplate.push('7. IOCs Discovered: [New indicators to add to detection]')

  return {
    incident_id: incidentId,
    incident_type: input.incident_type,
    severity: input.severity,
    phases,
    containment_actions: containmentActions,
    eradication_steps: eradicationSteps,
    recovery_procedures: recoveryProcedures,
    communication_timeline: communicationTimeline,
    regulatory_notifications: regulatoryNotifications,
    estimated_total_recovery_hours: estimatedHours,
    lessons_learned_template: lessonsLearnedTemplate,
  }
}

function formatIRReport(r: IRResult): string {
  const lines: string[] = []
  lines.push('## Incident Response Orchestration Plan')
  lines.push('')
  lines.push(`**Incident ID:** ${r.incident_id} | **Type:** ${r.incident_type} | **Severity:** ${r.severity}`)
  lines.push(`**Estimated Total Recovery:** ${r.estimated_total_recovery_hours} hours`)
  lines.push('')
  lines.push('### Response Phases')
  for (const p of r.phases) {
    lines.push(`#### Phase ${p.order}: ${p.name} [${p.status.toUpperCase()}] -- Owner: ${p.owner} -- SLA: ${p.sla_minutes} min`)
    for (let i = 0; i < p.actions.length; i++) {
      lines.push(`  ${i + 1}. ${p.actions[i]}`)
    }
    if (p.dependencies.length > 0) lines.push(`  Dependencies: ${p.dependencies.join(', ')}`)
    lines.push('')
  }
  lines.push('### Containment Actions')
  for (const c of r.containment_actions) lines.push(`- ${c}`)
  lines.push('')
  lines.push('### Eradication Steps')
  for (const e of r.eradication_steps) lines.push(`- ${e}`)
  lines.push('')
  lines.push('### Recovery Procedures')
  for (const proc of r.recovery_procedures) lines.push(`- ${proc}`)
  lines.push('')
  lines.push('### Communication Timeline')
  for (const c of r.communication_timeline) lines.push(`- ${c}`)
  lines.push('')
  lines.push('### Regulatory Notifications')
  for (const n of r.regulatory_notifications) lines.push(`- ${n}`)
  lines.push('')
  lines.push('### Lessons Learned Template')
  for (const l of r.lessons_learned_template) lines.push(`- ${l}`)
  lines.push('')
  lines.push(`> **Disclaimer:** ${DISCLAIMER}`)
  return lines.join('\n')
}

/* ─────────────────────────────────────────────
   4. Security Orchestration Automator
   ───────────────────────────────────────────── */
export interface SOARInput {
  platform: string
  playbook_category: 'phishing_response' | 'malware_containment' | 'data_loss_prevention' | 'brute_force_response' | 'insider_threat' | 'vulnerability_response'
  automation_level: 'full_auto' | 'semi_auto' | 'human_in_loop'
  integrations: string[]
  trigger_conditions: string[]
}

export interface SOARAction {
  step: number
  action: string
  tool: string
  automated: boolean
  input_params: string[]
  output_handlers: string[]
  error_handling: string
  timeout_seconds: number
}

export interface SOARResult {
  playbook_id: string
  playbook_name: string
  category: string
  automation_level: string
  total_steps: number
  automated_steps: number
  manual_steps: number
  actions: SOARAction[]
  integration_map: string[]
  escalation_rules: string[]
  metrics: Record<string, string>
  deployment_notes: string[]
}

function automateSOAR(input: SOARInput): SOARResult {
  const rng = createRngFromInput(input)
  const playbookId = `SOAR-${randInt(rng, 1000, 9999)}`

  const playbookTemplates: Record<string, { name: string; actions: Array<{ action: string; tool: string; auto: boolean }> }> = {
    phishing_response: {
      name: 'Automated Phishing Response Playbook',
      actions: [
        { action: 'Parse email headers and extract IOCs', tool: 'Email Gateway', auto: true },
        { action: 'Query sender reputation across threat intel platforms', tool: 'Threat Intel Platform', auto: true },
        { action: 'Sandbox URL and attachment analysis', tool: 'Sandbox (Cuckoo/Any.Run)', auto: true },
        { action: 'Search mail logs for similar emails across organization', tool: 'SIEM (Splunk/Elastic)', auto: true },
        { action: 'Quarantine matching emails from all mailboxes', tool: 'Email Gateway', auto: true },
        { action: 'Block sender domain and IP at perimeter', tool: 'Firewall/Proxy', auto: input.automation_level !== 'human_in_loop' },
        { action: 'Notify affected users and security team', tool: 'Notification Service', auto: true },
        { action: 'Create incident ticket with full context', tool: 'ITSM (ServiceNow/Jira)', auto: true },
        { action: 'Update threat intelligence with new IOCs', tool: 'TIP (MISP/OpenCTI)', auto: true },
        { action: 'Executive summary for security leadership', tool: 'Reporting Engine', auto: false },
      ],
    },
    malware_containment: {
      name: 'Malware Containment and Eradication Playbook',
      actions: [
        { action: 'Isolate infected endpoint from network', tool: 'EDR (CrowdStrike/SentinelOne)', auto: input.automation_level === 'full_auto' },
        { action: 'Capture forensic memory dump', tool: 'EDR Forensics', auto: true },
        { action: 'Identify malware family and behavior', tool: 'Sandbox Analysis', auto: true },
        { action: 'Extract IOCs (file hashes, C2 domains, IPs)', tool: 'Malware Analysis', auto: true },
        { action: 'Hunt for same IOCs across all endpoints', tool: 'EDR/XDR', auto: true },
        { action: 'Block C2 communication at firewall/DNS', tool: 'Firewall/DNS Filter', auto: input.automation_level !== 'human_in_loop' },
        { action: 'Deploy custom detection rules to SIEM', tool: 'SIEM', auto: true },
        { action: 'Initiate full scan on adjacent systems', tool: 'EDR', auto: true },
        { action: 'Escalate to IR team if lateral movement detected', tool: 'Ticketing System', auto: true },
        { action: 'Document malware TTPs for threat intel', tool: 'Threat Intel Platform', auto: false },
      ],
    },
    data_loss_prevention: {
      name: 'Data Loss Prevention Response Playbook',
      actions: [
        { action: 'Identify data classification of exposed content', tool: 'DLP Engine', auto: true },
        { action: 'Determine scope of data exposure', tool: 'DLP/SIEM', auto: true },
        { action: 'Block data transfer channel immediately', tool: 'CASB/DLP Gateway', auto: input.automation_level === 'full_auto' },
        { action: 'Revoke access for compromised account', tool: 'IAM/PAM', auto: input.automation_level !== 'human_in_loop' },
        { action: 'Capture forensic evidence of data access', tool: 'SIEM/Log Analytics', auto: true },
        { action: 'Assess regulatory notification requirements', tool: 'Compliance Engine', auto: false },
        { action: 'Notify data protection officer', tool: 'Notification Service', auto: true },
        { action: 'Initiate data breach assessment workflow', tool: 'GRC Platform', auto: false },
        { action: 'Document incident for compliance reporting', tool: 'GRC Platform', auto: true },
        { action: 'Update DLP policies to prevent recurrence', tool: 'DLP Engine', auto: false },
      ],
    },
    brute_force_response: {
      name: 'Brute Force Attack Response Playbook',
      actions: [
        { action: 'Identify source IPs and attack pattern', tool: 'SIEM', auto: true },
        { action: 'Correlate with threat intelligence feeds', tool: 'TIP', auto: true },
        { action: 'Block attacking IPs at WAF/firewall', tool: 'WAF/Firewall', auto: input.automation_level !== 'human_in_loop' },
        { action: 'Lock targeted accounts after threshold', tool: 'IAM', auto: true },
        { action: 'Force password reset for targeted accounts', tool: 'IAM', auto: input.automation_level === 'full_auto' },
        { action: 'Enable CAPTCHA on authentication endpoints', tool: 'WAF', auto: true },
        { action: 'Deploy rate limiting rules', tool: 'API Gateway/WAF', auto: true },
        { action: 'Notify affected users of account protection', tool: 'Notification Service', auto: true },
        { action: 'Create incident with attack timeline', tool: 'ITSM', auto: true },
        { action: 'Recommend MFA enforcement for targeted accounts', tool: 'IAM', auto: false },
      ],
    },
    insider_threat: {
      name: 'Insider Threat Detection and Response Playbook',
      actions: [
        { action: 'Correlate UEBA alerts with access logs', tool: 'UEBA/SIEM', auto: true },
        { action: 'Identify data access anomalies', tool: 'DLP/UEBA', auto: true },
        { action: 'Review user activity for past 30 days', tool: 'SIEM', auto: true },
        { action: 'Flag user account for enhanced monitoring', tool: 'IAM/UEBA', auto: true },
        { action: 'Alert HR and legal (sensitive - human review)', tool: 'Notification Service', auto: false },
        { action: 'Restrict data access pending investigation', tool: 'IAM', auto: false },
        { action: 'Capture forensic evidence (legal hold)', tool: 'Forensics Platform', auto: false },
        { action: 'Coordinate with legal for investigation', tool: 'Case Management', auto: false },
        { action: 'Document chain of custody for evidence', tool: 'GRC Platform', auto: true },
        { action: 'Update insider threat detection models', tool: 'UEBA', auto: false },
      ],
    },
    vulnerability_response: {
      name: 'Critical Vulnerability Response Playbook',
      actions: [
        { action: 'Correlate vulnerability scan with asset inventory', tool: 'VM Platform (Tenable/Qualys)', auto: true },
        { action: 'Check for active exploitation in environment', tool: 'SIEM/EDR', auto: true },
        { action: 'Query threat intel for in-the-wild exploitation', tool: 'TIP', auto: true },
        { action: 'Prioritize by asset criticality and exposure', tool: 'VM Platform', auto: true },
        { action: 'Deploy emergency patch to critical assets', tool: 'Patch Management', auto: input.automation_level === 'full_auto' },
        { action: 'Apply virtual patching via WAF/IPS', tool: 'WAF/IPS', auto: input.automation_level !== 'human_in_loop' },
        { action: 'Verify patch deployment success', tool: 'VM Platform', auto: true },
        { action: 'Update vulnerability metrics and SLAs', tool: 'GRC Platform', auto: true },
        { action: 'Escalate unpatched critical vulnerabilities', tool: 'Ticketing System', auto: true },
        { action: 'Generate vulnerability remediation report', tool: 'Reporting Engine', auto: true },
      ],
    },
  }

  const template = playbookTemplates[input.playbook_category] || playbookTemplates.phishing_response
  const isSemiAuto = input.automation_level === 'semi_auto'
  const isHumanInLoop = input.automation_level === 'human_in_loop'

  const actions: SOARAction[] = []
  for (let i = 0; i < template.actions.length; i++) {
    const a = template.actions[i]
    const automated = isHumanInLoop ? false : isSemiAuto ? a.auto && rng() > 0.3 : a.auto

    actions.push({
      step: i + 1,
      action: a.action,
      tool: a.tool,
      automated,
      input_params: [`param_${i}_input`, `param_${i}_config`],
      output_handlers: [`handler_${i}_success`, `handler_${i}_failure`],
      error_handling: automated ? 'Auto-retry (3x) then escalate to analyst' : 'Pause and notify assigned analyst',
      timeout_seconds: randInt(rng, 30, 300),
    })
  }

  const automatedCount = actions.filter(a => a.automated).length
  const manualCount = actions.filter(a => !a.automated).length

  const integrations = input.integrations.length > 0
    ? input.integrations
    : ['SIEM (Splunk)', 'EDR (CrowdStrike)', 'SOAR (Palo Alto XSOAR)', 'Ticketing (ServiceNow)', 'Email Gateway', 'Firewall', 'IAM', 'Threat Intel Platform']

  const escalationRules: string[] = []
  escalationRules.push('Escalate to L2 if automated action fails after 3 retries')
  escalationRules.push('Escalate to IR team if lateral movement or data exfiltration detected')
  escalationRules.push('Escalate to CISO if P1 incident or regulatory notification required')
  escalationRules.push('Auto-close ticket if all actions complete successfully and verified')
  escalationRules.push('SLA breach: Notify manager if playbook exceeds expected runtime by 50%')

  const metrics: Record<string, string> = {
    'Mean Time to Detect (MTTD)': `${randInt(rng, 5, 30)} minutes`,
    'Mean Time to Respond (MTTR)': `${randInt(rng, 15, 120)} minutes`,
    'Mean Time to Contain (MTTC)': `${randInt(rng, 30, 240)} minutes`,
    'Automation Rate': `${Math.round((automatedCount / actions.length) * 100)}%`,
    'Playbook Success Rate': `${randInt(rng, 85, 98)}%`,
    'False Positive Rate': `${Math.round(rng() * 8)}%`,
  }

  const deploymentNotes: string[] = []
  deploymentNotes.push(`Deploy in test environment first with ${actions.length} step validation`)
  deploymentNotes.push('Configure rollback procedures for each automated action')
  deploymentNotes.push('Set up monitoring dashboards for playbook execution metrics')
  deploymentNotes.push('Schedule quarterly playbook review and update cycle')
  deploymentNotes.push('Ensure all integrations have API rate limit handling')

  return {
    playbook_id: playbookId,
    playbook_name: template.name,
    category: input.playbook_category,
    automation_level: input.automation_level,
    total_steps: actions.length,
    automated_steps: automatedCount,
    manual_steps: manualCount,
    actions,
    integration_map: integrations,
    escalation_rules: escalationRules,
    metrics,
    deployment_notes: deploymentNotes,
  }
}

function formatSOARReport(r: SOARResult): string {
  const lines: string[] = []
  lines.push('## Security Orchestration Automation Playbook')
  lines.push('')
  lines.push(`**Playbook ID:** ${r.playbook_id} | **Name:** ${r.playbook_name}`)
  lines.push(`**Category:** ${r.category} | **Automation Level:** ${r.automation_level}`)
  lines.push(`**Steps:** ${r.total_steps} total | ${r.automated_steps} automated | ${r.manual_steps} manual`)
  lines.push('')
  lines.push('### Playbook Steps')
  lines.push('| Step | Action | Tool | Auto | Timeout |')
  lines.push('|------|--------|------|------|---------|')
  for (const a of r.actions) {
    lines.push(`| ${a.step} | ${a.action} | ${a.tool} | ${a.automated ? 'Yes' : 'No'} | ${a.timeout_seconds}s |`)
  }
  lines.push('')
  lines.push('### Integration Map')
  for (const i of r.integration_map) lines.push(`- ${i}`)
  lines.push('')
  lines.push('### Escalation Rules')
  for (const e of r.escalation_rules) lines.push(`- ${e}`)
  lines.push('')
  lines.push('### Metrics')
  for (const [k, v] of Object.entries(r.metrics)) lines.push(`- **${k}:** ${v}`)
  lines.push('')
  lines.push('### Deployment Notes')
  for (const d of r.deployment_notes) lines.push(`- ${d}`)
  lines.push('')
  lines.push(`> **Disclaimer:** ${DISCLAIMER}`)
  return lines.join('\n')
}

/* ─────────────────────────────────────────────
   5. Attack Surface Mapper
   ───────────────────────────────────────────── */
export interface AttackSurfaceInput {
  organization: string
  domains: string[]
  ip_ranges: string[]
  cloud_providers: string[]
  include_third_party: boolean
  scan_type: 'external' | 'internal' | 'both'
}

export interface SurfaceAsset {
  name: string
  type: string
  exposure: 'internet_facing' | 'internal' | 'partner_access'
  technologies: string[]
  vulnerabilities_count: number
  risk_score: number
  owner: string
  last_assessed: string
}

export interface AttackVector {
  name: string
  category: string
  likelihood: 'High' | 'Medium' | 'Low'
  impact: 'Critical' | 'High' | 'Medium' | 'Low'
  attack_complexity: 'Low' | 'Medium' | 'High'
  mitre_technique: string
  description: string
}

export interface AttackSurfaceResult {
  mapping_id: string
  organization: string
  scan_type: string
  total_assets_discovered: number
  internet_facing_count: number
  assets: SurfaceAsset[]
  attack_vectors: AttackVector[]
  exposure_summary: Record<string, number>
  recommendations: string[]
  risk_heatmap: string[]
}

function mapAttackSurface(input: AttackSurfaceInput): AttackSurfaceResult {
  const rng = createRngFromInput(input)
  const mappingId = `ASM-${randInt(rng, 10000, 99999)}`

  const assetTypes = ['Web Application', 'API Gateway', 'Cloud Storage', 'Database', 'Load Balancer', 'CDN Endpoint', 'DNS Server', 'Mail Server', 'VPN Gateway', 'Container Registry', 'Serverless Function', 'Message Queue', 'CI/CD Pipeline', 'Monitoring Dashboard', 'Admin Panel']
  const technologies = ['React', 'Node.js', 'Python/Django', 'Java/Spring', 'PostgreSQL', 'MongoDB', 'Redis', 'Kubernetes', 'Docker', 'AWS S3', 'Azure AD', 'NGINX', 'Apache', 'GraphQL', 'REST API', 'gRPC', 'OAuth2', 'JWT', 'Terraform', 'Ansible']
  const exposures: SurfaceAsset['exposure'][] = ['internet_facing', 'internal', 'partner_access']

  const assetCount = randInt(rng, 12, 30)
  const assets: SurfaceAsset[] = []
  for (let i = 0; i < assetCount; i++) {
    const type = pick(rng, assetTypes)
    const exposure = pick(rng, exposures)
    const vulnCount = exposure === 'internet_facing' ? randInt(rng, 1, 8) : randInt(rng, 0, 4)
    const riskBase = exposure === 'internet_facing' ? 60 : exposure === 'partner_access' ? 40 : 20

    assets.push({
      name: `${type.toLowerCase().replace(/ /g, '-')}-${randInt(rng, 1, 99)}`,
      type,
      exposure,
      technologies: pickN(rng, technologies, randInt(rng, 2, 5)),
      vulnerabilities_count: vulnCount,
      risk_score: Math.min(100, riskBase + vulnCount * randInt(rng, 3, 8) + randInt(rng, 0, 20)),
      owner: `team-${pick(rng, ['platform', 'backend', 'frontend', 'data', 'infra', 'security', 'devops'])}`,
      last_assessed: `2025-${String(randInt(rng, 6, 12)).padStart(2, '0')}-${String(randInt(rng, 1, 28)).padStart(2, '0')}`,
    })
  }

  const attackVectors: AttackVector[] = [
    { name: 'Phishing via lookalike domain', category: 'Social Engineering', likelihood: 'High', impact: 'Critical', attack_complexity: 'Low', mitre_technique: 'T1566', description: 'Register similar domain and send targeted phishing emails to employees' },
    { name: 'API key exposure in public repo', category: 'Credential Exposure', likelihood: 'High', impact: 'High', attack_complexity: 'Low', mitre_technique: 'T1552.001', description: 'Scan public code repositories for leaked API keys and credentials' },
    { name: 'Subdomain takeover via dangling DNS', category: 'Infrastructure', likelihood: 'Medium', impact: 'High', attack_complexity: 'Medium', mitre_technique: 'T1584.001', description: 'Identify DNS records pointing to deprovisioned cloud resources' },
    { name: 'SSRF via cloud metadata endpoint', category: 'Cloud Exploitation', likelihood: 'Medium', impact: 'Critical', attack_complexity: 'Medium', mitre_technique: 'T1552.005', description: 'Exploit SSRF to access cloud instance metadata and temporary credentials' },
    { name: 'Supply chain via compromised dependency', category: 'Supply Chain', likelihood: 'Medium', impact: 'Critical', attack_complexity: 'High', mitre_technique: 'T1195.001', description: 'Compromise upstream software dependency to inject malicious code' },
    { name: 'Credential stuffing with breached passwords', category: 'Authentication', likelihood: 'High', impact: 'High', attack_complexity: 'Low', mitre_technique: 'T1110.004', description: 'Use credentials from previous breaches to access user accounts' },
    { name: 'Cloud storage misconfiguration', category: 'Cloud Exploitation', likelihood: 'High', impact: 'High', attack_complexity: 'Low', mitre_technique: 'T1530', description: 'Access publicly exposed cloud storage buckets containing sensitive data' },
    { name: 'Zero-day in edge service', category: 'Exploitation', likelihood: 'Low', impact: 'Critical', attack_complexity: 'High', mitre_technique: 'T1190', description: 'Exploit unknown vulnerability in internet-facing edge service' },
    { name: 'Watering hole via industry portal', category: 'Social Engineering', likelihood: 'Low', impact: 'High', attack_complexity: 'High', mitre_technique: 'T1189', description: 'Compromise frequently visited industry website to target employees' },
    { name: 'Insider threat via excessive permissions', category: 'Insider', likelihood: 'Medium', impact: 'High', attack_complexity: 'Low', mitre_technique: 'T1078', description: 'Abuse over-privileged access to exfiltrate sensitive data' },
  ]

  const exposureSummary: Record<string, number> = {
    internet_facing: assets.filter(a => a.exposure === 'internet_facing').length,
    internal: assets.filter(a => a.exposure === 'internal').length,
    partner_access: assets.filter(a => a.exposure === 'partner_access').length,
    total_vulnerabilities: assets.reduce((s, a) => s + a.vulnerabilities_count, 0),
    high_risk_assets: assets.filter(a => a.risk_score >= 70).length,
  }

  const recommendations: string[] = []
  const internetFacing = assets.filter(a => a.exposure === 'internet_facing')
  if (internetFacing.length > 5) {
    recommendations.push(`Reduce attack surface: ${internetFacing.length} internet-facing assets detected - consolidate where possible`)
  }
  recommendations.push(`Prioritize remediation for ${exposureSummary.high_risk_assets} high-risk assets (score >= 70)`)
  recommendations.push('Implement continuous attack surface monitoring with weekly discovery scans')
  recommendations.push('Deploy subdomain takeover prevention with automated DNS monitoring')
  recommendations.push('Enforce secrets scanning in all CI/CD pipelines')
  recommendations.push('Implement cloud security posture management (CSPM) for all cloud providers')
  if (input.include_third_party) {
    recommendations.push('Conduct third-party risk assessment for all vendor integrations')
  }

  const riskHeatmap: string[] = []
  riskHeatmap.push(`Critical Risk: ${assets.filter(a => a.risk_score >= 80).length} assets require immediate attention`)
  riskHeatmap.push(`High Risk: ${assets.filter(a => a.risk_score >= 60 && a.risk_score < 80).length} assets need remediation within 30 days`)
  riskHeatmap.push(`Medium Risk: ${assets.filter(a => a.risk_score >= 40 && a.risk_score < 60).length} assets scheduled for standard patching`)
  riskHeatmap.push(`Low Risk: ${assets.filter(a => a.risk_score < 40).length} assets within acceptable risk threshold`)
  riskHeatmap.push(`Top Attack Vector: ${pick(rng, attackVectors).name} (Likelihood: ${pick(rng, attackVectors).likelihood}, Impact: ${pick(rng, attackVectors).impact})`)

  return {
    mapping_id: mappingId,
    organization: input.organization,
    scan_type: input.scan_type,
    total_assets_discovered: assets.length,
    internet_facing_count: exposureSummary.internet_facing,
    assets,
    attack_vectors: attackVectors,
    exposure_summary: exposureSummary,
    recommendations,
    risk_heatmap: riskHeatmap,
  }
}

function formatAttackSurfaceReport(r: AttackSurfaceResult): string {
  const lines: string[] = []
  lines.push('## Attack Surface Mapping Report')
  lines.push('')
  lines.push(`**Mapping ID:** ${r.mapping_id} | **Organization:** ${r.organization} | **Scan Type:** ${r.scan_type}`)
  lines.push(`**Total Assets:** ${r.total_assets_discovered} | **Internet-Facing:** ${r.internet_facing_count}`)
  lines.push('')
  lines.push('### Exposure Summary')
  for (const [k, v] of Object.entries(r.exposure_summary)) {
    lines.push(`- ${k.replace(/_/g, ' ').replace(/^\w/, c => c.toUpperCase())}: ${v}`)
  }
  lines.push('')
  lines.push('### Key Assets')
  lines.push('| Asset | Type | Exposure | Vulns | Risk | Owner |')
  lines.push('|-------|------|----------|-------|------|-------|')
  for (const a of r.assets.slice(0, 15)) {
    lines.push(`| ${a.name} | ${a.type} | ${a.exposure} | ${a.vulnerabilities_count} | ${a.risk_score} | ${a.owner} |`)
  }
  if (r.assets.length > 15) lines.push(`| ... and ${r.assets.length - 15} more assets | | | | | |`)
  lines.push('')
  lines.push('### Attack Vectors')
  lines.push('| Vector | Category | Likelihood | Impact | Complexity | MITRE |')
  lines.push('|--------|----------|------------|--------|------------|-------|')
  for (const v of r.attack_vectors) {
    lines.push(`| ${v.name} | ${v.category} | ${v.likelihood} | ${v.impact} | ${v.attack_complexity} | ${v.mitre_technique} |`)
  }
  lines.push('')
  lines.push('### Risk Heatmap')
  for (const h of r.risk_heatmap) lines.push(`- ${h}`)
  lines.push('')
  lines.push('### Recommendations')
  for (const rec of r.recommendations) lines.push(`- [ ] ${rec}`)
  lines.push('')
  lines.push(`> **Disclaimer:** ${DISCLAIMER}`)
  return lines.join('\n')
}

/* ─────────────────────────────────────────────
   6. Malware Behavior Analyst
   ───────────────────────────────────────────── */
export interface MalwareAnalysisInput {
  sample_type: 'ransomware' | 'trojan' | 'worm' | 'rootkit' | 'spyware' | 'adware' | 'cryptominer' | 'wiper' | 'fileless' | 'polymorphic'
  analysis_depth: 'static' | 'dynamic' | 'full'
  environment: 'sandbox' | 'production_isolated' | 'air_gapped'
  indicators?: string[]
}

export interface MalwareBehavior {
  category: string
  action: string
  severity: 'Critical' | 'High' | 'Medium' | 'Low'
  mitre_technique: string
  description: string
}

export interface MalwareNetworkActivity {
  protocol: string
  destination: string
  port: number
  purpose: string
  encrypted: boolean
}

export interface MalwareAnalysisResult {
  analysis_id: string
  sample_type: string
  analysis_depth: string
  threat_level: 'Critical' | 'High' | 'Medium' | 'Low'
  behaviors: MalwareBehavior[]
  network_activity: MalwareNetworkActivity[]
  persistence_mechanisms: string[]
  indicators_of_compromise: string[]
  yara_rules: string[]
  sigma_rules: string[]
  remediation_steps: string[]
  similarity_score: number
}

function analyzeMalwareBehavior(input: MalwareAnalysisInput): MalwareAnalysisResult {
  const rng = createRngFromInput(input)
  const analysisId = `MAL-${randInt(rng, 10000, 99999)}`

  const behaviorTemplates: Record<string, MalwareBehavior[]> = {
    ransomware: [
      { category: 'Encryption', action: 'Mass file encryption via AES-256 + RSA', severity: 'Critical', mitre_technique: 'T1486', description: 'Encrypts all accessible files with hybrid encryption scheme' },
      { category: 'Persistence', action: 'Registry Run key modification', severity: 'High', mitre_technique: 'T1547.001', description: 'Adds persistence via HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run' },
      { category: 'Defense Evasion', action: 'Delete Volume Shadow Copies', severity: 'High', mitre_technique: 'T1490', description: 'Executes vssadmin delete shadows /all /quiet to prevent recovery' },
      { category: 'Discovery', action: 'Network share enumeration', severity: 'Medium', mitre_technique: 'T1135', description: 'Scans for accessible network shares to maximize encryption scope' },
      { category: 'Impact', action: 'Ransom note deployment', severity: 'High', mitre_technique: 'T1489', description: 'Drops ransom note (README_DECRYPT.txt) in each encrypted directory' },
    ],
    trojan: [
      { category: 'Execution', action: 'DLL side-loading via legitimate binary', severity: 'High', mitre_technique: 'T1574.002', description: 'Loads malicious DLL through legitimate signed application' },
      { category: 'Credential Access', action: 'Keylogging and clipboard capture', severity: 'Critical', mitre_technique: 'T1056.001', description: 'Captures keystrokes and clipboard data for credential theft' },
      { category: 'Collection', action: 'Screenshot capture at intervals', severity: 'Medium', mitre_technique: 'T1113', description: 'Captures screen content every 60 seconds' },
      { category: 'C2', action: 'HTTPS beacon to command server', severity: 'High', mitre_technique: 'T1071.001', description: 'Periodic HTTPS callbacks to C2 infrastructure' },
      { category: 'Exfiltration', action: 'Data staging and compressed upload', severity: 'Critical', mitre_technique: 'T1048', description: 'Compresses and exfiltrates collected data via HTTPS' },
    ],
    worm: [
      { category: 'Lateral Movement', action: 'SMB vulnerability exploitation', severity: 'Critical', mitre_technique: 'T1210', description: 'Exploits EternalBlue (MS17-010) for network propagation' },
      { category: 'Execution', action: 'Remote service creation via SMB', severity: 'Critical', mitre_technique: 'T1021.002', description: 'Creates remote service on vulnerable systems for execution' },
      { category: 'Discovery', action: 'Network scanning for open ports', severity: 'Medium', mitre_technique: 'T1046', description: 'Scans subnet for systems with open SMB (445) ports' },
      { category: 'Propagation', action: 'Self-replication to discovered hosts', severity: 'Critical', mitre_technique: 'T1080', description: 'Copies itself to all accessible network shares' },
    ],
    rootkit: [
      { category: 'Privilege Escalation', action: 'Kernel driver exploitation', severity: 'Critical', mitre_technique: 'T1068', description: 'Exploits vulnerable kernel driver for ring-0 access' },
      { category: 'Defense Evasion', action: 'DKOM (Direct Kernel Object Manipulation)', severity: 'Critical', mitre_technique: 'T1014', description: 'Modifies kernel structures to hide processes and files' },
      { category: 'Persistence', action: 'Bootkit installation in MBR/VBR', severity: 'Critical', mitre_technique: 'T1542.001', description: 'Installs boot-level persistence in Master Boot Record' },
      { category: 'Collection', action: 'Kernel-level network sniffing', severity: 'High', mitre_technique: 'T1040', description: 'Captures network traffic at kernel level for credential harvesting' },
    ],
    spyware: [
      { category: 'Collection', action: 'Browser history and cookie theft', severity: 'High', mitre_technique: 'T1217', description: 'Extracts browsing history and session cookies from all browsers' },
      { category: 'Collection', action: 'Microphone and camera activation', severity: 'Critical', mitre_technique: 'T1125', description: 'Activates recording devices without user knowledge' },
      { category: 'Collection', action: 'GPS location tracking', severity: 'Medium', mitre_technique: 'T1592', description: 'Tracks device location via GPS/WiFi triangulation' },
      { category: 'Exfiltration', action: 'Encrypted data upload to C2', severity: 'High', mitre_technique: 'T1041', description: 'Periodically uploads collected surveillance data' },
    ],
    cryptominer: [
      { category: 'Execution', action: 'XMRig miner process injection', severity: 'High', mitre_technique: 'T1055', description: 'Injects cryptocurrency mining code into legitimate process' },
      { category: 'Resource Hijacking', action: 'GPU/CPU utilization maximization', severity: 'High', mitre_technique: 'T1496', description: 'Consumes 90%+ of available compute resources for mining' },
      { category: 'Defense Evasion', action: 'Process name masquerading', severity: 'Medium', mitre_technique: 'T1036', description: 'Disguises miner as svchost.exe or other system process' },
      { category: 'Persistence', action: 'Scheduled task for miner restart', severity: 'Medium', mitre_technique: 'T1053.005', description: 'Creates scheduled task to restart miner if terminated' },
    ],
    wiper: [
      { category: 'Impact', action: 'Master Boot Record overwrite', severity: 'Critical', mitre_technique: 'T1485', description: 'Overwrites MBR/VBR rendering system unbootable' },
      { category: 'Impact', action: 'Mass file corruption', severity: 'Critical', mitre_technique: 'T1485', description: 'Corrupts file headers across all accessible storage' },
      { category: 'Impact', action: 'Firmware overwrite attempt', severity: 'Critical', mitre_technique: 'T1495', description: 'Attempts to corrupt UEFI/BIOS firmware' },
      { category: 'Defense Evasion', action: 'Log deletion and timestamp manipulation', severity: 'High', mitre_technique: 'T1070', description: 'Removes evidence by clearing event logs and timestomping' },
    ],
    fileless: [
      { category: 'Execution', action: 'PowerShell in-memory execution', severity: 'Critical', mitre_technique: 'T1059.001', description: 'Executes payload entirely in PowerShell memory space' },
      { category: 'Persistence', action: 'WMI event subscription', severity: 'High', mitre_technique: 'T1546.003', description: 'Uses WMI permanent event subscription for persistence' },
      { category: 'Defense Evasion', action: 'AMSI bypass via memory patching', severity: 'High', mitre_technique: 'T1562.001', description: 'Patches AMSI DLL in memory to disable script scanning' },
      { category: 'Privilege Escalation', action: 'Token impersonation', severity: 'High', mitre_technique: 'T1134', description: 'Impersonates SYSTEM token for privilege escalation' },
    ],
    polymorphic: [
      { category: 'Defense Evasion', action: 'Code mutation on each execution', severity: 'Critical', mitre_technique: 'T1027', description: 'Rewrites own code structure to evade signature detection' },
      { category: 'Defense Evasion', action: 'Encrypted payload with variable key', severity: 'High', mitre_technique: 'T1027.002', description: 'Uses different encryption key for each infection' },
      { category: 'Execution', action: 'Runtime code generation', severity: 'High', mitre_technique: 'T1059', description: 'Generates executable code at runtime to avoid static analysis' },
      { category: 'Anti-Analysis', action: 'VM/sandbox detection and evasion', severity: 'High', mitre_technique: 'T1497', description: 'Detects analysis environment and alters behavior' },
    ],
    adware: [
      { category: 'Execution', action: 'Browser extension injection', severity: 'Medium', mitre_technique: 'T1176', description: 'Installs browser extension for ad injection' },
      { category: 'Collection', action: 'Browsing behavior tracking', severity: 'Medium', mitre_technique: 'T1217', description: 'Monitors and reports browsing habits to ad network' },
      { category: 'Defense Evasion', action: 'Extension hiding and protection', severity: 'Low', mitre_technique: 'T1564', description: 'Hides extension from browser management page' },
    ],
  }

  const behaviors = behaviorTemplates[input.sample_type] || behaviorTemplates.trojan

  const networkProtocols = ['HTTPS', 'DNS', 'HTTP', 'TCP', 'ICMP', 'SMTP', 'WebSocket', 'gRPC']
  const networkPurposes = ['C2 Beacon', 'Data Exfiltration', 'Payload Download', 'DNS Tunneling', 'Certificate Validation', 'NTP Sync', 'Proxy Check']
  const networkActivity: MalwareNetworkActivity[] = []
  for (let i = 0; i < randInt(rng, 3, 7); i++) {
    networkActivity.push({
      protocol: pick(rng, networkProtocols),
      destination: `${pick(rng, ['c2', 'update', 'cdn', 'api', 'dns'])}-${randInt(rng, 100, 999)}.${pick(rng, ['xyz', 'top', 'club', 'online', 'site', 'info'])}`,
      port: pick(rng, [443, 80, 53, 8080, 8443, 4443, 995, 22]),
      purpose: pick(rng, networkPurposes),
      encrypted: rng() > 0.3,
    })
  }

  const persistenceMechanisms: string[] = []
  persistenceMechanisms.push('Registry: HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run')
  persistenceMechanisms.push('Scheduled Task: Created hidden task for system startup')
  persistenceMechanisms.push('WMI Event Subscription: Permanent event filter for boot execution')
  if (rng() > 0.5) persistenceMechanisms.push('Service Creation: Registered as auto-start service')
  if (rng() > 0.6) persistenceMechanisms.push('DLL Search Order Hijacking: Placed in application directory')

  const iocs: string[] = []
  iocs.push(`File Hash (SHA256): ${Array.from({ length: 64 }, () => '0123456789abcdef'[randInt(rng, 0, 15)]).join('')}`)
  iocs.push(`Mutex: Global\\MalMutex_${randInt(rng, 100000, 999999)}`)
  iocs.push(`Registry Key: HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\\Update${randInt(rng, 1, 99)}`)
  iocs.push(`C2 Domain: c2-${randInt(rng, 100, 999)}.${pick(rng, ['xyz', 'top', 'club', 'online'])}`)
  iocs.push(`User-Agent: Mozilla/5.0 MalAgent/${randInt(rng, 1, 9)}.${randInt(rng, 0, 9)}.${randInt(rng, 0, 9999)}`)

  const yaraRules: string[] = []
  yaraRules.push(`rule ${input.sample_type}_sample_${randInt(rng, 100, 999)} { condition: uint16(0) == 0x5A4D and filesize < ${randInt(rng, 1, 10)}MB }`)
  yaraRules.push(`rule ${input.sample_type}_strings { strings: $a = "${pick(rng, ['cmd.exe', 'powershell', 'rundll32', 'regsvr32', 'mshta'])}" nocase wide ascii condition: $a }`)

  const sigmaRules: string[] = []
  sigmaRules.push(`title: ${input.sample_type} Execution Detection`)
  sigmaRules.push(`logsource: category: process_creation`)
  sigmaRules.push(`detection: selection: CommandLine|contains: ['${pick(rng, ['-enc', '-nop', '-w hidden', 'IEX', 'DownloadString'])}']`)

  const remediationSteps: string[] = []
  remediationSteps.push('Isolate infected systems from network immediately')
  remediationSteps.push('Block identified C2 domains and IPs at perimeter')
  remediationSteps.push('Deploy IOCs to EDR/SIEM for environment-wide detection')
  remediationSteps.push('Scan all systems for identified file hashes and behavioral indicators')
  remediationSteps.push('Remove persistence mechanisms (registry keys, scheduled tasks, WMI)')
  remediationSteps.push('Restore affected files from clean backup (if ransomware, do NOT pay)')
  remediationSteps.push('Conduct full forensic investigation to determine initial access vector')
  remediationSteps.push('Update detection rules and threat intelligence with new IOCs')

  const threatLevel: MalwareAnalysisResult['threat_level'] = behaviors.some(b => b.severity === 'Critical') ? 'Critical' : behaviors.some(b => b.severity === 'High') ? 'High' : 'Medium'

  return {
    analysis_id: analysisId,
    sample_type: input.sample_type,
    analysis_depth: input.analysis_depth,
    threat_level: threatLevel,
    behaviors,
    network_activity: networkActivity,
    persistence_mechanisms: persistenceMechanisms,
    indicators_of_compromise: iocs,
    yara_rules: yaraRules,
    sigma_rules: sigmaRules,
    remediation_steps: remediationSteps,
    similarity_score: Math.round((0.6 + rng() * 0.4) * 100) / 100,
  }
}

function formatMalwareReport(r: MalwareAnalysisResult): string {
  const lines: string[] = []
  lines.push('## Malware Behavior Analysis Report')
  lines.push('')
  lines.push(`**Analysis ID:** ${r.analysis_id} | **Sample Type:** ${r.sample_type} | **Depth:** ${r.analysis_depth}`)
  lines.push(`**Threat Level:** ${r.threat_level} | **Similarity Score:** ${(r.similarity_score * 100).toFixed(0)}%`)
  lines.push('')
  lines.push('### Behavioral Analysis')
  lines.push('| Category | Action | Severity | MITRE |')
  lines.push('|----------|--------|----------|-------|')
  for (const b of r.behaviors) {
    lines.push(`| ${b.category} | ${b.action} | ${b.severity} | ${b.mitre_technique} |`)
  }
  lines.push('')
  lines.push('### Network Activity')
  lines.push('| Protocol | Destination | Port | Purpose | Encrypted |')
  lines.push('|----------|-------------|------|---------|-----------|')
  for (const n of r.network_activity) {
    lines.push(`| ${n.protocol} | ${n.destination} | ${n.port} | ${n.purpose} | ${n.encrypted ? 'Yes' : 'No'} |`)
  }
  lines.push('')
  lines.push('### Persistence Mechanisms')
  for (const p of r.persistence_mechanisms) lines.push(`- ${p}`)
  lines.push('')
  lines.push('### Indicators of Compromise')
  for (const i of r.indicators_of_compromise) lines.push(`- ${i}`)
  lines.push('')
  lines.push('### YARA Rules')
  for (const y of r.yara_rules) lines.push(`- ${y}`)
  lines.push('')
  lines.push('### SIGMA Rules')
  for (const s of r.sigma_rules) lines.push(`- ${s}`)
  lines.push('')
  lines.push('### Remediation Steps')
  for (const s of r.remediation_steps) lines.push(`- [ ] ${s}`)
  lines.push('')
  lines.push(`> **Disclaimer:** ${DISCLAIMER}`)
  return lines.join('\n')
}

/* ─────────────────────────────────────────────
   7. Security Posture Scorer
   ───────────────────────────────────────────── */
export interface PostureInput {
  organization: string
  industry: string
  employee_count: number
  security_team_size: number
  annual_security_budget_k: number
  frameworks: string[]
  maturity_baseline: 'initial' | 'developing' | 'defined' | 'managed' | 'optimizing'
}

export interface PostureDomain {
  name: string
  score: number
  max_score: number
  weight: number
  grade: string
  findings: string[]
  benchmarks: string[]
}

export interface PostureResult {
  assessment_id: string
  organization: string
  industry: string
  overall_score: number
  overall_grade: string
  maturity_level: string
  domains: PostureDomain[]
  industry_benchmark: string
  peer_comparison: string
  top_gaps: string[]
  investment_recommendations: string[]
  roadmap: string[]
}

function scoreSecurityPosture(input: PostureInput): PostureResult {
  const rng = createRngFromInput(input)
  const assessmentId = `SPA-${randInt(rng, 10000, 99999)}`

  const maturityBaseScores: Record<string, number> = {
    initial: 25,
    developing: 40,
    defined: 55,
    managed: 70,
    optimizing: 85,
  }
  const baseScore = maturityBaseScores[input.maturity_baseline] || 40

  const domainNames = [
    'Identity & Access Management',
    'Data Protection & Privacy',
    'Network Security',
    'Endpoint Security',
    'Cloud Security',
    'Application Security',
    'Security Operations & Monitoring',
    'Incident Response',
    'Vulnerability Management',
    'Governance, Risk & Compliance',
    'Security Awareness & Training',
    'Third-Party Risk Management',
    'Business Continuity & DR',
    'DevSecOps',
    'Threat Intelligence',
  ]

  const domains: PostureDomain[] = []
  for (const domainName of domainNames) {
    const variance = (rng() * 30) - 15
    const score = Math.max(10, Math.min(100, Math.round(baseScore + variance)))
    const weight = domainName.includes('Identity') || domainName.includes('Incident') ? 1.2 : 1.0

    let grade = 'F'
    if (score >= 90) grade = 'A'
    else if (score >= 80) grade = 'B+'
    else if (score >= 70) grade = 'B'
    else if (score >= 60) grade = 'C+'
    else if (score >= 50) grade = 'C'
    else if (score >= 40) grade = 'D'

    const findings: string[] = []
    if (score < 50) findings.push(`${domainName}: Significant gaps identified - below industry minimum`)
    else if (score < 70) findings.push(`${domainName}: Moderate maturity - improvement opportunities exist`)
    else findings.push(`${domainName}: Adequate controls in place - focus on optimization`)

    const benchmarks: string[] = []
    benchmarks.push(`Industry average for ${input.industry}: ${Math.round(score + (rng() * 10 - 5))}/100`)
    benchmarks.push(`Top quartile benchmark: ${Math.min(100, score + randInt(rng, 10, 25))}/100`)

    domains.push({ name: domainName, score, max_score: 100, weight, grade, findings, benchmarks })
  }

  const weightedTotal = domains.reduce((s, d) => s + d.score * d.weight, 0)
  const totalWeight = domains.reduce((s, d) => s + d.weight, 0)
  const overallScore = Math.round(weightedTotal / totalWeight)

  let overallGrade = 'F'
  if (overallScore >= 90) overallGrade = 'A'
  else if (overallScore >= 80) overallGrade = 'B+'
  else if (overallScore >= 70) overallGrade = 'B'
  else if (overallScore >= 60) overallGrade = 'C+'
  else if (overallScore >= 50) overallGrade = 'C'
  else if (overallScore >= 40) overallGrade = 'D'

  const maturityLevels = ['Initial (Level 1)', 'Developing (Level 2)', 'Defined (Level 3)', 'Managed (Level 4)', 'Optimizing (Level 5)']
  const overallMaturityIdx = overallScore >= 80 ? 4 : overallScore >= 65 ? 3 : overallScore >= 50 ? 2 : overallScore >= 35 ? 1 : 0

  const industryBenchmarks: Record<string, number> = {
    Finance: 72, Healthcare: 65, Technology: 70, Government: 68, Retail: 58, Manufacturing: 55, Energy: 67, Education: 50, Telecom: 66,
  }
  const industryAvg = industryBenchmarks[input.industry] || 60
  const benchmarkComparison = overallScore >= industryAvg
    ? `Above ${input.industry} industry average (${industryAvg}) by ${overallScore - industryAvg} points`
    : `Below ${input.industry} industry average (${industryAvg}) by ${industryAvg - overallScore} points`

  const peerComparison = input.employee_count > 1000
    ? `Enterprise peer group (${Math.round((overallScore / 100) * 100)}th percentile)`
    : `Mid-market peer group (${Math.round((overallScore / 100) * 100)}th percentile)`

  const sortedDomains = [...domains].sort((a, b) => a.score - b.score)
  const topGaps: string[] = []
  for (const d of sortedDomains.slice(0, 5)) {
    topGaps.push(`${d.name}: ${d.score}/100 (Grade ${d.grade}) - ${d.findings[0]}`)
  }

  const investmentRecommendations: string[] = []
  const lowestDomain = sortedDomains[0]
  investmentRecommendations.push(`Priority Investment: ${lowestDomain.name} (current: ${lowestDomain.score}/100) - Estimated budget: $${randInt(rng, 50, 300)}K`)
  investmentRecommendations.push(`Security team ratio: ${input.security_team_size}/${input.employee_count} (recommended: 1:${randInt(rng, 50, 100)})`)
  investmentRecommendations.push(`Budget allocation: $${input.annual_security_budget_k}K annually (industry benchmark: $${randInt(rng, 500, 2000)}K for ${input.employee_count} employees)`)
  investmentRecommendations.push('Consider managed security service provider (MSSP) for 24/7 SOC coverage')
  investmentRecommendations.push('Invest in security automation to reduce manual toil by 40-60%')

  const roadmap: string[] = []
  roadmap.push(`Phase 1 (0-90 days): Address ${sortedDomains.filter(d => d.score < 50).length} critical gap domains`)
  roadmap.push(`Phase 2 (90-180 days): Achieve ${maturityLevels[Math.min(overallMaturityIdx + 1, 4)]} maturity level`)
  roadmap.push(`Phase 3 (180-365 days): Target overall score of ${Math.min(95, overallScore + 15)}/100`)
  roadmap.push(`Phase 4 (12-18 months): Achieve ${input.frameworks.length > 0 ? input.frameworks[0].toUpperCase() : 'industry'} compliance certification`)
  roadmap.push('Ongoing: Quarterly posture assessments with continuous improvement cycle')

  return {
    assessment_id: assessmentId,
    organization: input.organization,
    industry: input.industry,
    overall_score: overallScore,
    overall_grade: overallGrade,
    maturity_level: maturityLevels[overallMaturityIdx],
    domains,
    industry_benchmark: benchmarkComparison,
    peer_comparison: peerComparison,
    top_gaps: topGaps,
    investment_recommendations: investmentRecommendations,
    roadmap,
  }
}

function formatPostureReport(r: PostureResult): string {
  const lines: string[] = []
  lines.push('## Security Posture Assessment Report')
  lines.push('')
  lines.push(`**Assessment ID:** ${r.assessment_id} | **Organization:** ${r.organization} | **Industry:** ${r.industry}`)
  lines.push(`**Overall Score:** ${r.overall_score}/100 | **Grade:** ${r.overall_grade} | **Maturity:** ${r.maturity_level}`)
  lines.push('')
  lines.push(`**Industry Benchmark:** ${r.industry_benchmark}`)
  lines.push(`**Peer Comparison:** ${r.peer_comparison}`)
  lines.push('')
  lines.push('### Domain Scores')
  lines.push('| Domain | Score | Grade | Weight |')
  lines.push('|--------|-------|-------|--------|')
  for (const d of r.domains) {
    const bar = '|'.repeat(Math.floor(d.score / 10)) + '.'.repeat(10 - Math.floor(d.score / 10))
    lines.push(`| ${d.name} | ${d.score}/100 ${bar} | ${d.grade} | ${d.weight.toFixed(1)}x |`)
  }
  lines.push('')
  lines.push('### Top Gaps')
  for (const g of r.top_gaps) lines.push(`- ${g}`)
  lines.push('')
  lines.push('### Investment Recommendations')
  for (const i of r.investment_recommendations) lines.push(`- ${i}`)
  lines.push('')
  lines.push('### Improvement Roadmap')
  for (const rd of r.roadmap) lines.push(`- ${rd}`)
  lines.push('')
  lines.push(`> **Disclaimer:** ${DISCLAIMER}`)
  return lines.join('\n')
}

/* ─────────────────────────────────────────────
   8. Zero Trust Architecture Advisor
   ───────────────────────────────────────────── */
export interface ZeroTrustInput {
  organization: string
  current_architecture: 'perimeter_based' | 'vpn_based' | 'hybrid' | 'cloud_native' | 'legacy'
  user_count: number
  device_count: number
  cloud_adoption: 'none' | 'partial' | 'majority' | 'full'
  compliance_requirements: string[]
  priority: 'identity' | 'device' | 'network' | 'application' | 'data' | 'all'
}

export interface ZTComponent {
  name: string
  category: string
  current_state: string
  target_state: string
  implementation_phase: 'Phase 1' | 'Phase 2' | 'Phase 3'
  complexity: 'Low' | 'Medium' | 'High'
  estimated_cost: string
  dependencies: string[]
}

export interface ZeroTrustResult {
  advisory_id: string
  organization: string
  current_architecture: string
  target_maturity: string
  components: ZTComponent[]
  implementation_roadmap: string[]
  principles_assessment: Record<string, string>
  quick_wins: string[]
  risk_mitigations: string[]
  compliance_mapping: string[]
  total_estimated_investment: string
}

function adviseZeroTrust(input: ZeroTrustInput): ZeroTrustResult {
  const rng = createRngFromInput(input)
  const advisoryId = `ZTA-${randInt(rng, 10000, 99999)}`

  const components: ZTComponent[] = [
    {
      name: 'Identity-Centric Security (ICAM)',
      category: 'Identity',
      current_state: input.current_architecture === 'perimeter_based' ? 'Perimeter-focused authentication' : 'Partial MFA deployment',
      target_state: 'Phishing-resistant MFA for all users, continuous authentication risk scoring',
      implementation_phase: 'Phase 1',
      complexity: 'Medium',
      estimated_cost: `$${randInt(rng, 100, 500)}K`,
      dependencies: ['Identity Provider (IdP) upgrade', 'User directory consolidation'],
    },
    {
      name: 'Device Trust & Endpoint Verification',
      category: 'Device',
      current_state: 'Basic endpoint management without trust scoring',
      target_state: 'Device health attestation, compliance-based access, EDR integration',
      implementation_phase: 'Phase 1',
      complexity: 'Medium',
      estimated_cost: `$${randInt(rng, 150, 600)}K`,
      dependencies: ['MDM/EDR deployment', 'Device certificate infrastructure'],
    },
    {
      name: 'Microsegmentation & Software-Defined Perimeter',
      category: 'Network',
      current_state: 'Flat network with VLAN-based segmentation',
      target_state: 'Identity-aware microsegmentation with per-workload policies',
      implementation_phase: 'Phase 2',
      complexity: 'High',
      estimated_cost: `$${randInt(rng, 300, 1200)}K`,
      dependencies: ['Network visibility tooling', 'Policy engine deployment', 'Application dependency mapping'],
    },
    {
      name: 'Application & Workload Security',
      category: 'Application',
      current_state: 'Application access via VPN or direct exposure',
      target_state: 'Zero trust application access with per-session authorization',
      implementation_phase: 'Phase 2',
      complexity: 'Medium',
      estimated_cost: `$${randInt(rng, 200, 800)}K`,
      dependencies: ['Identity proxy deployment', 'Application inventory'],
    },
    {
      name: 'Data Classification & Protection',
      category: 'Data',
      current_state: 'Basic DLP with manual classification',
      target_state: 'Automated data classification, encryption, and rights management',
      implementation_phase: 'Phase 2',
      complexity: 'High',
      estimated_cost: `$${randInt(rng, 250, 1000)}K`,
      dependencies: ['Data discovery and classification tooling', 'Encryption key management'],
    },
    {
      name: 'Analytics & Continuous Monitoring',
      category: 'Visibility',
      current_state: 'SIEM with limited behavioral analytics',
      target_state: 'Full UEBA with automated threat response and risk scoring',
      implementation_phase: 'Phase 3',
      complexity: 'High',
      estimated_cost: `$${randInt(rng, 200, 900)}K`,
      dependencies: ['Data lake for security analytics', 'SOAR platform integration'],
    },
    {
      name: 'Policy Engine & Orchestration',
      category: 'Governance',
      current_state: 'Manual policy management with static rules',
      target_state: 'Dynamic policy engine with real-time risk assessment and automated enforcement',
      implementation_phase: 'Phase 3',
      complexity: 'High',
      estimated_cost: `$${randInt(rng, 150, 700)}K`,
      dependencies: ['Policy decision point (PDP) deployment', 'Integration with all ZT components'],
    },
    {
      name: 'Secure Access Service Edge (SASE)',
      category: 'Network',
      current_state: 'Traditional VPN and MPLS connectivity',
      target_state: 'Cloud-delivered secure access with SD-WAN and SWG/CASB/ZTNA',
      implementation_phase: 'Phase 1',
      complexity: 'Medium',
      estimated_cost: `$${randInt(rng, 200, 800)}K`,
      dependencies: ['SASE vendor selection', 'Network architecture redesign'],
    },
  ]

  const implementationRoadmap: string[] = []
  implementationRoadmap.push('Phase 1 (0-6 months): Deploy identity-centric controls, device trust, and SASE foundation')
  implementationRoadmap.push('Phase 2 (6-12 months): Implement microsegmentation, application security, and data protection')
  implementationRoadmap.push('Phase 3 (12-18 months): Deploy analytics, policy engine, and full orchestration')
  implementationRoadmap.push('Phase 4 (18-24 months): Optimize, automate, and achieve full zero trust maturity')
  implementationRoadmap.push('Key Success Metric: Reduce lateral movement risk by 90% within 18 months')

  const principlesAssessment: Record<string, string> = {
    'Never Trust, Always Verify': input.current_architecture === 'perimeter_based' ? 'Not Implemented - perimeter trust model' : 'Partially Implemented',
    'Assume Breach': 'Partially Implemented - detection capabilities exist but response automation is limited',
    'Verify Explicitly': input.current_architecture === 'cloud_native' ? 'Well Implemented - identity-based access' : 'Needs Improvement - static access controls',
    'Least Privilege Access': 'Partially Implemented - RBAC exists but over-privileged accounts common',
    'Microsegmentation': 'Not Implemented - flat network architecture',
    'Continuous Monitoring': 'Partially Implemented - SIEM deployed but limited behavioral analytics',
  }

  const quickWins: string[] = []
  quickWins.push('Enable MFA for all privileged accounts (immediate, high impact)')
  quickWins.push('Implement conditional access policies based on device compliance')
  quickWins.push('Deploy cloud access security broker (CASB) for shadow IT visibility')
  quickWins.push('Enable just-in-time (JIT) access for administrative accounts')
  quickWins.push('Implement DNS-layer security to block C2 and phishing domains')
  quickWins.push('Deploy certificate-based authentication for device trust')

  const riskMitigations: string[] = []
  riskMitigations.push('Reduce blast radius: Microsegmentation limits lateral movement to single workload')
  riskMitigations.push('Prevent credential abuse: Phishing-resistant MFA blocks 99.9% of account compromise')
  riskMitigations.push('Improve visibility: Continuous monitoring detects threats in minutes vs. months')
  riskMitigations.push('Enable secure remote work: SASE replaces VPN with identity-aware access')
  riskMitigations.push('Data-centric protection: Classification and encryption protect data regardless of location')

  const complianceMapping: string[] = []
  for (const req of input.compliance_requirements) {
    if (req.toLowerCase().includes('nist')) complianceMapping.push('NIST SP 800-207: Zero Trust Architecture standard fully addressed')
    if (req.toLowerCase().includes('cis')) complianceMapping.push('CIS Controls: Implementation Groups 1-3 mapped to ZT components')
    if (req.toLowerCase().includes('soc2')) complianceMapping.push('SOC2: CC6.1, CC6.6, CC7.1 controls enhanced by ZT implementation')
    if (req.toLowerCase().includes('iso')) complianceMapping.push('ISO27001: A.9 (Access Control), A.13 (Communications Security) addressed')
    if (req.toLowerCase().includes('pci')) complianceMapping.push('PCI DSS: Req 1 (Firewall), Req 7 (Access), Req 8 (Identity) enhanced')
    if (req.toLowerCase().includes('hipaa')) complianceMapping.push('HIPAA: Technical safeguards for access control and transmission security addressed')
  }
  if (complianceMapping.length === 0) complianceMapping.push('General compliance: Zero trust architecture addresses common control frameworks')

  const totalMin = components.reduce((s, c) => {
    const match = c.estimated_cost.match(/\$(\d+)K/)
    return s + (match ? parseInt(match[1]) : 0)
  }, 0)
  const totalInvestment = `$${totalMin}K - $${Math.round(totalMin * 1.4)}K over 24 months`

  const targetMaturity = input.current_architecture === 'cloud_native' ? 'Advanced (Level 4)' : input.current_architecture === 'hybrid' ? 'Intermediate (Level 3)' : 'Developing (Level 2)'

  return {
    advisory_id: advisoryId,
    organization: input.organization,
    current_architecture: input.current_architecture,
    target_maturity: targetMaturity,
    components,
    implementation_roadmap: implementationRoadmap,
    principles_assessment: principlesAssessment,
    quick_wins: quickWins,
    risk_mitigations: riskMitigations,
    compliance_mapping: complianceMapping,
    total_estimated_investment: totalInvestment,
  }
}

function formatZeroTrustReport(r: ZeroTrustResult): string {
  const lines: string[] = []
  lines.push('## Zero Trust Architecture Advisory Report')
  lines.push('')
  lines.push(`**Advisory ID:** ${r.advisory_id} | **Organization:** ${r.organization}`)
  lines.push(`**Current Architecture:** ${r.current_architecture} | **Target Maturity:** ${r.target_maturity}`)
  lines.push(`**Estimated Investment:** ${r.total_estimated_investment}`)
  lines.push('')
  lines.push('### ZT Components')
  lines.push('| Component | Category | Phase | Complexity | Cost | Current State |')
  lines.push('|-----------|----------|-------|------------|------|---------------|')
  for (const c of r.components) {
    lines.push(`| ${c.name} | ${c.category} | ${c.implementation_phase} | ${c.complexity} | ${c.estimated_cost} | ${c.current_state.substring(0, 40)} |`)
  }
  lines.push('')
  lines.push('### Zero Trust Principles Assessment')
  for (const [k, v] of Object.entries(r.principles_assessment)) {
    lines.push(`- **${k}:** ${v}`)
  }
  lines.push('')
  lines.push('### Implementation Roadmap')
  for (const rd of r.implementation_roadmap) lines.push(`- ${rd}`)
  lines.push('')
  lines.push('### Quick Wins (0-90 days)')
  for (const q of r.quick_wins) lines.push(`- [ ] ${q}`)
  lines.push('')
  lines.push('### Risk Mitigations')
  for (const rm of r.risk_mitigations) lines.push(`- ${rm}`)
  lines.push('')
  lines.push('### Compliance Mapping')
  for (const cm of r.compliance_mapping) lines.push(`- ${cm}`)
  lines.push('')
  lines.push(`> **Disclaimer:** ${DISCLAIMER}`)
  return lines.join('\n')
}

/* ─────────────────────────────────────────────
   Plugin Registration
   ───────────────────────────────────────────── */
export function apply(ctx: Context) {
  const tools = ctx.tools

  // Tool 1: Threat Intelligence Aggregator
  tools.register(defineTool({
    name: 'threat_intelligence_aggregator',
    description: 'Aggregate and correlate threat intelligence from multiple sources. Generates IOCs, identifies threat actors, correlates campaigns, and provides trend analysis for a given industry and time window.',
    parameters: {
      input_data: { type: 'string' as const, required: true, description: 'JSON-encoded input. Fields: organization (string), industry (string), sources (string[]), threat_types (string[]), time_window_days (number), severity_threshold ("critical"|"high"|"medium"|"low"|"all")' },
    },
    output: {
      schema: { type: 'string' as const },
      render: (_a: any, v: any) => [{ type: 'text' as const, text: v as string }],
    },
    async execute(args: { input_data: string }) {
      const input: ThreatIntelInput = JSON.parse(args.input_data)
      return formatThreatIntelReport(aggregateThreatIntel(input))
    },
  }))

  // Tool 2: Vulnerability Management Engine
  tools.register(defineTool({
    name: 'vulnerability_management_engine',
    description: 'Scan, prioritize, and manage vulnerability remediation. Generates CVE-based findings with CVSS scores, EPSS exploitability, remediation plans with SLAs, and compliance gap analysis.',
    parameters: {
      input_data: { type: 'string' as const, required: true, description: 'JSON-encoded input. Fields: asset_scope (string[]), environment ("production"|"staging"|"development"|"cloud"|"hybrid"), scan_depth ("surface"|"standard"|"deep"|"compliance"), max_results (number), include_exploitability (boolean)' },
    },
    output: {
      schema: { type: 'string' as const },
      render: (_a: any, v: any) => [{ type: 'text' as const, text: v as string }],
    },
    async execute(args: { input_data: string }) {
      const input: VulnMgmtInput = JSON.parse(args.input_data)
      return formatVulnMgmtReport(runVulnManagement(input))
    },
  }))

  // Tool 3: Incident Response Orchestrator
  tools.register(defineTool({
    name: 'incident_response_orchestrator',
    description: 'Orchestrate end-to-end incident response workflows. Creates phased response plans (Detection, Containment, Eradication, Recovery, Post-Incident) with SLAs, regulatory notifications, and communication timelines.',
    parameters: {
      input_data: { type: 'string' as const, required: true, description: 'JSON-encoded input. Fields: incident_type ("ransomware"|"data_breach"|"ddos"|"insider_threat"|"apt"|"supply_chain"|"phishing_campaign"|"zero_day"), severity ("P1"|"P2"|"P3"|"P4"), affected_systems (number), data_volume_gb (number), regulatory_scope (string[]), containment_status ("none"|"partial"|"full")' },
    },
    output: {
      schema: { type: 'string' as const },
      render: (_a: any, v: any) => [{ type: 'text' as const, text: v as string }],
    },
    async execute(args: { input_data: string }) {
      const input: IRInput = JSON.parse(args.input_data)
      return formatIRReport(orchestrateIncidentResponse(input))
    },
  }))

  // Tool 4: Security Orchestration Automator
  tools.register(defineTool({
    name: 'security_orchestration_automator',
    description: 'Automate SOAR playbooks and security workflows. Generates multi-step automated response playbooks for phishing, malware, DLP, brute force, insider threat, and vulnerability response with integration maps and escalation rules.',
    parameters: {
      input_data: { type: 'string' as const, required: true, description: 'JSON-encoded input. Fields: platform (string), playbook_category ("phishing_response"|"malware_containment"|"data_loss_prevention"|"brute_force_response"|"insider_threat"|"vulnerability_response"), automation_level ("full_auto"|"semi_auto"|"human_in_loop"), integrations (string[]), trigger_conditions (string[])' },
    },
    output: {
      schema: { type: 'string' as const },
      render: (_a: any, v: any) => [{ type: 'text' as const, text: v as string }],
    },
    async execute(args: { input_data: string }) {
      const input: SOARInput = JSON.parse(args.input_data)
      return formatSOARReport(automateSOAR(input))
    },
  }))

  // Tool 5: Attack Surface Mapper
  tools.register(defineTool({
    name: 'attack_surface_mapper',
    description: 'Map and analyze organizational attack surface. Discovers internet-facing assets, identifies attack vectors, generates risk heatmaps, and provides exposure reduction recommendations.',
    parameters: {
      input_data: { type: 'string' as const, required: true, description: 'JSON-encoded input. Fields: organization (string), domains (string[]), ip_ranges (string[]), cloud_providers (string[]), include_third_party (boolean), scan_type ("external"|"internal"|"both")' },
    },
    output: {
      schema: { type: 'string' as const },
      render: (_a: any, v: any) => [{ type: 'text' as const, text: v as string }],
    },
    async execute(args: { input_data: string }) {
      const input: AttackSurfaceInput = JSON.parse(args.input_data)
      return formatAttackSurfaceReport(mapAttackSurface(input))
    },
  }))

  // Tool 6: Malware Behavior Analyst
  tools.register(defineTool({
    name: 'malware_behavior_analyst',
    description: 'Analyze malware behavior patterns and indicators. Supports ransomware, trojan, worm, rootkit, spyware, cryptominer, wiper, fileless, polymorphic, and adware analysis with YARA/SIGMA rule generation.',
    parameters: {
      input_data: { type: 'string' as const, required: true, description: 'JSON-encoded input. Fields: sample_type ("ransomware"|"trojan"|"worm"|"rootkit"|"spyware"|"adware"|"cryptominer"|"wiper"|"fileless"|"polymorphic"), analysis_depth ("static"|"dynamic"|"full"), environment ("sandbox"|"production_isolated"|"air_gapped"), indicators (string[], optional)' },
    },
    output: {
      schema: { type: 'string' as const },
      render: (_a: any, v: any) => [{ type: 'text' as const, text: v as string }],
    },
    async execute(args: { input_data: string }) {
      const input: MalwareAnalysisInput = JSON.parse(args.input_data)
      return formatMalwareReport(analyzeMalwareBehavior(input))
    },
  }))

  // Tool 7: Security Posture Scorer
  tools.register(defineTool({
    name: 'security_posture_scorer',
    description: 'Score and benchmark organizational security posture across 15 security domains. Provides letter grades, industry benchmarking, peer comparison, investment recommendations, and improvement roadmaps.',
    parameters: {
      input_data: { type: 'string' as const, required: true, description: 'JSON-encoded input. Fields: organization (string), industry (string), employee_count (number), security_team_size (number), annual_security_budget_k (number), frameworks (string[]), maturity_baseline ("initial"|"developing"|"defined"|"managed"|"optimizing")' },
    },
    output: {
      schema: { type: 'string' as const },
      render: (_a: any, v: any) => [{ type: 'text' as const, text: v as string }],
    },
    async execute(args: { input_data: string }) {
      const input: PostureInput = JSON.parse(args.input_data)
      return formatPostureReport(scoreSecurityPosture(input))
    },
  }))

  // Tool 8: Zero Trust Architecture Advisor
  tools.register(defineTool({
    name: 'zero_trust_architecture_advisor',
    description: 'Advise on zero trust architecture implementation. Provides component-level recommendations, implementation roadmaps, principle assessments, quick wins, compliance mapping, and investment estimates.',
    parameters: {
      input_data: { type: 'string' as const, required: true, description: 'JSON-encoded input. Fields: organization (string), current_architecture ("perimeter_based"|"vpn_based"|"hybrid"|"cloud_native"|"legacy"), user_count (number), device_count (number), cloud_adoption ("none"|"partial"|"majority"|"full"), compliance_requirements (string[]), priority ("identity"|"device"|"network"|"application"|"data"|"all")' },
    },
    output: {
      schema: { type: 'string' as const },
      render: (_a: any, v: any) => [{ type: 'text' as const, text: v as string }],
    },
    async execute(args: { input_data: string }) {
      const input: ZeroTrustInput = JSON.parse(args.input_data)
      return formatZeroTrustReport(adviseZeroTrust(input))
    },
  }))

  console.log(`[${name}] Loaded v0.1.0 - Cybersecurity & Threat Intelligence with 8 tools`)
  console.log('  Tools: threat_intelligence_aggregator, vulnerability_management_engine, incident_response_orchestrator, security_orchestration_automator, attack_surface_mapper, malware_behavior_analyst, security_posture_scorer, zero_trust_architecture_advisor')
  console.log('  Market: $300B+ cybersecurity, 20% CAGR AI-powered security tools')
}
