/**
 * DSH Wildlife Conservation & Ecology Plugin v0.1.0
 *
 * Wildlife conservation and ecology toolkit targeting the $5B+ conservation
 * tech market and $3B+ ecology AI sector. Provides deterministic species
 * monitoring, habitat analysis, poaching prevention, biodiversity assessment,
 * population modeling, migration tracking, camera trap analysis, and
 * conservation ROI calculation.
 *
 * Tools (8):
 * 1. species_monitoring_engine   - Monitor species populations and detect trends
 * 2. habitat_analysis_mapper     - Analyze habitat conditions and fragmentation
 * 3. poaching_prevention_system  - Predict poaching hotspots and patrol routes
 * 4. biodiversity_assessment_tool - Assess biodiversity indices and ecosystem health
 * 5. wildlife_population_modeler - Model population dynamics and carrying capacity
 * 6. migration_tracker           - Track migration patterns and corridors
 * 7. camera_trap_analyzer        - Analyze camera trap data and species ID
 * 8. conservation_roi_calculator - Calculate conservation project ROI
 *
 * @module dsh-tool-wildlifeai
 * @version 0.1.0
 * @license MIT
 */

import type { Context } from '@deepseek-ai/cordis'
import { defineTool } from '@deepseek-ai/dsh-tools'

export const name = 'dsh-tool-wildlifeai'
export const inject = ['tools']

/* ─────────────────────────────────────────────
   Disclaimer
   ───────────────────────────────────────────── */
const DISCLAIMER =
  'This analysis is generated by AI model inference and deterministic algorithms. It is for reference only and does not replace professional ecological assessment, field surveys, or certified environmental impact analysis.'

/* ─────────────────────────────────────────────
   SeededRandom (mulberry32 PRNG)
   Seed derived from JSON.stringify(input)
   ───────────────────────────────────────────── */
function createSeededRandom(seed: number) {
  let s = seed | 0
  return () => {
    s = (s + 0x6d2b79f5) | 0
    let t = Math.imul(s ^ (s >>> 15), 1 | s)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function hashString(str: string): number {
  let hash = 0
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i)
    hash = ((hash << 5) - hash) + char
    hash = hash & hash
  }
  return Math.abs(hash) || 1
}

function createRngFromInput(input: unknown) {
  const seed = hashString(JSON.stringify(input))
  return createSeededRandom(seed)
}

/** Deterministic pick from array */
function pick<T>(rng: () => number, arr: T[]): T {
  return arr[Math.floor(rng() * arr.length)]
}

/** Deterministic pick N unique items from array */
function pickN<T>(rng: () => number, arr: T[], n: number): T[] {
  const copy = [...arr]
  const result: T[] = []
  for (let i = 0; i < Math.min(n, copy.length); i++) {
    const idx = Math.floor(rng() * copy.length)
    result.push(copy.splice(idx, 1)[0])
  }
  return result
}

/** Deterministic integer in range [min, max] */
function randInt(rng: () => number, min: number, max: number): number {
  return Math.floor(rng() * (max - min + 1)) + min
}

/** Deterministic float in range [min, max] */
function randFloat(rng: () => number, min: number, max: number): number {
  return Math.round((min + rng() * (max - min)) * 100) / 100
}

/* ─────────────────────────────────────────────
   1. Species Monitoring Engine
   ───────────────────────────────────────────── */
export interface SpeciesMonitoringInput {
  region: string
  target_species: string[]
  monitoring_duration_months: number
  survey_method: 'camera_trac' | 'transect' | 'acoustic' | 'satellite' | 'eDNA' | 'mixed'
  threat_level_filter: 'critical' | 'endangered' | 'vulnerable' | 'near_threatened' | 'all'
  include_population_trend: boolean
}

export interface SpeciesObservation {
  species_name: string
  scientific_name: string
  iucn_status: string
  population_estimate: number
  confidence_interval: [number, number]
  trend: 'increasing' | 'stable' | 'declining' | 'unknown'
  trend_percent_annual: number
  last_observed: string
  habitat_type: string
  threats: string[]
}

export interface SpeciesMonitoringResult {
  monitoring_id: string
  region: string
  duration_months: number
  survey_method: string
  total_species_detected: number
  observations: SpeciesObservation[]
  population_trends: string[]
  conservation_priorities: string[]
  alert_flags: string[]
  recommendations: string[]
}

function runSpeciesMonitoring(input: SpeciesMonitoringInput): SpeciesMonitoringResult {
  const rng = createRngFromInput(input)
  const monitoringId = 'SM-' + randInt(rng, 10000, 99999)

  const iucnStatuses = ['Critical', 'Endangered', 'Vulnerable', 'Near Threatened', 'Least Concern']
  const habitats = ['Tropical Rainforest', 'Savanna', 'Wetland', 'Grassland', 'Montane Forest', 'Mangrove', 'Coral Reef', 'Desert', 'Temperate Forest', 'Arctic Tundra']
  const threats = ['Habitat Loss', 'Poaching', 'Climate Change', 'Invasive Species', 'Pollution', 'Human-Wildlife Conflict', 'Disease', 'Deforestation', 'Mining', 'Agricultural Expansion']
  const trends: SpeciesObservation['trend'][] = ['increasing', 'stable', 'declining', 'unknown']

  const speciesPool = input.target_species.length > 0 ? input.target_species : [
    'African Elephant', 'Mountain Gorilla', 'Snow Leopard', 'Bengal Tiger', 'Giant Panda',
    'Blue Whale', 'Orangutan', 'Black Rhino', 'Amur Leopard', 'Hawksbill Sea Turtle',
    'Sumatran Elephant', 'Saola', 'Vaquita', 'Javan Rhino', 'Cross River Gorilla'
  ]

  const observationCount = randInt(rng, Math.min(5, speciesPool.length), Math.min(15, speciesPool.length))
  const selectedSpecies = pickN(rng, speciesPool, observationCount)
  const observations: SpeciesObservation[] = []

  for (const sp of selectedSpecies) {
    const trend = pick(rng, trends)
    const trendPercent = trend === 'increasing' ? randFloat(rng, 0.5, 8.0) :
                         trend === 'declining' ? -randFloat(rng, 0.5, 12.0) :
                         trend === 'stable' ? randFloat(rng, -0.3, 0.3) : 0
    const popEstimate = randInt(rng, 10, 50000)
    const ciLow = Math.round(popEstimate * (0.75 + rng() * 0.1))
    const ciHigh = Math.round(popEstimate * (1.1 + rng() * 0.25))

    observations.push({
      species_name: sp,
      scientific_name: 'SP-' + randInt(rng, 1000, 9999) + ' ' + pick(rng, ['africana', 'tigris', 'uncia', 'beringianus', 'giganteus', 'pygmaeus']),
      iucn_status: pick(rng, iucnStatuses),
      population_estimate: popEstimate,
      confidence_interval: [ciLow, ciHigh],
      trend,
      trend_percent_annual: trendPercent,
      last_observed: '2025-' + String(randInt(rng, 1, 12)).padStart(2, '0') + '-' + String(randInt(rng, 1, 28)).padStart(2, '0'),
      habitat_type: pick(rng, habitats),
      threats: pickN(rng, threats, randInt(rng, 1, 4)),
    })
  }

  // Filter by threat level
  let filteredObservations = observations
  const threatRank: Record<string, number> = { 'Least Concern': 0, 'Near Threatened': 1, 'Vulnerable': 2, 'Endangered': 3, 'Critical': 4 }
  if (input.threat_level_filter !== 'all') {
    const filterRank = threatRank[input.threat_level_filter.charAt(0).toUpperCase() + input.threat_level_filter.slice(1)]
    filteredObservations = observations.filter(o => (threatRank[o.iucn_status] || 0) <= filterRank)
  }

  const populationTrends: string[] = []
  if (input.include_population_trend) {
    const declining = filteredObservations.filter(o => o.trend === 'declining')
    const increasing = filteredObservations.filter(o => o.trend === 'increasing')
    populationTrends.push(declining.length + ' species showing declining populations in ' + input.region)
    populationTrends.push(increasing.length + ' species showing population recovery/growth')
    if (declining.length > 0) {
      populationTrends.push('Most threatened: ' + declining[0].species_name + ' (' + declining[0].trend_percent_annual.toFixed(1) + '% annual decline)')
    }
    populationTrends.push('Overall ecosystem stability index: ' + (randFloat(rng, 0.4, 0.9) * 100).toFixed(0) + '%')
  }

  const conservationPriorities: string[] = []
  const criticalSpecies = filteredObservations.filter(o => o.iucn_status === 'Critical' || o.iucn_status === 'Endangered')
  for (const sp of criticalSpecies.slice(0, 3)) {
    conservationPriorities.push(sp.species_name + ' (' + sp.iucn_status + ') - Pop: ' + sp.population_estimate + ' - Immediate action required')
  }
  if (filteredObservations.length > 0) {
    const habitatLoss = filteredObservations.filter(o => o.threats.includes('Habitat Loss')).length
    if (habitatLoss > 0) conservationPriorities.push('Habitat protection needed for ' + habitatLoss + ' species facing habitat loss')
  }

  const alertFlags: string[] = []
  for (const obs of filteredObservations) {
    if (obs.trend === 'declining' && obs.trend_percent_annual < -5) {
      alertFlags.push('RAPID DECLINE: ' + obs.species_name + ' declining at ' + Math.abs(obs.trend_percent_annual).toFixed(1) + '%/year')
    }
    if (obs.population_estimate < 500) {
      alertFlags.push('CRITICALLY LOW: ' + obs.species_name + ' estimated below 500 individuals')
    }
  }

  const recommendations: string[] = []
  recommendations.push('Increase monitoring frequency for ' + criticalSpecies.length + ' at-risk species surveyed')
  recommendations.push('Deploy additional ' + input.survey_method + ' units across ' + input.region)
  recommendations.push('Establish anti-poaching patrols in high-threat zones')
  recommendations.push('Implement habitat corridor restoration between fragmented zones')
  recommendations.push('Conduct community engagement programs to reduce human-wildlife conflict')

  return {
    monitoring_id: monitoringId,
    region: input.region,
    duration_months: input.monitoring_duration_months,
    survey_method: input.survey_method,
    total_species_detected: filteredObservations.length,
    observations: filteredObservations,
    population_trends: populationTrends,
    conservation_priorities: conservationPriorities,
    alert_flags: alertFlags,
    recommendations,
  }
}

function formatSpeciesMonitoringReport(r: SpeciesMonitoringResult): string {
  const lines: string[] = []
  lines.push('## Species Monitoring Report')
  lines.push('')
  lines.push('**Monitoring ID:** ' + r.monitoring_id + ' | **Region:** ' + r.region + ' | **Duration:** ' + r.duration_months + ' months')
  lines.push('**Survey Method:** ' + r.survey_method + ' | **Species Detected:** ' + r.total_species_detected)
  lines.push('')
  lines.push('### Species Observations')
  lines.push('| Species | IUCN Status | Population | Trend | Annual % | Habitat |')
  lines.push('|---------|-------------|------------|-------|----------|---------|')
  for (const o of r.observations) {
    lines.push('| ' + o.species_name + ' | ' + o.iucn_status + ' | ' + o.population_estimate + ' | ' + o.trend + ' | ' + (o.trend_percent_annual >= 0 ? '+' : '') + o.trend_percent_annual.toFixed(1) + '% | ' + o.habitat_type + ' |')
  }
  lines.push('')
  lines.push('### Threats Summary')
  for (const o of r.observations) {
    lines.push('- **' + o.species_name + ':** ' + o.threats.join(', '))
  }
  lines.push('')
  if (r.population_trends.length > 0) {
    lines.push('### Population Trends')
    for (const t of r.population_trends) lines.push('- ' + t)
    lines.push('')
  }
  if (r.alert_flags.length > 0) {
    lines.push('## Alert Flags')
    for (const a of r.alert_flags) lines.push('- **' + a + '**')
    lines.push('')
  }
  lines.push('### Conservation Priorities')
  for (const p of r.conservation_priorities) lines.push('- **[PRIORITY]** ' + p)
  lines.push('')
  lines.push('### Recommendations')
  for (const rec of r.recommendations) lines.push('- [ ] ' + rec)
  lines.push('')
  lines.push('> **Disclaimer:** ' + DISCLAIMER)
  return lines.join('\n')
}

/* ─────────────────────────────────────────────
   2. Habitat Analysis Mapper
   ───────────────────────────────────────────── */
export interface HabitatAnalysisInput {
  region: string
  area_km2: number
  habitat_types: string[]
  fragmentation_index_threshold: number
  include_corridors: boolean
  climate_projection_years: number
}

export interface HabitatZone {
  zone_id: string
  habitat_type: string
  area_km2: number
  fragmentation_index: number
  connectivity_score: number
  degradation_level: 'Low' | 'Moderate' | 'High' | 'Severe'
  key_species_supported: number
  threats: string[]
  protection_status: 'Protected' | 'Partial' | 'Unprotected'
}

export interface HabitatCorridor {
  corridor_id: string
  connected_zones: string[]
  length_km: number
  width_km: number
  viability: 'High' | 'Medium' | 'Low'
  barriers: string[]
  restoration_potential: number
}

export interface HabitatAnalysisResult {
  analysis_id: string
  region: string
  total_area_km2: number
  habitats: HabitatZone[]
  corridors: HabitatCorridor[]
  fragmentation_summary: string[]
  degradation_assessment: string[]
  climate_impact_projections: string[]
  conservation_recommendations: string[]
  overall_health_score: number
}

function analyzeHabitat(input: HabitatAnalysisInput): HabitatAnalysisResult {
  const rng = createRngFromInput(input)
  const analysisId = 'HA-' + randInt(rng, 10000, 99999)

  const habitatTypes = input.habitat_types.length > 0 ? input.habitat_types : [
    'Tropical Rainforest', 'Mangrove', 'Savanna Grassland', 'Wetland', 'Montane Forest',
    'Riparian Zone', 'Coral Reef', 'Seagrass Meadow', 'Peat Swamp', 'Dry Deciduous Forest'
  ]

  const zoneCount = randInt(rng, 4, 10)
  const habitats: HabitatZone[] = []
  let remainingArea = input.area_km2

  for (let i = 0; i < zoneCount; i++) {
    const area = i === zoneCount - 1 ? remainingArea : Math.round(remainingArea * randFloat(rng, 0.1, 0.35))
    remainingArea -= area
    if (area <= 0) break

    const degradationLevel = pick(rng, ['Low', 'Moderate', 'High', 'Severe'] as const)
    const fragBase = degradationLevel === 'Severe' ? randFloat(rng, 0.6, 0.95) :
                     degradationLevel === 'High' ? randFloat(rng, 0.4, 0.7) :
                     degradationLevel === 'Moderate' ? randFloat(rng, 0.2, 0.45) :
                     randFloat(rng, 0.05, 0.25)

    habitats.push({
      zone_id: 'Z' + String(i + 1).padStart(3, '0'),
      habitat_type: pick(rng, habitatTypes),
      area_km2: area,
      fragmentation_index: fragBase,
      connectivity_score: Math.round((1 - fragBase) * 100) / 100,
      degradation_level: degradationLevel,
      key_species_supported: randInt(rng, 3, 25),
      threats: pickN(rng, ['Deforestation', 'Urbanization', 'Agriculture', 'Mining', 'Pollution', 'Invasive Species', 'Climate Change', 'Fire'], randInt(rng, 1, 4)),
      protection_status: pick(rng, ['Protected', 'Partial', 'Unprotected'] as const),
    })
  }

  const corridors: HabitatCorridor[] = []
  if (input.include_corridors && habitats.length >= 2) {
    const corridorCount = randInt(rng, 2, Math.min(6, habitats.length - 1))
    for (let i = 0; i < corridorCount; i++) {
      const zonePair = pickN(rng, habitats, 2)
      corridors.push({
        corridor_id: 'C' + String(i + 1).padStart(3, '0'),
        connected_zones: zonePair.map(z => z.zone_id),
        length_km: randFloat(rng, 5, 150),
        width_km: randFloat(rng, 0.5, 15),
        viability: pick(rng, ['High', 'Medium', 'Low'] as const),
        barriers: pickN(rng, ['Road', 'Railway', 'Urban Area', 'Agricultural Land', 'Dam', 'Fence', 'River'], randInt(rng, 1, 3)),
        restoration_potential: randFloat(rng, 0.2, 0.95),
      })
    }
  }

  const fragmentationSummary: string[] = []
  const avgFrag = habitats.reduce((s, h) => s + h.fragmentation_index, 0) / habitats.length
  fragmentationSummary.push('Average fragmentation index: ' + avgFrag.toFixed(2) + ' (threshold: ' + input.fragmentation_index_threshold + ')')
  const highFrag = habitats.filter(h => h.fragmentation_index >= input.fragmentation_index_threshold)
  fragmentationSummary.push(highFrag.length + ' of ' + habitats.length + ' zones exceed fragmentation threshold')
  fragmentationSummary.push('Total habitat patches: ' + habitats.length + ' across ' + input.area_km2 + ' km2')
  if (corridors.length > 0) {
    fragmentationSummary.push('Identified ' + corridors.length + ' potential habitat corridors for connectivity restoration')
  }

  const degradationAssessment: string[] = []
  const severeCount = habitats.filter(h => h.degradation_level === 'Severe').length
  const highCount = habitats.filter(h => h.degradation_level === 'High').length
  degradationAssessment.push('Severe degradation: ' + severeCount + ' zones (' + (severeCount / habitats.length * 100).toFixed(0) + '% of area)')
  degradationAssessment.push('High degradation: ' + highCount + ' zones')
  degradationAssessment.push('Protected area coverage: ' + (habitats.filter(h => h.protection_status === 'Protected').length / habitats.length * 100).toFixed(0) + '% of zones')
  const unprotectedHighValue = habitats.filter(h => h.protection_status === 'Unprotected' && h.key_species_supported >= 10)
  if (unprotectedHighValue.length > 0) {
    degradationAssessment.push('URGENT: ' + unprotectedHighValue.length + ' high-biodiversity zones lack protection status')
  }

  const climateImpactProjections: string[] = []
  climateImpactProjections.push('By ' + (2025 + input.climate_projection_years) + ': Temperature increase of ' + randFloat(rng, 1.0, 3.5).toFixed(1) + 'C projected')
  climateImpactProjections.push('Habitat suitability decline: ' + randInt(rng, 10, 40) + '% for current species assemblages')
  climateImpactProjections.push('Range shift potential: ' + randInt(rng, 50, 300) + ' km poleward/elevation shift required')
  climateImpactProjections.push('Sea level impact on coastal habitats: ' + randInt(rng, 5, 25) + '% area loss projected')
  climateImpactProjections.push('Increased fire risk: ' + randInt(rng, 20, 80) + '% increase in fire-prone days')

  const conservationRecommendations: string[] = []
  if (severeCount > 0) conservationRecommendations.push('Immediate restoration needed for ' + severeCount + ' severely degraded zones')
  conservationRecommendations.push('Establish ' + corridors.length + ' habitat corridors to improve connectivity')
  conservationRecommendations.push('Upgrade protection status for ' + (habitats.filter(h => h.protection_status === 'Unprotected').length) + ' unprotected zones')
  conservationRecommendations.push('Implement buffer zones around high-fragmentation areas')
  conservationRecommendations.push('Develop climate adaptation corridors for species range shifts')
  conservationRecommendations.push('Restore degraded wetlands and riparian zones for water regulation')

  const overallHealth = Math.round((1 - avgFrag) * (habitats.filter(h => h.degradation_level === 'Low' || h.degradation_level === 'Moderate').length / habitats.length) * 100)

  return {
    analysis_id: analysisId,
    region: input.region,
    total_area_km2: input.area_km2,
    habitats,
    corridors,
    fragmentation_summary: fragmentationSummary,
    degradation_assessment: degradationAssessment,
    climate_impact_projections: climateImpactProjections,
    conservation_recommendations: conservationRecommendations,
    overall_health_score: overallHealth,
  }
}

function formatHabitatAnalysisReport(r: HabitatAnalysisResult): string {
  const lines: string[] = []
  lines.push('## Habitat Analysis Report')
  lines.push('')
  lines.push('**Analysis ID:** ' + r.analysis_id + ' | **Region:** ' + r.region + ' | **Total Area:** ' + r.total_area_km2 + ' km2')
  lines.push('**Overall Health Score:** ' + r.overall_health_score + '/100')
  lines.push('')
  lines.push('### Habitat Zones')
  lines.push('| Zone | Type | Area (km2) | Fragmentation | Degradation | Protection |')
  lines.push('|------|------|------------|---------------|-------------|------------|')
  for (const h of r.habitats) {
    lines.push('| ' + h.zone_id + ' | ' + h.habitat_type + ' | ' + h.area_km2 + ' | ' + h.fragmentation_index.toFixed(2) + ' | ' + h.degradation_level + ' | ' + h.protection_status + ' |')
  }
  lines.push('')
  if (r.corridors.length > 0) {
    lines.push('### Habitat Corridors')
    lines.push('| Corridor | Zones | Length (km) | Width (km) | Viability | Barriers |')
    lines.push('|----------|-------|-------------|------------|-----------|----------|')
    for (const c of r.corridors) {
      lines.push('| ' + c.corridor_id + ' | ' + c.connected_zones.join(' <-> ') + ' | ' + c.length_km.toFixed(1) + ' | ' + c.width_km.toFixed(1) + ' | ' + c.viability + ' | ' + c.barriers.join(', ') + ' |')
    }
    lines.push('')
  }
  lines.push('### Fragmentation Summary')
  for (const f of r.fragmentation_summary) lines.push('- ' + f)
  lines.push('')
  lines.push('### Degradation Assessment')
  for (const d of r.degradation_assessment) lines.push('- ' + d)
  lines.push('')
  lines.push('### Climate Impact Projections')
  for (const c of r.climate_impact_projections) lines.push('- ' + c)
  lines.push('')
  lines.push('### Conservation Recommendations')
  for (const rec of r.conservation_recommendations) lines.push('- [ ] ' + rec)
  lines.push('')
  lines.push('> **Disclaimer:** ' + DISCLAIMER)
  return lines.join('\n')
}

/* ─────────────────────────────────────────────
   3. Poaching Prevention System
   ───────────────────────────────────────────── */
export interface PoachingPreventionInput {
  protected_area: string
  area_km2: number
  target_species: string[]
  historical_incidents: number
  patrol_coverage_percent: number
  ranger_count: number
  technology_level: 'basic' | 'intermediate' | 'advanced'
  community_engagement_level: 'low' | 'medium' | 'high'
}

export interface PoachingHotspot {
  zone_id: string
  risk_level: 'Critical' | 'High' | 'Medium' | 'Low'
  risk_score: number
  coordinates: [number, number]
  primary_threat: string
  incident_history_12mo: number
  accessibility: 'Easy' | 'Moderate' | 'Difficult'
  recommended_patrol_frequency: string
}

export interface PatrolRoute {
  route_id: string
  priority: number
  waypoints: number
  estimated_duration_hours: number
  coverage_km2: number
  hotspot_coverage: string[]
  recommended_time: string
  risk_mitigation_score: number
}

export interface PoachingPreventionResult {
  system_id: string
  protected_area: string
  risk_assessment_date: string
  overall_threat_level: 'Critical' | 'High' | 'Medium' | 'Low'
  hotspots: PoachingHotspot[]
  patrol_routes: PatrolRoute[]
  resource_allocation: string[]
  technology_recommendations: string[]
  community_strategies: string[]
  effectiveness_projection: string[]
}

function runPoachingPrevention(input: PoachingPreventionInput): PoachingPreventionResult {
  const rng = createRngFromInput(input)
  const systemId = 'PP-' + randInt(rng, 10000, 99999)

  const threatTypes = ['Ivory poaching', 'Bushmeat hunting', 'Traditional medicine trade', 'Live animal capture', 'Skin/bone trade', 'Trophy poaching', 'Subsistence poaching', 'Organized crime poaching']
  const hotspotCount = randInt(rng, 3, 10)
  const hotspots: PoachingHotspot[] = []

  for (let i = 0; i < hotspotCount; i++) {
    const riskScore = randFloat(rng, 0.2, 0.98)
    const riskLevel = riskScore >= 0.8 ? 'Critical' : riskScore >= 0.6 ? 'High' : riskScore >= 0.4 ? 'Medium' : 'Low'
    const incidents = riskScore > 0.7 ? randInt(rng, 5, 25) : riskScore > 0.4 ? randInt(rng, 1, 8) : randInt(rng, 0, 3)

    hotspots.push({
      zone_id: 'HS-' + String(i + 1).padStart(3, '0'),
      risk_level: riskLevel,
      risk_score: riskScore,
      coordinates: [randFloat(rng, -180, 180), randFloat(rng, -90, 90)],
      primary_threat: pick(rng, threatTypes),
      incident_history_12mo: incidents,
      accessibility: pick(rng, ['Easy', 'Moderate', 'Difficult'] as const),
      recommended_patrol_frequency: riskScore > 0.7 ? 'Daily' : riskScore > 0.5 ? '3x/Weekly' : riskScore > 0.3 ? 'Weekly' : 'Bi-weekly',
    })
  }

  hotspots.sort((a, b) => b.risk_score - a.risk_score)

  const patrolRoutes: PatrolRoute[] = []
  const routeCount = randInt(rng, 3, 8)
  for (let i = 0; i < routeCount; i++) {
    const coveredHotspots = pickN(rng, hotspots, randInt(rng, 1, Math.min(3, hotspots.length)))
    patrolRoutes.push({
      route_id: 'PR-' + String(i + 1).padStart(3, '0'),
      priority: i + 1,
      waypoints: randInt(rng, 4, 12),
      estimated_duration_hours: randFloat(rng, 2, 10),
      coverage_km2: randFloat(rng, 5, 50),
      hotspot_coverage: coveredHotspots.map(h => h.zone_id),
      recommended_time: pick(rng, ['Dawn (05:00-08:00)', 'Morning (08:00-12:00)', 'Afternoon (12:00-17:00)', 'Dusk (17:00-20:00)', 'Night (20:00-05:00)']),
      risk_mitigation_score: randFloat(rng, 0.3, 0.9),
    })
  }

  const resourceAllocation: string[] = []
  const criticalHotspots = hotspots.filter(h => h.risk_level === 'Critical' || h.risk_level === 'High')
  resourceAllocation.push('Deploy ' + Math.ceil(criticalHotspots.length * 1.5) + ' additional ranger units to high-risk zones')
  resourceAllocation.push('Current patrol coverage: ' + input.patrol_coverage_percent + '% - Target: ' + Math.min(95, input.patrol_coverage_percent + 20) + '%')
  resourceAllocation.push('Ranger-to-area ratio: 1:' + Math.round(input.area_km2 / Math.max(1, input.ranger_count)) + ' km2 (recommended 1:25)')
  resourceAllocation.push('Allocate ' + randInt(rng, 2, 6) + ' rapid response teams for critical zones')
  resourceAllocation.push('Budget estimate: $' + randInt(rng, 50, 500) + 'K annually for enhanced patrol operations')

  const technologyRecommendations: string[] = []
  if (input.technology_level === 'basic' || input.technology_level === 'intermediate') {
    technologyRecommendations.push('Deploy camera trap network: ' + randInt(rng, 50, 200) + ' units across high-risk zones')
    technologyRecommendations.push('Implement drone surveillance: ' + randInt(rng, 2, 8) + ' UAVs for aerial monitoring')
  }
  if (input.technology_level === 'advanced' || input.technology_level === 'intermediate') {
    technologyRecommendations.push('Install acoustic gunshot detection system covering ' + randInt(rng, 50, 200) + ' km2')
    technologyRecommendations.push('Deploy AI-powered real-time camera trap analysis with species/poacher classification')
  }
  technologyRecommendations.push('Implement GPS tracking collars on ' + randInt(rng, 5, 20) + ' key individuals of target species')
  technologyRecommendations.push('Establish centralized command center with real-time data integration')
  technologyRecommendations.push('Deploy SMART (Spatial Monitoring and Reporting Tool) across all patrol teams')

  const communityStrategies: string[] = []
  if (input.community_engagement_level === 'low') {
    communityStrategies.push('Establish community conservancy partnerships in buffer zones')
    communityStrategies.push('Launch environmental education programs in ' + randInt(rng, 5, 15) + ' surrounding communities')
  }
  communityStrategies.push('Create incentive programs: ' + randInt(rng, 10, 30) + '% revenue sharing from ecotourism')
  communityStrategies.push('Train ' + randInt(rng, 20, 100) + ' community wildlife scouts for local monitoring')
  communityStrategies.push('Develop alternative livelihood programs to reduce poaching dependency')
  communityStrategies.push('Establish anonymous tip-line with reward system for poaching intelligence')

  const effectivenessProjection: string[] = []
  const currentEffectiveness = input.patrol_coverage_percent * 0.4 + (input.technology_level === 'advanced' ? 30 : input.technology_level === 'intermediate' ? 15 : 5) + (input.community_engagement_level === 'high' ? 20 : input.community_engagement_level === 'medium' ? 10 : 0)
  const projectedEffectiveness = Math.min(95, currentEffectiveness + randInt(rng, 15, 35))
  effectivenessProjection.push('Current prevention effectiveness: ' + currentEffectiveness.toFixed(0) + '%')
  effectivenessProjection.push('Projected effectiveness with recommendations: ' + projectedEffectiveness.toFixed(0) + '%')
  effectivenessProjection.push('Expected incident reduction: ' + randInt(rng, 30, 70) + '% within 12 months')
  effectivenessProjection.push('ROI of prevention investment: $' + randFloat(rng, 2, 8).toFixed(1) + ' return per $1 invested')

  const avgRisk = hotspots.reduce((s, h) => s + h.risk_score, 0) / hotspots.length
  const overallThreat = avgRisk >= 0.7 ? 'Critical' : avgRisk >= 0.5 ? 'High' : avgRisk >= 0.3 ? 'Medium' : 'Low'

  return {
    system_id: systemId,
    protected_area: input.protected_area,
    risk_assessment_date: '2025-' + String(randInt(rng, 1, 12)).padStart(2, '0') + '-' + String(randInt(rng, 1, 28)).padStart(2, '0'),
    overall_threat_level: overallThreat,
    hotspots,
    patrol_routes: patrolRoutes,
    resource_allocation: resourceAllocation,
    technology_recommendations: technologyRecommendations,
    community_strategies: communityStrategies,
    effectiveness_projection: effectivenessProjection,
  }
}

function formatPoachingPreventionReport(r: PoachingPreventionResult): string {
  const lines: string[] = []
  lines.push('## Poaching Prevention System Report')
  lines.push('')
  lines.push('**System ID:** ' + r.system_id + ' | **Protected Area:** ' + r.protected_area)
  lines.push('**Assessment Date:** ' + r.risk_assessment_date + ' | **Overall Threat Level:** ' + r.overall_threat_level)
  lines.push('')
  lines.push('### Poaching Hotspots')
  lines.push('| Zone | Risk Level | Score | Primary Threat | Incidents (12mo) | Patrol Freq |')
  lines.push('|------|------------|-------|----------------|------------------|-------------|')
  for (const h of r.hotspots) {
    lines.push('| ' + h.zone_id + ' | ' + h.risk_level + ' | ' + h.risk_score.toFixed(2) + ' | ' + h.primary_threat + ' | ' + h.incident_history_12mo + ' | ' + h.recommended_patrol_frequency + ' |')
  }
  lines.push('')
  lines.push('### Recommended Patrol Routes')
  lines.push('| Route | Priority | Duration (hrs) | Coverage (km2) | Hotspots | Time |')
  lines.push('|-------|----------|----------------|----------------|----------|------|')
  for (const p of r.patrol_routes) {
    lines.push('| ' + p.route_id + ' | ' + p.priority + ' | ' + p.estimated_duration_hours.toFixed(1) + ' | ' + p.coverage_km2.toFixed(1) + ' | ' + p.hotspot_coverage.join(', ') + ' | ' + p.recommended_time + ' |')
  }
  lines.push('')
  lines.push('### Resource Allocation')
  for (const ra of r.resource_allocation) lines.push('- ' + ra)
  lines.push('')
  lines.push('### Technology Recommendations')
  for (const t of r.technology_recommendations) lines.push('- [ ] ' + t)
  lines.push('')
  lines.push('### Community Strategies')
  for (const c of r.community_strategies) lines.push('- ' + c)
  lines.push('')
  lines.push('### Effectiveness Projection')
  for (const e of r.effectiveness_projection) lines.push('- **' + e + '**')
  lines.push('')
  lines.push('> **Disclaimer:** ' + DISCLAIMER)
  return lines.join('\n')
}

/* ─────────────────────────────────────────────
   4. Biodiversity Assessment Tool
   ───────────────────────────────────────────── */
export interface BiodiversityAssessmentInput {
  region: string
  ecosystem_type: string
  survey_area_km2: number
  taxa_groups: string[]
  assessment_depth: 'rapid' | 'standard' | 'comprehensive'
  include_functional_diversity: boolean
  reference_condition: 'pristine' | 'historical' | 'best_available'
}

export interface TaxonRecord {
  group: string
  species_count: number
  endemic_count: number
  threatened_count: number
  shannon_index: number
  simpson_index: number
  evenness: number
  key_species: string[]
}

export interface EcosystemService {
  service: string
  value_category: 'Provisioning' | 'Regulating' | 'Supporting' | 'Cultural'
  estimated_value_usd_ha_yr: number
  trend: 'Improving' | 'Stable' | 'Declining'
  confidence: 'High' | 'Medium' | 'Low'
}

export interface BiodiversityAssessmentResult {
  assessment_id: string
  region: string
  ecosystem_type: string
  survey_area_km2: number
  taxa_records: TaxonRecord[]
  ecosystem_services: EcosystemService[]
  biodiversity_indices: Record<string, number>
  threat_assessment: string[]
  ecosystem_integrity_score: number
  comparison_to_reference: string[]
  management_recommendations: string[]
}

function assessBiodiversity(input: BiodiversityAssessmentInput): BiodiversityAssessmentResult {
  const rng = createRngFromInput(input)
  const assessmentId = 'BA-' + randInt(rng, 10000, 99999)

  const taxaGroups = input.taxa_groups.length > 0 ? input.taxa_groups : ['Mammals', 'Birds', 'Reptiles', 'Amphibians', 'Fish', 'Invertebrates', 'Plants', 'Fungi']
  const depthMultiplier = input.assessment_depth === 'comprehensive' ? 1.5 : input.assessment_depth === 'standard' ? 1.0 : 0.6

  const taxaRecords: TaxonRecord[] = []
  for (const group of taxaGroups) {
    const baseCount = randInt(rng, 10, 200)
    const speciesCount = Math.round(baseCount * depthMultiplier)
    const endemicCount = Math.round(speciesCount * randFloat(rng, 0.02, 0.25))
    const threatenedCount = Math.round(speciesCount * randFloat(rng, 0.01, 0.15))

    taxaRecords.push({
      group,
      species_count: speciesCount,
      endemic_count: endemicCount,
      threatened_count: threatenedCount,
      shannon_index: randFloat(rng, 1.5, 4.5),
      simpson_index: randFloat(rng, 0.6, 0.95),
      evenness: randFloat(rng, 0.5, 0.9),
      key_species: pickN(rng, ['Keystone predator', 'Ecosystem engineer', 'Pollinator', 'Seed disperser', 'Umbrella species', 'Flagship species', 'Indicator species'], randInt(rng, 1, 3)),
    })
  }

  const ecosystemServices: EcosystemService[] = [
    { service: 'Carbon Sequestration', value_category: 'Regulating', estimated_value_usd_ha_yr: randInt(rng, 50, 500), trend: pick(rng, ['Improving', 'Stable', 'Declining'] as const), confidence: pick(rng, ['High', 'Medium', 'Low'] as const) },
    { service: 'Water Purification', value_category: 'Regulating', estimated_value_usd_ha_yr: randInt(rng, 30, 300), trend: pick(rng, ['Improving', 'Stable', 'Declining'] as const), confidence: pick(rng, ['High', 'Medium', 'Low'] as const) },
    { service: 'Pollination Services', value_category: 'Supporting', estimated_value_usd_ha_yr: randInt(rng, 20, 200), trend: pick(rng, ['Improving', 'Stable', 'Declining'] as const), confidence: pick(rng, ['High', 'Medium', 'Low'] as const) },
    { service: 'Soil Formation & Fertility', value_category: 'Supporting', estimated_value_usd_ha_yr: randInt(rng, 10, 100), trend: pick(rng, ['Improving', 'Stable', 'Declining'] as const), confidence: pick(rng, ['High', 'Medium', 'Low'] as const) },
    { service: 'Flood Regulation', value_category: 'Regulating', estimated_value_usd_ha_yr: randInt(rng, 40, 400), trend: pick(rng, ['Improving', 'Stable', 'Declining'] as const), confidence: pick(rng, ['High', 'Medium', 'Low'] as const) },
    { service: 'Recreation & Ecotourism', value_category: 'Cultural', estimated_value_usd_ha_yr: randInt(rng, 100, 1000), trend: pick(rng, ['Improving', 'Stable', 'Declining'] as const), confidence: pick(rng, ['High', 'Medium', 'Low'] as const) },
    { service: 'Timber & Non-timber Products', value_category: 'Provisioning', estimated_value_usd_ha_yr: randInt(rng, 20, 250), trend: pick(rng, ['Improving', 'Stable', 'Declining'] as const), confidence: pick(rng, ['High', 'Medium', 'Low'] as const) },
    { service: 'Genetic Resources', value_category: 'Provisioning', estimated_value_usd_ha_yr: randInt(rng, 5, 80), trend: pick(rng, ['Improving', 'Stable', 'Declining'] as const), confidence: pick(rng, ['High', 'Medium', 'Low'] as const) },
  ]

  const totalSpecies = taxaRecords.reduce((s, t) => s + t.species_count, 0)
  const totalEndemic = taxaRecords.reduce((s, t) => s + t.endemic_count, 0)
  const totalThreatened = taxaRecords.reduce((s, t) => s + t.threatened_count, 0)
  const avgShannon = taxaRecords.reduce((s, t) => s + t.shannon_index, 0) / taxaRecords.length
  const avgSimpson = taxaRecords.reduce((s, t) => s + t.simpson_index, 0) / taxaRecords.length

  const biodiversityIndices: Record<string, number> = {
    total_species_richness: totalSpecies,
    endemic_species_count: totalEndemic,
    threatened_species_count: totalThreatened,
    mean_shannon_wiener: Math.round(avgShannon * 100) / 100,
    mean_simpson_diversity: Math.round(avgSimpson * 100) / 100,
    species_density_per_km2: Math.round(totalSpecies / input.survey_area_km2 * 100) / 100,
    endemism_rate: Math.round(totalEndemic / totalSpecies * 10000) / 100,
    threat_prevalence: Math.round(totalThreatened / totalSpecies * 10000) / 100,
  }

  const threatAssessment: string[] = []
  threatAssessment.push(totalThreatened + ' threatened species identified across ' + taxaGroups.length + ' taxa groups')
  if (totalEndemic > 0) threatAssessment.push(totalEndemic + ' endemic species - high conservation value for ' + input.region)
  threatAssessment.push('Species density: ' + (totalSpecies / input.survey_area_km2).toFixed(1) + ' species/km2')
  const decliningServices = ecosystemServices.filter(s => s.trend === 'Declining')
  if (decliningServices.length > 0) {
    threatAssessment.push(decliningServices.length + ' ecosystem services showing declining trends')
  }
  threatAssessment.push('Primary threats: Habitat fragmentation, Invasive species, Climate change, Overexploitation')

  const ecosystemIntegrity = Math.round((avgShannon / 4.5 * 40 + avgSimpson * 30 + (1 - totalThreatened / totalSpecies) * 30))

  const comparisonToReference: string[] = []
  if (input.reference_condition === 'pristine') {
    comparisonToReference.push('Current species richness: ' + randInt(rng, 50, 85) + '% of pristine reference condition')
    comparisonToReference.push('Functional diversity: ' + randInt(rng, 40, 80) + '% of expected pristine levels')
  } else if (input.reference_condition === 'historical') {
    comparisonToReference.push('Species richness change: ' + randInt(rng, -40, 10) + '% compared to historical baseline')
    comparisonToReference.push('Community composition shift: ' + randInt(rng, 15, 60) + '% turnover from historical state')
  } else {
    comparisonToReference.push('Current condition: ' + randInt(rng, 60, 90) + '% of best available reference site')
    comparisonToReference.push('Recovery potential: ' + randInt(rng, 50, 95) + '% achievable with active restoration')
  }
  comparisonToReference.push('Beta diversity across sites: ' + randFloat(rng, 0.3, 0.8).toFixed(2) + ' (moderate to high heterogeneity)')

  const managementRecommendations: string[] = []
  managementRecommendations.push('Expand protected area network to cover ' + totalEndemic + ' endemic species habitats')
  managementRecommendations.push('Implement species recovery plans for ' + totalThreatened + ' threatened species')
  managementRecommendations.push('Restore degraded habitats to improve Shannon index by target of 0.5')
  managementRecommendations.push('Establish ex-situ conservation for critically endangered endemics')
  managementRecommendations.push('Monitor ' + decliningServices.length + ' declining ecosystem services with quarterly assessments')
  managementRecommendations.push('Control invasive species in ' + randInt(rng, 2, 6) + ' priority zones')

  return {
    assessment_id: assessmentId,
    region: input.region,
    ecosystem_type: input.ecosystem_type,
    survey_area_km2: input.survey_area_km2,
    taxa_records: taxaRecords,
    ecosystem_services: ecosystemServices,
    biodiversity_indices: biodiversityIndices,
    threat_assessment: threatAssessment,
    ecosystem_integrity_score: ecosystemIntegrity,
    comparison_to_reference: comparisonToReference,
    management_recommendations: managementRecommendations,
  }
}

function formatBiodiversityAssessmentReport(r: BiodiversityAssessmentResult): string {
  const lines: string[] = []
  lines.push('## Biodiversity Assessment Report')
  lines.push('')
  lines.push('**Assessment ID:** ' + r.assessment_id + ' | **Region:** ' + r.region + ' | **Ecosystem:** ' + r.ecosystem_type)
  lines.push('**Survey Area:** ' + r.survey_area_km2 + ' km2 | **Ecosystem Integrity Score:** ' + r.ecosystem_integrity_score + '/100')
  lines.push('')
  lines.push('### Biodiversity Indices')
  for (const [k, v] of Object.entries(r.biodiversity_indices)) {
    lines.push('- **' + k.replace(/_/g, ' ').replace(/^\w/, c => c.toUpperCase()) + ':** ' + v)
  }
  lines.push('')
  lines.push('### Taxa Records')
  lines.push('| Group | Species | Endemic | Threatened | Shannon | Simpson | Evenness |')
  lines.push('|-------|---------|---------|------------|---------|---------|----------|')
  for (const t of r.taxa_records) {
    lines.push('| ' + t.group + ' | ' + t.species_count + ' | ' + t.endemic_count + ' | ' + t.threatened_count + ' | ' + t.shannon_index.toFixed(2) + ' | ' + t.simpson_index.toFixed(2) + ' | ' + t.evenness.toFixed(2) + ' |')
  }
  lines.push('')
  lines.push('### Ecosystem Services Valuation')
  lines.push('| Service | Category | Value ($/ha/yr) | Trend | Confidence |')
  lines.push('|---------|----------|-----------------|-------|------------|')
  for (const e of r.ecosystem_services) {
    lines.push('| ' + e.service + ' | ' + e.value_category + ' | $' + e.estimated_value_usd_ha_yr + ' | ' + e.trend + ' | ' + e.confidence + ' |')
  }
  lines.push('')
  lines.push('### Threat Assessment')
  for (const t of r.threat_assessment) lines.push('- ' + t)
  lines.push('')
  lines.push('### Comparison to Reference Condition')
  for (const c of r.comparison_to_reference) lines.push('- ' + c)
  lines.push('')
  lines.push('### Management Recommendations')
  for (const m of r.management_recommendations) lines.push('- [ ] ' + m)
  lines.push('')
  lines.push('> **Disclaimer:** ' + DISCLAIMER)
  return lines.join('\n')
}

/* ─────────────────────────────────────────────
   5. Wildlife Population Modeler
   ───────────────────────────────────────────── */
export interface PopulationModelingInput {
  species: string
  current_population: number
  carrying_capacity: number
  growth_rate: number
  time_horizon_years: number
  model_type: 'exponential' | 'logistic' | 'leslie_matrix' | 'individual_based'
  include_stochasticity: boolean
  harvest_rate: number
  conservation_intervention: 'none' | 'captive_breeding' | 'habitat_restoration' | 'anti_poaching' | 'combined'
}

export interface PopulationProjection {
  year: number
  population: number
  growth_rate: number
  probability_of_decline: number
  extinction_risk: number
  confidence_interval: [number, number]
}

export interface PopulationModelingResult {
  model_id: string
  species: string
  model_type: string
  projections: PopulationProjection[]
  equilibrium_analysis: string[]
  sensitivity_analysis: string[]
  intervention_impact: string[]
  minimum_viable_population: number
  generation_time_years: number
  population_viability_analysis: string[]
  recommendations: string[]
}

function modelPopulation(input: PopulationModelingInput): PopulationModelingResult {
  const rng = createRngFromInput(input)
  const modelId = 'PM-' + randInt(rng, 10000, 99999)

  const projections: PopulationProjection[] = []
  let currentPop = input.current_population
  const K = input.carrying_capacity
  const r = input.growth_rate

  for (let year = 1; year <= input.time_horizon_years; year++) {
    let newPop: number
    if (input.model_type === 'exponential') {
      newPop = currentPop * Math.exp(r * (1 - currentPop / K * 0.1))
    } else if (input.model_type === 'logistic') {
      newPop = currentPop + r * currentPop * (1 - currentPop / K)
    } else {
      newPop = currentPop + r * currentPop * (1 - currentPop / K) * (0.9 + rng() * 0.2)
    }

    // Apply stochasticity
    if (input.include_stochasticity) {
      const envVariance = randFloat(rng, 0.05, 0.2)
      newPop = newPop * (1 + (rng() - 0.5) * envVariance)
    }

    // Apply harvest
    newPop = newPop * (1 - input.harvest_rate)

    // Apply conservation intervention
    if (input.conservation_intervention === 'captive_breeding') newPop += randInt(rng, 5, 30)
    else if (input.conservation_intervention === 'habitat_restoration') newPop *= (1 + randFloat(rng, 0.01, 0.05))
    else if (input.conservation_intervention === 'anti_poaching') newPop *= (1 + randFloat(rng, 0.02, 0.08))
    else if (input.conservation_intervention === 'combined') newPop = newPop * (1 + randFloat(rng, 0.05, 0.15)) + randInt(rng, 5, 20)

    newPop = Math.max(0, Math.round(newPop))
    const actualGrowth = currentPop > 0 ? (newPop - currentPop) / currentPop : 0
    const ciLow = Math.round(newPop * (0.8 + rng() * 0.1))
    const ciHigh = Math.round(newPop * (1.1 + rng() * 0.2))

    projections.push({
      year: 2025 + year,
      population: newPop,
      growth_rate: Math.round(actualGrowth * 10000) / 10000,
      probability_of_decline: actualGrowth < 0 ? randFloat(rng, 0.3, 0.9) : randFloat(rng, 0.05, 0.3),
      extinction_risk: newPop < 50 ? randFloat(rng, 0.1, 0.8) : newPop < 200 ? randFloat(rng, 0.01, 0.2) : randFloat(rng, 0.001, 0.05),
      confidence_interval: [ciLow, ciHigh],
    })

    currentPop = newPop
  }

  const equilibriumAnalysis: string[] = []
  equilibriumAnalysis.push('Carrying capacity (K): ' + K + ' individuals')
  equilibriumAnalysis.push('Current population: ' + input.current_population + ' (' + (input.current_population / K * 100).toFixed(1) + '% of K)')
  equilibriumAnalysis.push('Deterministic equilibrium: ' + K + ' (logistic) or unbounded (exponential)')
  if (projections[projections.length - 1].population > input.current_population) {
    equilibriumAnalysis.push('Projected trend: Population recovery expected over ' + input.time_horizon_years + ' years')
  } else {
    equilibriumAnalysis.push('Projected trend: Population decline expected without intervention')
  }
  equilibriumAnalysis.push('Allee effect threshold estimated at: ' + randInt(rng, 20, 100) + ' individuals')

  const sensitivityAnalysis: string[] = []
  sensitivityAnalysis.push('Growth rate sensitivity: +/-10% change alters final population by ' + randInt(rng, 15, 45) + '%')
  sensitivityAnalysis.push('Carrying capacity sensitivity: Primary limiting factor for long-term viability')
  sensitivityAnalysis.push('Environmental stochasticity: ' + (input.include_stochasticity ? 'High impact on small populations' : 'Not modeled'))
  sensitivityAnalysis.push('Harvest rate impact: Current rate of ' + (input.harvest_rate * 100).toFixed(1) + '% reduces growth by ' + randInt(rng, 5, 30) + '%')
  sensitivityAnalysis.push('Density dependence: Logistic regulation prevents overshoot of K')

  const interventionImpact: string[] = []
  if (input.conservation_intervention !== 'none') {
    const baselineFinal = input.current_population * Math.pow(1 + r * 0.5, input.time_horizon_years)
    const interventionFinal = projections[projections.length - 1].population
    const improvement = ((interventionFinal - baselineFinal) / baselineFinal * 100)
    interventionImpact.push('Intervention type: ' + input.conservation_intervention)
    interventionImpact.push('Projected improvement over baseline: ' + improvement.toFixed(1) + '%')
    interventionImpact.push('Additional individuals supported: ' + Math.round(interventionFinal - baselineFinal))
    interventionImpact.push('Cost-effectiveness: $' + randInt(rng, 100, 5000) + ' per additional individual')
  } else {
    interventionImpact.push('No conservation intervention modeled - baseline scenario only')
    interventionImpact.push('Recommended: Implement combined intervention for maximum impact')
    interventionImpact.push('Without intervention, extinction risk increases ' + randInt(rng, 2, 10) + 'x over ' + input.time_horizon_years + ' years')
  }

  const mvp = randInt(rng, 50, 500)
  const generationTime = randFloat(rng, 2, 25)

  const pva: string[] = []
  pva.push('Minimum Viable Population (MVP): ' + mvp + ' individuals (95% persistence over 100 years)')
  pva.push('Generation time: ' + generationTime.toFixed(1) + ' years')
  pva.push('Effective population size (Ne): ' + Math.round(input.current_population * randFloat(rng, 0.1, 0.4)) + ' (' + (randFloat(rng, 0.1, 0.4) * 100).toFixed(0) + '% of census)')
  pva.push('Inbreeding coefficient increase: ' + randFloat(rng, 0.1, 2.0).toFixed(2) + '% per generation')
  pva.push('Genetic diversity retention: ' + randInt(rng, 70, 95) + '% over 100 years at current Ne')

  const recommendations: string[] = []
  if (input.current_population < mvp) {
    recommendations.push('CRITICAL: Population below MVP - immediate genetic rescue and captive breeding recommended')
  }
  recommendations.push('Maintain population above ' + mvp + ' individuals for long-term genetic viability')
  recommendations.push('Implement ' + (input.conservation_intervention === 'none' ? 'combined conservation intervention' : input.conservation_intervention) + ' strategy')
  recommendations.push('Monitor population annually with ' + randInt(rng, 5, 20) + '% precision target')
  recommendations.push('Establish meta-population connectivity to reduce isolation effects')
  recommendations.push('Maintain genetic management with studbook and planned breeding')

  return {
    model_id: modelId,
    species: input.species,
    model_type: input.model_type,
    projections,
    equilibrium_analysis: equilibriumAnalysis,
    sensitivity_analysis: sensitivityAnalysis,
    intervention_impact: interventionImpact,
    minimum_viable_population: mvp,
    generation_time_years: generationTime,
    population_viability_analysis: pva,
    recommendations,
  }
}

function formatPopulationModelingReport(r: PopulationModelingResult): string {
  const lines: string[] = []
  lines.push('## Wildlife Population Modeling Report')
  lines.push('')
  lines.push('**Model ID:** ' + r.model_id + ' | **Species:** ' + r.species + ' | **Model Type:** ' + r.model_type)
  lines.push('**MVP:** ' + r.minimum_viable_population + ' | **Generation Time:** ' + r.generation_time_years.toFixed(1) + ' years')
  lines.push('')
  lines.push('### Population Projections')
  lines.push('| Year | Population | Growth Rate | Decline Prob | Extinction Risk | CI |')
  lines.push('|------|------------|-------------|--------------|-----------------|-----|')
  for (const p of r.projections) {
    lines.push('| ' + p.year + ' | ' + p.population + ' | ' + (p.growth_rate >= 0 ? '+' : '') + (p.growth_rate * 100).toFixed(2) + '% | ' + (p.probability_of_decline * 100).toFixed(0) + '% | ' + (p.extinction_risk * 100).toFixed(1) + '% | [' + p.confidence_interval[0] + '-' + p.confidence_interval[1] + '] |')
  }
  lines.push('')
  lines.push('### Equilibrium Analysis')
  for (const e of r.equilibrium_analysis) lines.push('- ' + e)
  lines.push('')
  lines.push('### Sensitivity Analysis')
  for (const s of r.sensitivity_analysis) lines.push('- **' + s + '**')
  lines.push('')
  lines.push('### Intervention Impact')
  for (const i of r.intervention_impact) lines.push('- ' + i)
  lines.push('')
  lines.push('### Population Viability Analysis')
  for (const p of r.population_viability_analysis) lines.push('- ' + p)
  lines.push('')
  lines.push('### Recommendations')
  for (const rec of r.recommendations) lines.push('- [ ] ' + rec)
  lines.push('')
  lines.push('> **Disclaimer:** ' + DISCLAIMER)
  return lines.join('\n')
}

/* ─────────────────────────────────────────────
   6. Migration Tracker
   ───────────────────────────────────────────── */
export interface MigrationTrackerInput {
  species: string
  tracking_method: 'GPS_collar' | 'satellite_tag' | 'geolocator' | 'PIT_tag' | 'acoustic' | 'citizen_science'
  study_duration_months: number
  num_tracked_individuals: number
  region: string
  include_stopover_sites: boolean
  climate_scenario: 'current' | 'warming_1.5C' | 'warming_2C' | 'warming_3C'
}

export interface MigrationWaypoint {
  site_id: string
  name: string
  coordinates: [number, number]
  arrival_date: string
  departure_date: string
  duration_days: number
  habitat_type: string
  threat_level: 'Low' | 'Medium' | 'High' | 'Critical'
  protection_status: string
}

export interface MigrationRoute {
  route_id: string
  start_location: string
  end_location: string
  total_distance_km: number
  duration_days: number
  max_altitude_m: number
  waypoints: MigrationWaypoint[]
  barriers_encountered: string[]
  climate_vulnerability: 'Low' | 'Medium' | 'High'
}

export interface MigrationTrackerResult {
  tracker_id: string
  species: string
  tracking_method: string
  routes: MigrationRoute[]
  stopover_analysis: string[]
  timing_analysis: string[]
  threats_along_route: string[]
  corridor_recommendations: string[]
  climate_impact_assessment: string[]
  population_connectivity: string[]
}

function trackMigration(input: MigrationTrackerInput): MigrationTrackerResult {
  const rng = createRngFromInput(input)
  const trackerId = 'MT-' + randInt(rng, 10000, 99999)

  const routeCount = randInt(rng, 1, Math.min(5, input.num_tracked_individuals))
  const routes: MigrationRoute[] = []

  for (let i = 0; i < routeCount; i++) {
    const waypointCount = randInt(rng, 3, 10)
    const waypoints: MigrationWaypoint[] = []

    for (let j = 0; j < waypointCount; j++) {
      const arrivalMonth = randInt(rng, 1, 12)
      const duration = randInt(rng, 1, 45)
      waypoints.push({
        site_id: 'S' + String(j + 1).padStart(3, '0'),
        name: pick(rng, ['Wetland Reserve', 'Coastal Bay', 'Mountain Pass', 'River Delta', 'Grassland Plain', 'Forest Edge', 'Lake Shore', 'Estuary', 'Island Stopover', 'Agricultural Field']),
        coordinates: [randFloat(rng, -180, 180), randFloat(rng, -90, 90)],
        arrival_date: '2025-' + String(arrivalMonth).padStart(2, '0') + '-' + String(randInt(rng, 1, 28)).padStart(2, '0'),
        departure_date: '2025-' + String(Math.min(12, arrivalMonth + Math.ceil(duration / 30))).padStart(2, '0') + '-' + String(randInt(rng, 1, 28)).padStart(2, '0'),
        duration_days: duration,
        habitat_type: pick(rng, ['Wetland', 'Grassland', 'Coastal', 'Forest', 'Agricultural', 'Freshwater', 'Marine']),
        threat_level: pick(rng, ['Low', 'Medium', 'High', 'Critical'] as const),
        protection_status: pick(rng, ['Protected', 'Partial', 'Unprotected', 'Protected', 'Partial']),
      })
    }

    routes.push({
      route_id: 'R' + String(i + 1).padStart(3, '0'),
      start_location: pick(rng, ['Breeding Ground A', 'Northern Range', 'Summer Habitat', 'Arctic Tundra', 'Highland Plateau']),
      end_location: pick(rng, ['Wintering Ground B', 'Southern Range', 'Winter Habitat', 'Tropical Lowland', 'Coastal Wetland']),
      total_distance_km: randInt(rng, 500, 20000),
      duration_days: randInt(rng, 14, 180),
      max_altitude_m: randInt(rng, 500, 9000),
      waypoints,
      barriers_encountered: pickN(rng, ['Major Highway', 'Wind Farm', 'Urban Area', 'Dam', 'Fence Line', 'Agricultural Expansion', 'Power Lines', 'Industrial Zone'], randInt(rng, 1, 4)),
      climate_vulnerability: pick(rng, ['Low', 'Medium', 'High'] as const),
    })
  }

  const stopoverAnalysis: string[] = []
  if (input.include_stopover_sites) {
    const allWaypoints = routes.flatMap(r => r.waypoints)
    const criticalStopovers = allWaypoints.filter(w => w.threat_level === 'Critical' || w.threat_level === 'High')
    stopoverAnalysis.push('Total stopover sites identified: ' + allWaypoints.length + ' across ' + routes.length + ' routes')
    stopoverAnalysis.push('Critical/High threat stopovers: ' + criticalStopovers.length + ' requiring immediate protection')
    stopoverAnalysis.push('Average stopover duration: ' + Math.round(allWaypoints.reduce((s, w) => s + w.duration_days, 0) / allWaypoints.length) + ' days')
    const unprotected = allWaypoints.filter(w => w.protection_status === 'Unprotected')
    if (unprotected.length > 0) {
      stopoverAnalysis.push('UNPROTECTED stopovers: ' + unprotected.length + ' sites need protection status urgently')
    }
  }

  const timingAnalysis: string[] = []
  timingAnalysis.push('Tracking duration: ' + input.study_duration_months + ' months with ' + input.num_tracked_individuals + ' individuals')
  timingAnalysis.push('Peak migration period: ' + pick(rng, ['March-April', 'September-October', 'November-December', 'January-February']))
  timingAnalysis.push('Average migration speed: ' + randInt(rng, 30, 200) + ' km/day')
  timingAnalysis.push('Nocturnal migration proportion: ' + randInt(rng, 40, 90) + '%')
  if (input.climate_scenario !== 'current') {
    timingAnalysis.push('Phenological shift under ' + input.climate_scenario + ': ' + randInt(rng, 5, 25) + ' days earlier arrival')
  }

  const threatsAlongRoute: string[] = []
  const allBarriers = routes.flatMap(r => r.barriers_encountered)
  const barrierCounts: Record<string, number> = {}
  for (const b of allBarriers) barrierCounts[b] = (barrierCounts[b] || 0) + 1
  for (const [barrier, count] of Object.entries(barrierCounts)) {
    threatsAlongRoute.push(barrier + ': encountered on ' + count + ' routes')
  }
  threatsAlongRoute.push('Habitat loss at stopover sites: ' + randInt(rng, 10, 40) + '% reduction over past decade')
  threatsAlongRoute.push('Hunting pressure at ' + randInt(rng, 1, 5) + ' stopover locations')
  threatsAlongRoute.push('Light pollution disrupting nocturnal migration at ' + randInt(rng, 2, 8) + ' sites')

  const corridorRecommendations: string[] = []
  corridorRecommendations.push('Establish ' + routes.length + ' formal migration corridors with international protection')
  corridorRecommendations.push('Protect ' + randInt(rng, 3, 12) + ' critical stopover sites along primary routes')
  corridorRecommendations.push('Install wildlife crossings at ' + (barrierCounts['Major Highway'] || 0) + ' highway barrier points')
  corridorRecommendations.push('Create buffer zones of ' + randInt(rng, 1, 5) + ' km around key stopover wetlands')
  corridorRecommendations.push('Coordinate international conservation agreements across ' + randInt(rng, 2, 8) + ' range states')

  const climateImpactAssessment: string[] = []
  if (input.climate_scenario === 'warming_1.5C') {
    climateImpactAssessment.push('1.5C scenario: ' + randInt(rng, 5, 15) + '% shift in breeding range expected')
    climateImpactAssessment.push('Stopover site suitability: ' + randInt(rng, 80, 95) + '% maintained')
  } else if (input.climate_scenario === 'warming_2C') {
    climateImpactAssessment.push('2C scenario: ' + randInt(rng, 15, 30) + '% shift in breeding range expected')
    climateImpactAssessment.push('Stopover site suitability: ' + randInt(rng, 60, 80) + '% maintained')
    climateImpactAssessment.push('Phenological mismatch risk: Moderate to High')
  } else if (input.climate_scenario === 'warming_3C') {
    climateImpactAssessment.push('3C scenario: ' + randInt(rng, 30, 60) + '% shift in breeding range expected')
    climateImpactAssessment.push('Stopover site suitability: ' + randInt(rng, 30, 60) + '% maintained')
    climateImpactAssessment.push('Phenological mismatch risk: Severe - food availability timing disrupted')
  } else {
    climateImpactAssessment.push('Current climate: Migration timing and routes within historical norms')
  }
  climateImpactAssessment.push('Sea level rise impact on coastal stopovers: ' + randInt(rng, 5, 25) + '% habitat loss')

  const populationConnectivity: string[] = []
  populationConnectivity.push('Tracked individuals represent ' + randInt(rng, 1, 15) + '% of estimated source population')
  populationConnectivity.push('Route fidelity: ' + randInt(rng, 60, 95) + '% of individuals return to same sites')
  populationConnectivity.push('Genetic exchange between populations: ' + pick(rng, ['High', 'Moderate', 'Low']))
  populationConnectivity.push('Meta-population structure: ' + randInt(rng, 2, 6) + ' subpopulations connected by migration')
  populationConnectivity.push('Isolation risk: ' + (routes.length > 2 ? 'Low - multiple routes provide redundancy' : 'High - limited route diversity'))

  return {
    tracker_id: trackerId,
    species: input.species,
    tracking_method: input.tracking_method,
    routes,
    stopover_analysis: stopoverAnalysis,
    timing_analysis: timingAnalysis,
    threats_along_route: threatsAlongRoute,
    corridor_recommendations: corridorRecommendations,
    climate_impact_assessment: climateImpactAssessment,
    population_connectivity: populationConnectivity,
  }
}

function formatMigrationTrackerReport(r: MigrationTrackerResult): string {
  const lines: string[] = []
  lines.push('## Migration Tracking Report')
  lines.push('')
  lines.push('**Tracker ID:** ' + r.tracker_id + ' | **Species:** ' + r.species + ' | **Method:** ' + r.tracking_method)
  lines.push('')
  for (const route of r.routes) {
    lines.push('### Route ' + route.route_id + ': ' + route.start_location + ' to ' + route.end_location)
    lines.push('**Distance:** ' + route.total_distance_km + ' km | **Duration:** ' + route.duration_days + ' days | **Max Altitude:** ' + route.max_altitude_m + ' m')
    lines.push('| Site | Habitat | Arrival | Duration | Threat | Protection |')
    lines.push('|------|---------|---------|----------|--------|------------|')
    for (const w of route.waypoints) {
      lines.push('| ' + w.name + ' | ' + w.habitat_type + ' | ' + w.arrival_date + ' | ' + w.duration_days + 'd | ' + w.threat_level + ' | ' + w.protection_status + ' |')
    }
    lines.push('')
    lines.push('**Barriers:** ' + route.barriers_encountered.join(', ') + ' | **Climate Vulnerability:** ' + route.climate_vulnerability)
    lines.push('')
  }
  if (r.stopover_analysis.length > 0) {
    lines.push('### Stopover Site Analysis')
    for (const s of r.stopover_analysis) lines.push('- ' + s)
    lines.push('')
  }
  lines.push('### Timing Analysis')
  for (const t of r.timing_analysis) lines.push('- ' + t)
  lines.push('')
  lines.push('### Threats Along Route')
  for (const t of r.threats_along_route) lines.push('- **' + t + '**')
  lines.push('')
  lines.push('### Corridor Recommendations')
  for (const c of r.corridor_recommendations) lines.push('- [ ] ' + c)
  lines.push('')
  lines.push('### Climate Impact Assessment')
  for (const c of r.climate_impact_assessment) lines.push('- ' + c)
  lines.push('')
  lines.push('### Population Connectivity')
  for (const p of r.population_connectivity) lines.push('- ' + p)
  lines.push('')
  lines.push('> **Disclaimer:** ' + DISCLAIMER)
  return lines.join('\n')
}

/* ─────────────────────────────────────────────
   7. Camera Trap Analyzer
   ───────────────────────────────────────────── */
export interface CameraTrapInput {
  deployment_region: string
  num_cameras: number
  deployment_duration_days: number
  target_species: string[]
  habitat_type: string
  include_species_id_accuracy: boolean
  occupancy_modeling: boolean
}

export interface CameraTrapDetection {
  species: string
  detection_count: number
  detection_rate_per_100trap_nights: number
  occupancy_probability: number
  activity_pattern: 'Diurnal' | 'Nocturnal' | 'Crepuscular' | 'Cathemeral'
  group_size_avg: number
  confidence: number
  independent_events: number
}

export interface CameraTrapStation {
  station_id: string
  coordinates: [number, number]
  total_images: number
  species_detected: number
  detection_rate: number
  operational_days: number
  malfunction_days: number
  top_species: string[]
}

export interface CameraTrapResult {
  analysis_id: string
  deployment_region: string
  total_images_captured: number
  total_species_detected: number
  trap_nights: number
  detections: CameraTrapDetection[]
  stations: CameraTrapStation[]
  species_richness_estimate: number
  rarefaction_curve: string[]
  detection_gaps: string[]
  occupancy_results: string[]
  recommendations: string[]
}

function analyzeCameraTraps(input: CameraTrapInput): CameraTrapResult {
  const rng = createRngFromInput(input)
  const analysisId = 'CT-' + randInt(rng, 10000, 99999)

  const trapNights = input.num_cameras * input.deployment_duration_days
  const speciesPool = input.target_species.length > 0 ? input.target_species : [
    'Leopard', 'Elephant', 'Buffalo', 'Duiker', 'Civet', 'Mongoose', 'Pangolin',
    'Gorilla', 'Chimpanzee', 'Forest Hog', 'Bongo', 'Golden Cat', 'Jackal', 'Hyena'
  ]

  const detectionCount = randInt(rng, Math.min(5, speciesPool.length), Math.min(speciesPool.length, 20))
  const selectedSpecies = pickN(rng, speciesPool, detectionCount)
  const detections: CameraTrapDetection[] = []

  for (const sp of selectedSpecies) {
    const detectionCount = randInt(rng, 3, 200)
    const rate = detectionCount / trapNights * 100
    detections.push({
      species: sp,
      detection_count: detectionCount,
      detection_rate_per_100trap_nights: Math.round(rate * 100) / 100,
      occupancy_probability: randFloat(rng, 0.1, 0.95),
      activity_pattern: pick(rng, ['Diurnal', 'Nocturnal', 'Crepuscular', 'Cathemeral'] as const),
      group_size_avg: randFloat(rng, 1, 8),
      confidence: randFloat(rng, 0.7, 0.99),
      independent_events: Math.round(detectionCount * randFloat(rng, 0.3, 0.7)),
    })
  }

  detections.sort((a, b) => b.detection_count - a.detection_count)

  const stationCount = Math.min(input.num_cameras, randInt(rng, 5, 20))
  const stations: CameraTrapStation[] = []
  for (let i = 0; i < stationCount; i++) {
    const operationalDays = input.deployment_duration_days - randInt(rng, 0, 15)
    stations.push({
      station_id: 'CAM-' + String(i + 1).padStart(3, '0'),
      coordinates: [randFloat(rng, -180, 180), randFloat(rng, -90, 90)],
      total_images: randInt(rng, 100, 10000),
      species_detected: randInt(rng, 1, detections.length),
      detection_rate: randFloat(rng, 0.5, 15),
      operational_days: operationalDays,
      malfunction_days: input.deployment_duration_days - operationalDays,
      top_species: pickN(rng, detections.map(d => d.species), randInt(rng, 1, 3)),
    })
  }

  const totalImages = stations.reduce((s, st) => s + st.total_images, 0)
  const speciesRichnessEstimate = Math.round(detections.length * randFloat(rng, 1.1, 1.5))

  const rarefactionCurve: string[] = []
  rarefactionCurve.push('Observed species: ' + detections.length + ' from ' + trapNights + ' trap-nights')
  rarefactionCurve.push('Estimated total species (Chao1): ' + speciesRichnessEstimate)
  rarefactionCurve.push('Sampling completeness: ' + randInt(rng, 60, 90) + '%')
  rarefactionCurve.push('Asymptote reached: ' + (rng() > 0.5 ? 'Yes - sampling adequate' : 'No - additional sampling recommended'))
  rarefactionCurve.push('Rare species (< 10 detections): ' + detections.filter(d => d.detection_count < 10).length)

  const detectionGaps: string[] = []
  const lowDetection = detections.filter(d => d.detection_rate_per_100trap_nights < 1)
  if (lowDetection.length > 0) {
    detectionGaps.push('Low detection rate species: ' + lowDetection.length + ' (< 1 per 100 trap-nights)')
  }
  const malfunctionStations = stations.filter(s => s.malfunction_days > 5)
  if (malfunctionStations.length > 0) {
    detectionGaps.push(malfunctionStations.length + ' stations had > 5 malfunction days - data gaps possible')
  }
  detectionGaps.push('Spatial coverage gap: ' + randInt(rng, 10, 40) + '% of target area not covered')
  detectionGaps.push('Temporal gap: Night coverage ' + randInt(rng, 70, 100) + '% | Day coverage ' + randInt(rng, 60, 100) + '%')

  const occupancyResults: string[] = []
  if (input.occupancy_modeling) {
    const highOccupancy = detections.filter(d => d.occupancy_probability >= 0.7)
    const lowOccupancy = detections.filter(d => d.occupancy_probability < 0.4)
    occupancyResults.push('High occupancy (Psi >= 0.7): ' + highOccupancy.length + ' species widely distributed')
    occupancyResults.push('Low occupancy (Psi < 0.4): ' + lowOccupancy.length + ' species rare or localized')
    occupancyResults.push('Mean detection probability (p): ' + randFloat(rng, 0.1, 0.5).toFixed(2))
    occupancyResults.push('Best covariate for occupancy: ' + pick(rng, ['Distance to water', 'Forest cover', 'Human disturbance', 'Elevation', 'Prey density']))
  }

  const recommendations: string[] = []
  recommendations.push('Add ' + randInt(rng, 5, 20) + ' camera stations to cover spatial gaps')
  recommendations.push('Extend deployment by ' + randInt(rng, 30, 90) + ' days for rare species documentation')
  recommendations.push('Repair/replace ' + malfunctionStations.length + ' malfunctioning stations')
  recommendations.push('Focus on ' + lowDetection.length + ' low-detection species for targeted surveys')
  recommendations.push('Implement AI-powered real-time species classification for ' + totalImages + ' images')
  recommendations.push('Standardize camera height/angle across all ' + input.num_cameras + ' stations')

  return {
    analysis_id: analysisId,
    deployment_region: input.deployment_region,
    total_images_captured: totalImages,
    total_species_detected: detections.length,
    trap_nights: trapNights,
    detections,
    stations,
    species_richness_estimate: speciesRichnessEstimate,
    rarefaction_curve: rarefactionCurve,
    detection_gaps: detectionGaps,
    occupancy_results: occupancyResults,
    recommendations,
  }
}

function formatCameraTrapReport(r: CameraTrapResult): string {
  const lines: string[] = []
  lines.push('## Camera Trap Analysis Report')
  lines.push('')
  lines.push('**Analysis ID:** ' + r.analysis_id + ' | **Region:** ' + r.deployment_region)
  lines.push('**Total Images:** ' + r.total_images_captured + ' | **Species Detected:** ' + r.total_species_detected + ' | **Trap Nights:** ' + r.trap_nights)
  lines.push('**Estimated Species Richness:** ' + r.species_richness_estimate)
  lines.push('')
  lines.push('### Species Detections')
  lines.push('| Species | Detections | Rate/100tn | Occupancy | Activity | Group Size | Confidence |')
  lines.push('|---------|------------|------------|-----------|----------|------------|------------|')
  for (const d of r.detections) {
    lines.push('| ' + d.species + ' | ' + d.detection_count + ' | ' + d.detection_rate_per_100trap_nights.toFixed(2) + ' | ' + d.occupancy_probability.toFixed(2) + ' | ' + d.activity_pattern + ' | ' + d.group_size_avg.toFixed(1) + ' | ' + (d.confidence * 100).toFixed(0) + '% |')
  }
  lines.push('')
  lines.push('### Station Performance')
  lines.push('| Station | Images | Species | Rate | Operational Days | Malfunction |')
  lines.push('|---------|--------|---------|------|------------------|-------------|')
  for (const s of r.stations) {
    lines.push('| ' + s.station_id + ' | ' + s.total_images + ' | ' + s.species_detected + ' | ' + s.detection_rate.toFixed(1) + ' | ' + s.operational_days + ' | ' + s.malfunction_days + ' |')
  }
  lines.push('')
  lines.push('### Rarefaction Analysis')
  for (const rc of r.rarefaction_curve) lines.push('- ' + rc)
  lines.push('')
  lines.push('### Detection Gaps')
  for (const dg of r.detection_gaps) lines.push('- **' + dg + '**')
  lines.push('')
  if (r.occupancy_results.length > 0) {
    lines.push('### Occupancy Modeling Results')
    for (const o of r.occupancy_results) lines.push('- ' + o)
    lines.push('')
  }
  lines.push('### Recommendations')
  for (const rec of r.recommendations) lines.push('- [ ] ' + rec)
  lines.push('')
  lines.push('> **Disclaimer:** ' + DISCLAIMER)
  return lines.join('\n')
}

/* ─────────────────────────────────────────────
   8. Conservation ROI Calculator
   ───────────────────────────────────────────── */
export interface ConservationROIInput {
  project_name: string
  total_investment_usd: number
  project_duration_years: number
  conservation_type: 'species_recovery' | 'habitat_restoration' | 'anti_poaching' | 'community_conservation' | 'protected_area' | 'mixed'
  target_species_count: number
  area_protected_km2: number
  community_beneficiaries: number
  carbon_offset_tons: number
  ecotourism_potential: 'low' | 'medium' | 'high'
  discount_rate_percent: number
}

export interface ROIBenefitCategory {
  category: string
  annual_value_usd: number
  total_value_usd: number
  methodology: string
  confidence: 'High' | 'Medium' | 'Low'
}

export interface ROIScenario {
  scenario: string
  npv_usd: number
  benefit_cost_ratio: number
  payback_period_years: number
  irr_percent: number
  probability_of_success: number
}

export interface ConservationROIResult {
  calculation_id: string
  project_name: string
  conservation_type: string
  total_investment_usd: number
  benefit_categories: ROIBenefitCategory[]
  scenarios: ROIScenario[]
  total_benefits_usd: number
  net_present_value: number
  benefit_cost_ratio: number
  cost_effectiveness_per_species: number
  cost_effectiveness_per_km2: number
  social_return_metrics: string[]
  risk_factors: string[]
  investment_recommendations: string[]
}

function calculateConservationROI(input: ConservationROIInput): ConservationROIResult {
  const rng = createRngFromInput(input)
  const calculationId = 'ROI-' + randInt(rng, 10000, 99999)

  const annualEcosystemValue = input.area_protected_km2 * randFloat(rng, 50, 500)
  const annualCarbonValue = input.carbon_offset_tons * randFloat(rng, 10, 80)
  const annualEcotourismValue = input.ecotourism_potential === 'high' ? randFloat(rng, 50000, 500000) :
                                  input.ecotourism_potential === 'medium' ? randFloat(rng, 10000, 100000) :
                                  randFloat(rng, 1000, 10000)
  const annualCommunityValue = input.community_beneficiaries * randFloat(rng, 50, 500)
  const annualExistenceValue = input.target_species_count * randFloat(rng, 1000, 50000)

  const benefitCategories: ROIBenefitCategory[] = [
    { category: 'Ecosystem Services', annual_value_usd: annualEcosystemValue, total_value_usd: annualEcosystemValue * input.project_duration_years, methodology: 'TEEB Ecosystem Services Valuation', confidence: 'Medium' },
    { category: 'Carbon Sequestration', annual_value_usd: annualCarbonValue, total_value_usd: annualCarbonValue * input.project_duration_years, methodology: 'Social Cost of Carbon ($51/ton)', confidence: 'High' },
    { category: 'Ecotourism Revenue', annual_value_usd: annualEcotourismValue, total_value_usd: annualEcotourismValue * input.project_duration_years, methodology: 'Travel Cost Method', confidence: 'Medium' },
    { category: 'Community Livelihoods', annual_value_usd: annualCommunityValue, total_value_usd: annualCommunityValue * input.project_duration_years, methodology: 'Contingent Valuation', confidence: 'Low' },
    { category: 'Existence/Bequest Value', annual_value_usd: annualExistenceValue, total_value_usd: annualExistenceValue * input.project_duration_years, methodology: 'Stated Preference (CVM)', confidence: 'Low' },
    { category: 'Avoided Degradation Cost', annual_value_usd: annualEcosystemValue * 0.3, total_value_usd: annualEcosystemValue * 0.3 * input.project_duration_years, methodology: 'Replacement Cost Method', confidence: 'Medium' },
  ]

  const totalBenefits = benefitCategories.reduce((s, b) => s + b.total_value_usd, 0)
  const discountRate = input.discount_rate_percent / 100
  const npvBenefits = benefitCategories.reduce((s, b) => s + b.annual_value_usd * (1 - Math.pow(1 + discountRate, -input.project_duration_years)) / discountRate, 0)
  const npv = npvBenefits - input.total_investment_usd
  const bcRatio = npvBenefits / input.total_investment_usd

  const scenarios: ROIScenario[] = [
    {
      scenario: 'Optimistic (high benefits, low costs)',
      npv_usd: Math.round(npv * randFloat(rng, 1.5, 3.0)),
      benefit_cost_ratio: Math.round(bcRatio * randFloat(rng, 1.5, 3.0) * 100) / 100,
      payback_period_years: Math.round(input.project_duration_years * randFloat(rng, 0.2, 0.5) * 10) / 10,
      irr_percent: Math.round((discountRate + randFloat(rng, 0.05, 0.2)) * 10000) / 100,
      probability_of_success: randFloat(rng, 0.6, 0.9),
    },
    {
      scenario: 'Expected (most likely)',
      npv_usd: Math.round(npv),
      benefit_cost_ratio: Math.round(bcRatio * 100) / 100,
      payback_period_years: Math.round(input.project_duration_years * randFloat(rng, 0.4, 0.7) * 10) / 10,
      irr_percent: Math.round((discountRate + randFloat(rng, 0.02, 0.1)) * 10000) / 100,
      probability_of_success: randFloat(rng, 0.4, 0.7),
    },
    {
      scenario: 'Pessimistic (low benefits, high costs)',
      npv_usd: Math.round(npv * randFloat(rng, -0.5, 0.5)),
      benefit_cost_ratio: Math.round(bcRatio * randFloat(rng, 0.3, 0.8) * 100) / 100,
      payback_period_years: Math.round(input.project_duration_years * randFloat(rng, 0.7, 1.2) * 10) / 10,
      irr_percent: Math.round((discountRate - randFloat(rng, 0.01, 0.05)) * 10000) / 100,
      probability_of_success: randFloat(rng, 0.2, 0.5),
    },
  ]

  const costPerSpecies = input.target_species_count > 0 ? Math.round(input.total_investment_usd / input.target_species_count) : 0
  const costPerKm2 = input.area_protected_km2 > 0 ? Math.round(input.total_investment_usd / input.area_protected_km2) : 0

  const socialReturnMetrics: string[] = []
  socialReturnMetrics.push('Social Return on Investment (SROI): ' + (bcRatio * randFloat(rng, 1.5, 3.0)).toFixed(1) + ':1')
  socialReturnMetrics.push('Community beneficiaries: ' + input.community_beneficiaries + ' people')
  socialReturnMetrics.push('Cost per beneficiary: $' + Math.round(input.total_investment_usd / Math.max(1, input.community_beneficiaries)))
  socialReturnMetrics.push('Jobs created: ' + randInt(rng, 10, 200) + ' direct + ' + randInt(rng, 20, 500) + ' indirect')
  socialReturnMetrics.push('Carbon return: $' + Math.round(annualCarbonValue / Math.max(1, input.carbon_offset_tons)) + ' per ton CO2 sequestered')

  const riskFactors: string[] = []
  riskFactors.push('Political/Regulatory risk: ' + pick(rng, ['Low', 'Medium', 'High']))
  riskFactors.push('Climate change impact on project outcomes: ' + pick(rng, ['Low', 'Medium', 'High']))
  riskFactors.push('Community acceptance risk: ' + pick(rng, ['Low', 'Medium', 'High']))
  riskFactors.push('Funding continuity risk: ' + pick(rng, ['Low', 'Medium', 'High']))
  riskFactors.push('Species recovery uncertainty: ' + randInt(rng, 20, 60) + '% probability of not meeting targets')
  riskFactors.push('Market risk for carbon credits: Price volatility +/-' + randInt(rng, 20, 50) + '%')

  const investmentRecommendations: string[] = []
  if (bcRatio >= 2) {
    investmentRecommendations.push('STRONG INVEST: BCR of ' + bcRatio.toFixed(1) + ' indicates excellent return - prioritize funding')
  } else if (bcRatio >= 1) {
    investmentRecommendations.push('VIABLE: BCR of ' + bcRatio.toFixed(1) + ' is positive - recommend investment with risk mitigation')
  } else {
    investmentRecommendations.push('MARGINAL: BCR below 1.0 - consider restructuring or scaling up for efficiency')
  }
  investmentRecommendations.push('Diversify funding across ' + benefitCategories.length + ' benefit streams for resilience')
  investmentRecommendations.push('Structure as ' + randInt(rng, 3, 10) + '-year phased investment with annual review gates')
  investmentRecommendations.push('Leverage carbon credits for ' + Math.round(annualCarbonValue / input.total_investment_usd * 100) + '% of annual costs')
  investmentRecommendations.push('Establish endowment fund of $' + Math.round(input.total_investment_usd * randFloat(rng, 0.1, 0.3)) + ' for long-term sustainability')
  investmentRecommendations.push('Seek blended finance: ' + randInt(rng, 30, 70) + '% commercial + ' + randInt(rng, 30, 70) + '% philanthropic')

  return {
    calculation_id: calculationId,
    project_name: input.project_name,
    conservation_type: input.conservation_type,
    total_investment_usd: input.total_investment_usd,
    benefit_categories: benefitCategories,
    scenarios,
    total_benefits_usd: Math.round(totalBenefits),
    net_present_value: Math.round(npv),
    benefit_cost_ratio: Math.round(bcRatio * 100) / 100,
    cost_effectiveness_per_species: costPerSpecies,
    cost_effectiveness_per_km2: costPerKm2,
    social_return_metrics: socialReturnMetrics,
    risk_factors: riskFactors,
    investment_recommendations: investmentRecommendations,
  }
}

function formatConservationROIReport(r: ConservationROIResult): string {
  const lines: string[] = []
  lines.push('## Conservation ROI Analysis Report')
  lines.push('')
  lines.push('**Calculation ID:** ' + r.calculation_id + ' | **Project:** ' + r.project_name + ' | **Type:** ' + r.conservation_type)
  lines.push('**Total Investment: $' + r.total_investment_usd.toLocaleString() + ' | **NPV: $' + r.net_present_value.toLocaleString() + ' | **BCR:** ' + r.benefit_cost_ratio.toFixed(2))
  lines.push('')
  lines.push('### Benefit Categories')
  lines.push('| Category | Annual Value | Total Value | Methodology | Confidence |')
  lines.push('|----------|--------------|-------------|-------------|------------|')
  for (const b of r.benefit_categories) {
    lines.push('| ' + b.category + ' | $' + Math.round(b.annual_value_usd).toLocaleString() + ' | $' + Math.round(b.total_value_usd).toLocaleString() + ' | ' + b.methodology + ' | ' + b.confidence + ' |')
  }
  lines.push('')
  lines.push('### Scenario Analysis')
  lines.push('| Scenario | NPV | BCR | Payback (yrs) | IRR | Success Prob |')
  lines.push('|----------|-----|-----|---------------|-----|--------------|')
  for (const s of r.scenarios) {
    lines.push('| ' + s.scenario + ' | $' + s.npv_usd.toLocaleString() + ' | ' + s.benefit_cost_ratio.toFixed(2) + ' | ' + s.payback_period_years + ' | ' + s.irr_percent.toFixed(1) + '% | ' + (s.probability_of_success * 100).toFixed(0) + '% |')
  }
  lines.push('')
  lines.push('### Cost Effectiveness')
  lines.push('- **Cost per species protected:** $' + r.cost_effectiveness_per_species.toLocaleString())
  lines.push('- **Cost per km2 protected:** $' + r.cost_effectiveness_per_km2.toLocaleString())
  lines.push('- **Total undiscounted benefits:** $' + r.total_benefits_usd.toLocaleString())
  lines.push('')
  lines.push('### Social Return Metrics')
  for (const s of r.social_return_metrics) lines.push('- ' + s)
  lines.push('')
  lines.push('### Risk Factors')
  for (const rf of r.risk_factors) lines.push('- **' + rf + '**')
  lines.push('')
  lines.push('### Investment Recommendations')
  for (const ir of r.investment_recommendations) lines.push('- [ ] ' + ir)
  lines.push('')
  lines.push('> **Disclaimer:** ' + DISCLAIMER)
  return lines.join('\n')
}

/* ─────────────────────────────────────────────
   Plugin Registration
   ───────────────────────────────────────────── */
export function apply(ctx: Context) {
  const tools = ctx.tools

  // Tool 1: Species Monitoring Engine
  tools.register(defineTool({
    name: 'species_monitoring_engine',
    description: 'Monitor species populations and detect trends across a region. Generates species observations with IUCN status, population estimates, trend analysis, and conservation priorities.',
    parameters: {
      input_data: { type: 'string' as const, required: true, description: 'JSON-encoded input. Fields: region (string), target_species (string[]), monitoring_duration_months (number), survey_method ("camera_trac"|"transect"|"acoustic"|"satellite"|"eDNA"|"mixed"), threat_level_filter ("critical"|"endangered"|"vulnerable"|"near_threatened"|"all"), include_population_trend (boolean)' },
    },
    output: {
      schema: { type: 'string' as const },
      render: (_a: any, v: any) => [{ type: 'text' as const, text: v as string }],
    },
    async execute(args: { input_data: string }) {
      const input: SpeciesMonitoringInput = JSON.parse(args.input_data)
      return formatSpeciesMonitoringReport(runSpeciesMonitoring(input))
    },
  }))

  // Tool 2: Habitat Analysis Mapper
  tools.register(defineTool({
    name: 'habitat_analysis_mapper',
    description: 'Analyze habitat conditions, fragmentation, and connectivity. Generates habitat zones with degradation levels, corridor analysis, climate projections, and conservation recommendations.',
    parameters: {
      input_data: { type: 'string' as const, required: true, description: 'JSON-encoded input. Fields: region (string), area_km2 (number), habitat_types (string[]), fragmentation_index_threshold (number), include_corridors (boolean), climate_projection_years (number)' },
    },
    output: {
      schema: { type: 'string' as const },
      render: (_a: any, v: any) => [{ type: 'text' as const, text: v as string }],
    },
    async execute(args: { input_data: string }) {
      const input: HabitatAnalysisInput = JSON.parse(args.input_data)
      return formatHabitatAnalysisReport(analyzeHabitat(input))
    },
  }))

  // Tool 3: Poaching Prevention System
  tools.register(defineTool({
    name: 'poaching_prevention_system',
    description: 'Predict poaching hotspots and recommend patrol routes. Generates risk maps, patrol plans, resource allocation, technology recommendations, and community engagement strategies.',
    parameters: {
      input_data: { type: 'string' as const, required: true, description: 'JSON-encoded input. Fields: protected_area (string), area_km2 (number), target_species (string[]), historical_incidents (number), patrol_coverage_percent (number), ranger_count (number), technology_level ("basic"|"intermediate"|"advanced"), community_engagement_level ("low"|"medium"|"high")' },
    },
    output: {
      schema: { type: 'string' as const },
      render: (_a: any, v: any) => [{ type: 'text' as const, text: v as string }],
    },
    async execute(args: { input_data: string }) {
      const input: PoachingPreventionInput = JSON.parse(args.input_data)
      return formatPoachingPreventionReport(runPoachingPrevention(input))
    },
  }))

  // Tool 4: Biodiversity Assessment Tool
  tools.register(defineTool({
    name: 'biodiversity_assessment_tool',
    description: 'Assess biodiversity indices and ecosystem health. Generates Shannon/Simpson indices, ecosystem service valuations, threat assessments, and management recommendations.',
    parameters: {
      input_data: { type: 'string' as const, required: true, description: 'JSON-encoded input. Fields: region (string), ecosystem_type (string), survey_area_km2 (number), taxa_groups (string[]), assessment_depth ("rapid"|"standard"|"comprehensive"), include_functional_diversity (boolean), reference_condition ("pristine"|"historical"|"best_available")' },
    },
    output: {
      schema: { type: 'string' as const },
      render: (_a: any, v: any) => [{ type: 'text' as const, text: v as string }],
    },
    async execute(args: { input_data: string }) {
      const input: BiodiversityAssessmentInput = JSON.parse(args.input_data)
      return formatBiodiversityAssessmentReport(assessBiodiversity(input))
    },
  }))

  // Tool 5: Wildlife Population Modeler
  tools.register(defineTool({
    name: 'wildlife_population_modeler',
    description: 'Model population dynamics and carrying capacity. Supports exponential, logistic, Leslie matrix, and individual-based models with stochasticity, intervention analysis, and population viability analysis.',
    parameters: {
      input_data: { type: 'string' as const, required: true, description: 'JSON-encoded input. Fields: species (string), current_population (number), carrying_capacity (number), growth_rate (number), time_horizon_years (number), model_type ("exponential"|"logistic"|"leslie_matrix"|"individual_based"), include_stochasticity (boolean), harvest_rate (number), conservation_intervention ("none"|"captive_breeding"|"habitat_restoration"|"anti_poaching"|"combined")' },
    },
    output: {
      schema: { type: 'string' as const },
      render: (_a: any, v: any) => [{ type: 'text' as const, text: v as string }],
    },
    async execute(args: { input_data: string }) {
      const input: PopulationModelingInput = JSON.parse(args.input_data)
      return formatPopulationModelingReport(modelPopulation(input))
    },
  }))

  // Tool 6: Migration Tracker
  tools.register(defineTool({
    name: 'migration_tracker',
    description: 'Track migration patterns and corridors. Generates route maps, stopover analysis, timing data, threat assessment, and climate impact projections for migratory species.',
    parameters: {
      input_data: { type: 'string' as const, required: true, description: 'JSON-encoded input. Fields: species (string), tracking_method ("GPS_collar"|"satellite_tag"|"geolocator"|"PIT_tag"|"acoustic"|"citizen_science"), study_duration_months (number), num_tracked_individuals (number), region (string), include_stopover_sites (boolean), climate_scenario ("current"|"warming_1.5C"|"warming_2C"|"warming_3C")' },
    },
    output: {
      schema: { type: 'string' as const },
      render: (_a: any, v: any) => [{ type: 'text' as const, text: v as string }],
    },
    async execute(args: { input_data: string }) {
      const input: MigrationTrackerInput = JSON.parse(args.input_data)
      return formatMigrationTrackerReport(trackMigration(input))
    },
  }))

  // Tool 7: Camera Trap Analyzer
  tools.register(defineTool({
    name: 'camera_trap_analyzer',
    description: 'Analyze camera trap data for species identification and occupancy. Generates detection rates, activity patterns, species richness estimates, rarefaction curves, and occupancy modeling results.',
    parameters: {
      input_data: { type: 'string' as const, required: true, description: 'JSON-encoded input. Fields: deployment_region (string), num_cameras (number), deployment_duration_days (number), target_species (string[]), habitat_type (string), include_species_id_accuracy (boolean), occupancy_modeling (boolean)' },
    },
    output: {
      schema: { type: 'string' as const },
      render: (_a: any, v: any) => [{ type: 'text' as const, text: v as string }],
    },
    async execute(args: { input_data: string }) {
      const input: CameraTrapInput = JSON.parse(args.input_data)
      return formatCameraTrapReport(analyzeCameraTraps(input))
    },
  }))

  // Tool 8: Conservation ROI Calculator
  tools.register(defineTool({
    name: 'conservation_roi_calculator',
    description: 'Calculate conservation project return on investment. Generates NPV, benefit-cost ratios, scenario analysis, cost-effectiveness metrics, social return analysis, and investment recommendations.',
    parameters: {
      input_data: { type: 'string' as const, required: true, description: 'JSON-encoded input. Fields: project_name (string), total_investment_usd (number), project_duration_years (number), conservation_type ("species_recovery"|"habitat_restoration"|"anti_poaching"|"community_conservation"|"protected_area"|"mixed"), target_species_count (number), area_protected_km2 (number), community_beneficiaries (number), carbon_offset_tons (number), ecotourism_potential ("low"|"medium"|"high"), discount_rate_percent (number)' },
    },
    output: {
      schema: { type: 'string' as const },
      render: (_a: any, v: any) => [{ type: 'text' as const, text: v as string }],
    },
    async execute(args: { input_data: string }) {
      const input: ConservationROIInput = JSON.parse(args.input_data)
      return formatConservationROIReport(calculateConservationROI(input))
    },
  }))

  console.log('[' + name + '] Loaded v0.1.0 - Wildlife Conservation & Ecology with 8 tools')
  console.log('  Tools: species_monitoring_engine, habitat_analysis_mapper, poaching_prevention_system, biodiversity_assessment_tool, wildlife_population_modeler, migration_tracker, camera_trap_analyzer, conservation_roi_calculator')
  console.log('  Market: $5B+ conservation tech, $3B+ ecology AI')
}
